### ISSUE TITLE
Cant connect with my pro account. 

### ISSUE THREAD

**Issue by koksalkapucuoglu** [googlecolab/colabtools#1285] opened 2020-05-30 11:05 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Cant connect with my pro account.  But I can connect and run code with other free account. 

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Opera
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

https://drive.google.com/file/d/1gx2WhWrek0t9aJf4jT0oz-XpyzKY4zZg/view?usp=sharing

**Comment by colaboratory-team** [comment] 2020-05-30 17:16
Duplicate of #1287

**Closed by colaboratory-team** 2020-05-30 17:16 UTC
