### ISSUE TITLE
R notebook crashes when using GPU 

### ISSUE THREAD

**Issue by mr-francois** [googlecolab/colabtools#2543] opened 2022-01-05 17:58 UTC
The following code runs without GPU but always crashes when changing runtime to GPU. A few weeks ago this did not lead to a crash.

```
install.packages("keras")
library(keras)
library(magrittr)

model <- keras_model_sequential()
model %>%
  layer_dense(input_shape = 10, units = 16) %>%
  layer_dense(units = 10, activation = 'softmax')
```
There always appears a `Your session crashed for an unknown reason.` message. This is the output of the runtime log 

```
Jan 5, 2022, 6:56:13 PM | WARNING | WARNING:root:kernel b33cc461-73aa-4cfb-99ce-7054ae4a3a7f restarted
Jan 5, 2022, 6:56:13 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Jan 5, 2022, 6:56:12 PM | WARNING | 2022-01-05  17:56:12.991510: F tensorflow/core/platform/statusor.cc:33] Attempting  to fetch value instead of handling error INTERNAL: failed initializing  StreamExecutor for CUDA device ordinal 0: INTERNAL: failed call to  cuDevicePrimaryCtxRetain: CUDA_ERROR_UNKNOWN: unknown error
Jan 5, 2022, 6:56:12 PM | WARNING | 2022-01-05  17:56:12.990169: W tensorflow/stream_executor/cuda/cuda_driver.cc:374] A  non-primary context 0x55bcc226b000 for device 0 exists before  initializing the StreamExecutor. The primary context is now  0x55bcc1e4f420. We haven't verified StreamExecutor works with that.
```

**Comment by cperry-goog** [comment] 2022-01-06 22:16
Duplicate of #2486

**Closed by cperry-goog** 2022-01-06 22:16 UTC
Labels: bug
