### ISSUE TITLE
module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by rita442** [googlecolab/colabtools#1131] opened 2020-04-06 21:15 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: module 'tensorflow' has no attribute 'placeholder' when using load_model

- Describe the expected behavior: 

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1BtfqMVbcTPnHzhomGWfRsI-HAnuIaNlt

**Comment by kamilbakierzynski** [comment] 2020-04-11 06:25
Import load_model function like that:
`from keras.models import load_model`
or change to:
`model = tensorflow.keras.models.load_model(m_path)`

**Comment by kamilbakierzynski** [comment] 2020-04-11 06:29
Change:
`from keras.engine.saving import load_model`
to:
`from keras.models import load_model`

Please close this issue as it is not a bug.

**Closed** 2020-04-17 13:29 UTC
