### ISSUE TITLE
Google Colab will not connect to GCE Machine

### ISSUE THREAD

**Issue by Eduard6421** [googlecolab/colabtools#3211] opened 2022-11-04 20:53 UTC
Greetings!
It seems that Google Colab is unable to connect to deployed resource on GCP; 

I have tried to connect by clicking on the provided button:
![image](https://user-images.githubusercontent.com/20836974/200071927-9fc89726-be02-42e8-ab76-94faf08dead8.png)

Afterwards I have selected the option connect to a custom GCE VM;
![image](https://user-images.githubusercontent.com/20836974/200072038-ebb27ba1-fb77-4919-812d-baf5a3fc276a.png)

I have provied the requested project id / zone id / instance id correctly yet when pressing connect the following message appears:

![image](https://user-images.githubusercontent.com/20836974/200072235-1af2e695-cfeb-4ffa-bd2c-41eeb2891ded.png)

From what I understand this is the preferred method to connect to the GCE VMs hosted in GCP yet it does not work as intended;
I have disabled my adblock / Signed out of all the other google accounts I have been signed into / I have cleared my internet cache and
 even disabled it / i have signed in and out countless times;
 Could you provide an alternative for me to be able to connect through google colab to the vm?
 This is really frustrating given the fact that I wish to make use of my GPU credits;

Kind regards,
Eduard

**Comment by RazorBest** [comment] 2022-11-04 21:01
I also have the same problem.

**Comment by sebbov** [comment] 2022-11-04 21:42
Could you send us info on your setup following the instructions at   https://github.com/googlecolab/colabtools/issues/3209#issuecomment-1303784325

Refer to this issue in the feedback you send.

Thanks

**Comment by craigcitro** [comment] 2022-11-04 21:52
Thanks for the report -- I'm marking this as a dupe of #3209, but as noted there, this was indeed a problem on our side and should now be fixed. You'll need to do a page refresh to pick up the fix.

**Closed by craigcitro** 2022-11-04 21:52 UTC
Labels: bug
