### ISSUE TITLE
high disk usage after resetting run time

### ISSUE THREAD

**Issue by maxxx580** [googlecolab/colabtools#884] opened 2019-11-28 18:12 UTC
Describe the current behavior: colabs show high disk usage after I reset run time (no file was loaded yet).
Describe the expected behavior: very low disk usage
browser: chrome

![Screen Shot 2019-11-28 at 1 09 42 PM](https://user-images.githubusercontent.com/8864669/69826311-96e29680-11e0-11ea-8078-727f7f44f56b.png)

**Comment by colaboratory-team** [comment] 2019-11-28 19:39
Duplicate of #876

**Closed by colaboratory-team** 2019-11-28 19:39 UTC
