### ISSUE TITLE
Create new account, have just paid subscription for Colab Pro. But no GPU available???

### ISSUE THREAD

**Issue by giaabaoo** [googlecolab/colabtools#1953] opened 2021-04-11 06:46 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by cperry-goog** [comment] 2024-05-09 16:42
Closing due to staleness. File a new bug with reproducible steps if this is an issue.

**Closed by cperry-goog** 2024-05-09 16:42 UTC
