### ISSUE TITLE
Matplotlib 

### ISSUE THREAD

**Issue by kalathurkishore** [googlecolab/colabtools#3446] opened 2023-02-27 08:27 UTC
I am facing issue with matplotlib scatter plot where last week the entire code was working fine but throwing some warnings.
Now When i re-run the code again for plotting the data I am getting the error as "TypeError: must be real number, not str"

There is issue in the matplotlib package as shown below. Earlier version of matplotlib is working fine. There may be a possible mismatch of some packages and libraries in matplotlib.

Could you please resolve the issue it would be very helpful?

Please find the code

WARNING:matplotlib.axes._axes:*c* argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with *x* & *y*.  Please use the *color* keyword-argument or provide a 2D array with a single row if you intend to specify the same RGB or RGBA value for all points.
WARNING:matplotlib.axes._axes:*c* argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with *x* & *y*.  Please use the *color* keyword-argument or provide a 2D array with a single row if you intend to specify the same RGB or RGBA value for all points.
WARNING:matplotlib.axes._axes:*c* argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with *x* & *y*.  Please use the *color* keyword-argument or provide a 2D array with a single row if you intend to specify the same RGB or RGBA value for all points.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-2-acf8492cf700>](https://localhost:8080/#) in <module>
     62     addToPlot(coordinateList[i])
     63 plt.scatter(coordinateList[0][0][0],coordinateList[0][0][1], c='black', edgecolor='black', linewidth='2', s=1000, marker='h')
---> 64 plt.savefig('plotting-30000-kdd.pdf',bbox_inches="tight")
     65 plt.show()

13 frames
[/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py](https://localhost:8080/#) in savefig(*args, **kwargs)
    976     fig = gcf()
    977     res = fig.savefig(*args, **kwargs)
--> 978     fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors
    979     return res
    980 

[/usr/local/lib/python3.8/dist-packages/matplotlib/backend_bases.py](https://localhost:8080/#) in draw_idle(self, *args, **kwargs)
   2058         if not self._is_idle_drawing:
   2059             with self._idle_draw_cntx():
-> 2060                 self.draw(*args, **kwargs)
   2061 
   2062     @property

[/usr/local/lib/python3.8/dist-packages/matplotlib/backends/backend_agg.py](https://localhost:8080/#) in draw(self)
    434              (self.toolbar._wait_cursor_for_draw_cm() if self.toolbar
    435               else nullcontext()):
--> 436             self.figure.draw(self.renderer)
    437             # A GUI class may be need to update a window using this draw, so
    438             # don't forget to call the superclass.

[/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py](https://localhost:8080/#) in draw_wrapper(artist, renderer, *args, **kwargs)
     72     @wraps(draw)
     73     def draw_wrapper(artist, renderer, *args, **kwargs):
---> 74         result = draw(artist, renderer, *args, **kwargs)
     75         if renderer._rasterizing:
     76             renderer.stop_rasterizing()

[/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py](https://localhost:8080/#) in draw_wrapper(artist, renderer)
     49                 renderer.start_filter()
     50 
---> 51             return draw(artist, renderer)
     52         finally:
     53             if artist.get_agg_filter() is not None:

[/usr/local/lib/python3.8/dist-packages/matplotlib/figure.py](https://localhost:8080/#) in draw(self, renderer)
   2843 
   2844             self.patch.draw(renderer)
-> 2845             mimage._draw_list_compositing_images(
   2846                 renderer, self, artists, self.suppressComposite)
   2847 

[/usr/local/lib/python3.8/dist-packages/matplotlib/image.py](https://localhost:8080/#) in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130     if not_composite or not has_images:
    131         for a in artists:
--> 132             a.draw(renderer)
    133     else:
    134         # Composite any adjacent images together

[/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py](https://localhost:8080/#) in draw_wrapper(artist, renderer)
     49                 renderer.start_filter()
     50 
---> 51             return draw(artist, renderer)
     52         finally:
     53             if artist.get_agg_filter() is not None:

[/usr/local/lib/python3.8/dist-packages/matplotlib/axes/_base.py](https://localhost:8080/#) in draw(self, renderer)
   3089             renderer.stop_rasterizing()
   3090 
-> 3091         mimage._draw_list_compositing_images(
   3092             renderer, self, artists, self.figure.suppressComposite)
   3093 

[/usr/local/lib/python3.8/dist-packages/matplotlib/image.py](https://localhost:8080/#) in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    130     if not_composite or not has_images:
    131         for a in artists:
--> 132             a.draw(renderer)
    133     else:
    134         # Composite any adjacent images together

[/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py](https://localhost:8080/#) in draw_wrapper(artist, renderer)
     49                 renderer.start_filter()
     50 
---> 51             return draw(artist, renderer)
     52         finally:
     53             if artist.get_agg_filter() is not None:

[/usr/local/lib/python3.8/dist-packages/matplotlib/collections.py](https://localhost:8080/#) in draw(self, renderer)
    988     def draw(self, renderer):
    989         self.set_sizes(self._sizes, self.figure.dpi)
--> 990         super().draw(renderer)
    991 
    992 

[/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py](https://localhost:8080/#) in draw_wrapper(artist, renderer)
     49                 renderer.start_filter()
     50 
---> 51             return draw(artist, renderer)
     52         finally:
     53             if artist.get_agg_filter() is not None:

[/usr/local/lib/python3.8/dist-packages/matplotlib/collections.py](https://localhost:8080/#) in draw(self, renderer)
    418             gc.set_antialiased(self._antialiaseds[0])
    419             gc.set_url(self._urls[0])
--> 420             renderer.draw_markers(
    421                 gc, paths[0], combined_transform.frozen(),
    422                 mpath.Path(offsets), transOffset, tuple(facecolors[0]))

TypeError: must be real number, not str
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/IPython/core/formatters.py](https://localhost:8080/#) in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

17 frames
[/usr/local/lib/python3.8/dist-packages/matplotlib/collections.py](https://localhost:8080/#) in draw(self, renderer)
    418             gc.set_antialiased(self._antialiaseds[0])
    419             gc.set_url(self._urls[0])
--> 420             renderer.draw_markers(
    421                 gc, paths[0], combined_transform.frozen(),
    422                 mpath.Path(offsets), transOffset, tuple(facecolors[0]))

TypeError: must be real number, not str
<Figure size 1296x1296 with 4 Axes>

**Comment by mco-gh** [comment] 2023-02-27 09:18
Can you reproduce this outside of colab? If not, it's likely a usage error with respect to matplotlib, in which case I'd suggest posting your question on stackoverflow, which is better equipped to support matplotlib.

I'll close this for now but you can reopen it if you're convinced that this is due to a bug in colab (i.e. if you find that the same code works fine in another environment).

**Comment by kalathurkishore** [comment] 2023-02-27 09:28
Actually the same code without any change was working last week.

**Comment by mco-gh** [comment] 2023-02-27 09:31
Can you verify it still works outside colab? If it does, please add a link to a cleaned-of-anything-proprietary copy of your notebook and I'll see if I can help you debug it.

**Comment by kalathurkishore** [comment] 2023-02-27 09:35
Can you please find the below link of the code
[code url](https://colab.research.google.com/drive/1kQ75gB_Hb2MYSVLcsoRX1arsA2ejeZkv?usp=sharing)

**Comment by kalathurkishore** [comment] 2023-02-27 10:01
Could you please reopen the issue?

Any update on the issue

**Comment by mco-gh** [comment] 2023-02-27 10:15
The problem is you've coded linewidth, in your plt.scatter method call, as a string but it needs to be a real number (try changing '2' to 2 and see if that avoids the error, as it did for me).

In the future, I think stackoverflow would be a better method for solving these sort of problems that are intrinsically related to matplotlib (or any other python library not directly related to colab execution).

**Closed by mco-gh** 2023-02-27 10:15 UTC
Labels: bug

**Comment by kalathurkishore** [comment] 2023-02-27 10:32
Okay Thanks a lot!
