### ISSUE TITLE
Unable to use Colab - Getting error: "Sorry, no backends available. Please try again later

### ISSUE THREAD

**Issue by cameliaburlacu98** [googlecolab/colabtools#1290] opened 2020-05-30 12:00 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use stackoverflow.

Describe the current behavior: Unable to use Colab - Getting error: "Sorry, no backends available. Please try again later."

Describe the expected behavior: Expected to be used without any error.

The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

Link to self-contained notebook that reproduces this issue
(click the Share button, then Get Shareable Link): https://colab.research.google.com/drive/1Zc0S9O4WR6DDw7-SkVWB09VzqDWwgnJX#scrollTo=GaZqfwsOV067

**Comment by akbarhusnoo** [comment] 2020-05-30 12:03
Having this issue

**Comment by colaboratory-team** [comment] 2020-05-30 17:23
Duplicate of #1287

**Closed by colaboratory-team** 2020-05-30 17:23 UTC
