### ISSUE TITLE
"Google Account changed" keeps showing up

### ISSUE THREAD

**Issue by hanshengchiu** [googlecolab/colabtools#1111] opened 2020-04-02 17:22 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Since April 2nd, every time after I've started TPU training for few minutes, a "Google Account changed" message keeps popping up one after another. The dialog says "The current account has changed, please refresh the page to continue". Refreshing the page doesn't help. I've tried using Chrome Beta/Stable, incognito mode, and different google accounts. No fix. Same code was working days ago.
- Describe the expected behavior:
There shouldn't be such message because I didn't change account.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome stable v80.0.3987.162 (Official Build) (64-bit) and Chrome beta.

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
![Untitled](https://user-images.githubusercontent.com/17819084/78275699-86527c00-7544-11ea-91d0-a929c6343891.png)

**Comment by katlyn-edwards** [comment] 2020-04-02 18:11
Hey there! Thanks for the report. 

Can you provide a minimal repro notebook? I connected to a TPU successfully and was able to execute code. 

Additionally, when it happens, can you file in-app feedback so that we can gather app state data?
You can do this by clicking "Help" and then "Send Feedback". 
You can link to this github issue to help us more easily identify your report.

**Comment by katlyn-edwards** [comment] 2020-04-02 18:13
One more thing I just thought of - can you let us know if you're using multilogin? (e.g. you're signed into multiple Google accounts), and if you are, if you have multiple Colab tabs open with the various accounts?

**Comment by hanshengchiu** [comment] 2020-04-02 18:27
> One more thing I just thought of - can you let us know if you're using multilogin? (e.g. you're signed into multiple Google accounts), and if you are, if you have multiple Colab tabs open with the various accounts?

I used to have two tabs before last week. But today I have been using only one tab.

**Comment by hanshengchiu** [comment] 2020-04-02 18:53
> Hey there! Thanks for the report.
> 
> Can you provide a minimal repro notebook? I connected to a TPU successfully and was able to execute code.
> 
> Additionally, when it happens, can you file in-app feedback so that we can gather app state data?
> You can do this by clicking "Help" and then "Send Feedback".
> You can link to this github issue to help us more easily identify your report.

I am not able to click Help and Send Feedback because the messages appear as modal dialog and pressing the REFRESH button in the dialogs doesn't close them all.

I also noticed error messages in Chrome's console -
![Untitled](https://user-images.githubusercontent.com/17819084/78290237-01705e00-7556-11ea-8111-e63bbf22c9fb.png)

**Comment by katlyn-edwards** [comment] 2020-04-02 19:04
You can close the dialog before sending feedback. A repro notebook would be beneficial, since it seems like the problem is rooted with writing/reading from Drive in some way.

**Comment by hanshengchiu** [comment] 2020-04-02 19:28
> > Hey there! Thanks for the report.
> > Can you provide a minimal repro notebook? I connected to a TPU successfully and was able to execute code.
> > Additionally, when it happens, can you file in-app feedback so that we can gather app state data?
> > You can do this by clicking "Help" and then "Send Feedback".
> > You can link to this github issue to help us more easily identify your report.
> 
> I am not able to click Help and Send Feedback because the messages appear as modal dialog and pressing the REFRESH button in the dialogs doesn't close them all.
> 
> I also noticed error messages in Chrome's console -
> ![Untitled](https://user-images.githubusercontent.com/17819084/78290954-2913f600-7557-11ea-86e6-47279a9e7572.png)

Request URL: https://clients6.google.com/upload/drive/v2beta/files/13JvKLPZVMT64lqv3Lin3xNX6tkIl1lXW?uploadType=multipart&fields=alternateLink%2Ccapabilities%2FcanReadRevisions%2CdownloadUrl%2CfileSize%2Cid%2Clabels%2CmimeType%2CoriginalFilename%2Cowners%2Cparents%2Cproperties%2Cshared%2CteamDriveId%2Ctitle%2CuserPermission%2CheadRevisionId&supportsTeamDrives=true&key=[****removed*****]&%24unique=gc538
Request Method: PUT
Status Code: 404 
Remote Address: 172.217.160.110:443
Referrer Policy: origin
access-control-allow-credentials: true
access-control-allow-origin: https://colab.research.google.com
access-control-expose-headers: Content-Length, Content-Security-Policy, Content-Type, Date, Server, Transfer-Encoding, Vary, X-GUploader-UploadID, X-Google-Trace
alt-svc: h3-Q050=":443"; ma=2592000, h3-Q049=":443"; ma=2592000, h3-Q048=":443"; ma=2592000, h3-Q046=":443"; ma=2592000, h3-Q043=":443"; ma=2592000, h3-T050=":443"; ma=2592000
content-length: 298
content-security-policy: default-src 'none'; report-uri https://csp.withgoogle.com/csp/scotty/2;
content-type: application/json; charset=UTF-8
date: Thu, 02 Apr 2020 19:05:01 GMT
server: UploadServer
set-cookie: SIDCC=AJi4QfG0un32t1tRD4RcTA3KvaQKJLe7MB-HRMGn8u49JMl_65UM2Aowvs5jZh1jTeD6gAFqmAk; expires=Fri, 02-Apr-2021 19:05:01 GMT; path=/; domain=.google.com; priority=high
status: 404
vary: Origin
vary: X-Origin
x-guploader-uploadid: AEnB2UpPX32DSiucTDvX2dew8Os1mh9Nds6P2A91DUcanrRnrHdpPhxE17cyV-Dyprw2sZI-7dIb78yM890cNA_1eFrpG2BFIw
:authority: clients6.google.com
:method: PUT
:path: /upload/drive/v2beta/files/13JvKLPZVMT64lqv3Lin3xNX6tkIl1lXW?uploadType=multipart&fields=alternateLink%2Ccapabilities%2FcanReadRevisions%2CdownloadUrl%2CfileSize%2Cid%2Clabels%2CmimeType%2CoriginalFilename%2Cowners%2Cparents%2Cproperties%2Cshared%2CteamDriveId%2Ctitle%2CuserPermission%2CheadRevisionId&supportsTeamDrives=true&key=[****removed*****]&%24unique=gc538
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,zh-TW;q=0.8,zh-CN;q=0.7,zh;q=0.6
authorization: SAPISIDHASH 1585854301_c1c49ab37f8e5774fcbc08325f16f337e126c624
content-length: 247
content-type: multipart/mixed; boundary="-------314159265358979323846"
cookie: CONSENT=YES+FR.en-GB+V9; SEARCH_SAMESITE=CgQIzY4B; ANID=AHWqTUmlayNeiNSJ1uF97DjL0nXSPRhm_vFATDSEgBVJmiS1K-ONmBuxbLJUQoLA; S=billing-ui-v3=tTVmRYENnWZiLApJp0h--CxhwfFv739E:billing-ui-v3-efe=tTVmRYENnWZiLApJp0h--CxhwfFv739E; SID=vgcb_bi2jMffzVcuVkzBh4kM9n3letrD58iBFqE1QM9aK959YFXaq_xrJTS90cAKCQIItg.; __Secure-3PSID=vgcb_bi2jMffzVcuVkzBh4kM9n3letrD58iBFqE1QM9aK959pBkqgXknDCAcAPff8e9YCQ.; HSID=Aa-8jJJNekwsP2ZRJ; SSID=AQV3j8QmsZU-sL4pF; APISID=ebl109C-FYplL6Ec/APsUnCwBq9d_hBtEE; SAPISID=QEYe-O16Mz7SEcSx/AmATydCPpn5lleR_7; __Secure-HSID=Aa-8jJJNekwsP2ZRJ; __Secure-SSID=AQV3j8QmsZU-sL4pF; __Secure-APISID=ebl109C-FYplL6Ec/APsUnCwBq9d_hBtEE; __Secure-3PAPISID=QEYe-O16Mz7SEcSx/AmATydCPpn5lleR_7; NID=201=x-MfANJ4LFuaVGCrYpoUrsg_w6XEZeqHqnD_EJDNxrPcmJkxiVZrdbXuPubNtbmqMPFa29duK1Gi0xy0uAZ3nKm5dz1d_GqWOXFN0V31a54hhXcKxOU3DYAIgIjacbYAt4HBKF1xWq8EMyGuuKCmSaxftmD7jOj_yuD_VMQ1w_-ajoNj7ZWW-WaVUmwsWIWkQV4nm5WN0YoZPy_XlCEKqedEVix9kKsGQJK9eY0Hfkk-CopRDCfF3INpSHTxwesX6wyZ4AQVSxexebSQKnPKiNe6zzL2jizS6SKnjd06atcpYXaPdhkqa2wHQwWeYEgn3dR8gLfmGc2GGGPJFm_cp_-yn6ZtVYrJRcuiMt8ECFz0ursFcg; 1P_JAR=2020-4-2-19; SIDCC=AJi4QfF_223g2Oex3O4-f-rhp9X7jz8doVlpBcxZ-rAZ7a7R6gDanUK2O5fnaQ0ibPxPxjCgbJ0
dnt: 1
origin: https://colab.research.google.com
referer: https://colab.research.google.com/
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36
x-client-data: CJe2yQEIpLbJAQjBtskBCIqSygEIqZ3KAQjQr8oBCLywygEIl7XKAQjttcoBCI66ygEImb3KAQ==
x-clientdetails: appVersion=5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F80.0.3987.162%20Safari%2F537.36&platform=Win32&userAgent=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F80.0.3987.162%20Safari%2F537.36
x-goog-authuser: 1
x-goog-encode-response-if-executable: base64
x-javascript-user-agent: google-api-javascript-client/1.1.0
x-requested-with: XMLHttpRequest
uploadType: multipart
fields: alternateLink,capabilities/canReadRevisions,downloadUrl,fileSize,id,labels,mimeType,originalFilename,owners,parents,properties,shared,teamDriveId,title,userPermission,headRevisionId
supportsTeamDrives: true
key: [****removed*****]
$unique: gc538
---------314159265358979323846
Content-Type: application/json

{"title":"a755af1c-12ce-4310-8a99-f60274a4fffb"}
---------314159265358979323846
Content-Type: application/json

{"outputs":[],"resources":{}}
---------314159265358979323846--

**Comment by hanshengchiu** [comment] 2020-04-02 20:02
> You can close the dialog before sending feedback. A repro notebook would be beneficial, since it seems like the problem is rooted with writing/reading from Drive in some way.

Tested again without mounting google drive. Same messages showed up and same http 404 errors occurred. 
The message dialogs showed up faster than I could move cursor to Help menu.

**Comment by katlyn-edwards** [comment] 2020-04-03 00:25
Does this reproduce in an incognito window? 

If it doesn't, can you try signing out and back in again? 
If that doesn't fix it, can you try clearing your cookies?

**Comment by hanshengchiu** [comment] 2020-04-03 04:57
> Does this reproduce in an incognito window?
> 
> If it doesn't, can you try signing out and back in again?
> If that doesn't fix it, can you try clearing your cookies?

It reproduces in incognito mode.

**Comment by katlyn-edwards** [comment] 2020-04-03 20:42
Thanks for the tip, we have an idea of what we think is going on. 
Tracking internally in b/153188464

**Comment by katlyn-edwards** [comment] 2020-04-03 21:30
This should be fixed; please feel free to reopen if this still persists after a page reload.

**Closed by katlyn-edwards** 2020-04-03 21:30 UTC

**Comment by AmitSharma1127** [comment] 2020-09-04 06:23
Same issue. I can see the dialogue box with the same message when I try to train a CNN, with not so large dataset

**Comment by bpisaacoff** [comment] 2020-10-04 23:38
I am also getting this error while using ```matplotlib.pyplot.show()``` repeatedly inside a loop
