### ISSUE TITLE
Google Colab outputs disappears right after is shown 

### ISSUE THREAD

**Issue by jay-p007** [googlecolab/colabtools#4961] opened 2024-11-22 06:27 UTC
When running a code cell in Google Colab, the output momentarily appears and then disappears. It becomes visible only when selecting the "View output in fullscreen" option. This issue occurs consistently across different browsers and notebooks.

**Comment by cperry-goog** [comment] 2024-12-19 22:43
dupe of #4964

**Closed by cperry-goog** 2024-12-19 22:43 UTC
Labels: bug

**Comment by jay-p007** [comment] 2025-03-05 07:52
closed
