### ISSUE TITLE
users who cannot use Colab

### ISSUE THREAD

**Issue by ProChore** [googlecolab/colabtools#2310] opened 2021-09-27 15:59 UTC
Hello,
Some users of our domain can't longer use Colab. They have an error message "you do not have access to this service, to request access contact the administrator." But the service is well configured. Google support couldn't help me.
How to do ?
Could you help me please ?
Thanks.

![colab](https://user-images.githubusercontent.com/91486355/134943711-202f733f-bc37-401e-bcd2-5d65f3ca5375.png)

**Comment by craigcitro** [comment] 2021-09-27 16:10
Could this be a dupe of #2264?

**Comment by ProChore** [comment] 2021-09-27 16:53
Yes, exactly ! Thanks

**Closed** 2021-09-27 16:53 UTC
Labels: bug
