### ISSUE TITLE
Cannot create new Phython3 notebook

### ISSUE THREAD

**Issue by marcustankw** [googlecolab/colabtools#710] opened 2019-08-21 21:50 UTC
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
![image](https://user-images.githubusercontent.com/44251972/63470210-a019d580-c431-11e9-8a89-4b30e24939a8.png)

I am trying to create a new Phyton3 Notebook but this problem appeared. Colab seems to be connected to my Google Drive but for some reason I cannot create or save any notebooks in my drive from Colab. I have researched and tried every single solution suggested online (like blocking extensions, using incognito mode, mounting my google drive, etc), but the problem still persists. It seems to be a common problem that alot of people have been facing but there isn't really a solid solution.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome and Firefox

**Comment by braxtonj** [comment] 2019-08-21 22:56
I am running into the same issue for both Python 2 and 3 notebooks.  Using Chrome.

**Comment by blois** [comment] 2019-08-21 23:50
We're working on a fix for this right now. In the meantime a workaround is to go to drive.google.com and manually create a folder named `Colab Notebooks`.

**Comment by medright** [comment] 2019-08-22 01:19
also seeing this when trying to "copy to drive" from an existing notebook. 
<img width="1440" alt="Screen Shot 2019-08-21 at 5 38 39 PM" src="https://user-images.githubusercontent.com/4702913/63478817-33f29e00-c440-11e9-8072-acb8c820e9e7.png">

**Comment by katlyn-edwards** [comment] 2019-08-22 02:37
This should be fixed now; if you're still seeing this feel free to re-open.

**Closed by katlyn-edwards** 2019-08-22 02:37 UTC

**Comment by dforderek** [comment] 2019-09-26 10:26
I'm experiencing this problem too!

`` 
Error loading https://apis.google.com/js/client.js
Error: Error loading https://apis.google.com/js/client.js
    at HTMLScriptElement.k.onerror (https://colab.research.google.com/v2/external/gapi_loader.js:9:415)``

**Comment by blois** [comment] 2019-09-26 15:27
That error is most likely caused by an extension blocking that script- I would recommend trying incognito mode.

**Comment by Montesl** [comment] 2019-11-22 19:21
I am experiencing the same issue today. Anyone else with the same issue?

**Comment by Montesl** [comment] 2019-11-22 19:27
It is back!

**Comment by colaboratory-team** [comment] 2019-11-22 20:01
Hello Montesl - we are aware of some users having issues today related to drive notebook creation, and are working on addressing the problem ASAP.

**Comment by Mercurrent** [comment] 2020-03-30 07:16
Hi Colab team, any progress on this issue? I ran into it today using Edge browser.

**Comment by Tagbo-Aroh** [comment] 2020-04-04 13:38
Hi Colab team,

I ran into the same issue just last night while using chrome browser.

**Comment by zhenglidreams** [comment] 2020-07-14 06:51
Hi Colab, I meet this problem today, I remove "Colab Notebooks", but it still has error ' Unable to load Colaboratory.'

**Comment by 1996SEJR** [comment] 2020-09-20 01:45
I have the same problem
Collaboratory cannot be loaded.
Error loading https://apis.google.com/js/client.js
Error: Error loading https://apis.google.com/js/client.js
     at HTMLScriptElement.k.onerror (https://colab.research.google.com/v2/external/gapi_loader.js:15:415)

**Comment by Wangxinqian** [comment] 2021-09-17 02:25
Hi colab team, the situation is happening again!
![image](https://user-images.githubusercontent.com/35109234/133714280-f10c008f-5a33-4404-b8c1-d2bcda2cb9af.png)

**Comment by colaboratory-team** [comment] 2021-09-17 04:12
> Hi colab team, the situation is happening again!
> ![image](https://user-images.githubusercontent.com/35109234/133714280-f10c008f-5a33-4404-b8c1-d2bcda2cb9af.png)

This is a distinct issue tracked in https://github.com/googlecolab/colabtools/issues/2250

**Comment by Tanoy004** [comment] 2021-09-17 08:33
Hi colab Team,
I have faced a critical situation since last night.  It shows flooding error........keeps flooding but couldn't open file.

**Comment by krish-source** [comment] 2021-09-17 13:33
Hi Team,

I'm unable to load collab notebooks have tried all steps

**Comment by SB2318** [comment] 2021-09-17 14:22
Hi Team, 
I'm also unable to load collab notebooks. Please help `me.
external_polymer_binary.js?vrz=colab-20210915-060048-RC00_396786732:1585 Recording uncaught error: TypeError TypeError: Cannot read properties of undefined (reading '0')
(anonymous) @ external_polymer_binary.js?vrz=colab-20210915-060048-RC00_396786732:1585
error (async)
Qha @ external_polymer_binary.js?vrz=colab-20210915-060048-RC00_396786732:1585
QP @ external_polymer_binary.js?vrz=colab-20210915-060048-RC00_396786732:2557
V8 @ external_polymer_binary.js?vrz=colab-20210915-060048-RC00_396786732:5150
(anonymous) @ external_polymer_binary.js?vrz=colab-20210915-060048-RC00_396786732:5630
(anonymous) @ external_polymer_binary.js?vrz=colab-20210915-060048-RC00_396786732:5630
VM277 editor.main.js:6 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Object.localize (VM277 editor.main.js:6)
    at VM277 editor.main.js:620
    at Function.r._invokeFactory (loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:834)
    at r.complete (loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:845)
    at r._onModuleComplete (loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1354)
    at r._onModuleComplete (loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1362)
    at r._onModuleComplete (loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1362)
    at r._resolve (loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1318)
    at r.defineModule (loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1039)
    at o (loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1250)
(anonymous) @ VM277 editor.main.js:6
(anonymous) @ VM277 editor.main.js:620
r._invokeFactory @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:834
r.complete @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:845
r._onModuleComplete @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1354
r._onModuleComplete @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1362
r._onModuleComplete @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1362
r._resolve @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1318
r.defineModule @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1039
o @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1250
s @ VM277 editor.main.js:6
r._invokeFactory @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:834
r.complete @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:845
r._onModuleComplete @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1354
r._onModuleComplete @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1362
r._resolve @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1318
r.defineModule @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1039
g @ loader.js?vrz=colab-20210915-060048-RC00_396786732:formatted:1389
(anonymous) @ editor.main.nls.js?vrz=colab-20210915-060048-RC00_396786732:7

**Comment by ShaswatPA** [comment] 2022-09-05 05:45
Still running into this error and the solution does not seem to be straightforward so far! :/

A network error occurred and the request could not be completed.
GapiError: A network error occurred and the request could not be completed.
    at kE.pt [as constructor] (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__en_gb.js?vrz=colab-20220901-060049-RC00_471494601:670:878)
    at new kE (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__en_gb.js?vrz=colab-20220901-060049-RC00_471494601:1571:110)
    at va.program_ (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__en_gb.js?vrz=colab-20220901-060049-RC00_471494601:1662:437)
    at xa (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__en_gb.js?vrz=colab-20220901-060049-RC00_471494601:20:336)
    at va.throw_ (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__en_gb.js?vrz=colab-20220901-060049-RC00_471494601:19:403)
    at ya.throw (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__en_gb.js?vrz=colab-20220901-060049-RC00_471494601:21:248)
    at c (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__en_gb.js?vrz=colab-20220901-060049-RC00_471494601:21:504)
