### ISSUE TITLE
Student Pro

### ISSUE THREAD

**Issue by rhobro** [googlecolab/colabtools#2995] opened 2022-08-15 15:58 UTC
Hi there,

I am a student and I'm working with the OpenImages dataset. Unfortunately, I found out that it was around 500gigs while colab free workspaces are limited to around 100.

I am verified by github student developer pack and can send student transcripts if required. Please could I get access to colab pro with my student status?

Thanks

**Comment by cperry-goog** [comment] 2022-08-18 21:45
Dupe of #2367

**Closed by cperry-goog** 2022-08-18 21:45 UTC
Labels: feature
