### ISSUE TITLE
ValueError: mount failed: invalid oauth code

### ISSUE THREAD

**Issue by sajanraj** [googlecolab/colabtools#1566] opened 2020-09-07 05:40 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).
I have given the correct auth code generated from drive, but still getting this error.

- Describe the current behavior:
`
Enter your authorization code:
··········
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-d5df0069828e> in <module>()
      1 from google.colab import drive
----> 2 drive.mount('/content/drive')

/usr/local/lib/python3.6/dist-packages/google/colab/drive.py in mount(mountpoint, force_remount, timeout_ms, use_metadata_server)
    247       wrote_to_fifo = True
    248     elif case == 5:
--> 249       raise ValueError('mount failed: invalid oauth code')
    250   if not wrote_to_fifo:
    251     with open(fifo, 'w') as fifo_file:

ValueError: mount failed: invalid oauth code`

- Describe the expected behavior:
I always used this method, I don't know why I get this error.
- The web browser you are using (Chrome, Firefox, Safari, etc.):
chrome , ubuntu
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by Pratik6720** [comment] 2020-09-07 06:37
Hey just copy your authorization code and paste it in notepad empty file, from notpead  copy the auth code and paste it in cell it worked for me....

**Comment by craigcitro** [comment] 2020-09-07 06:51
The copy button is broken on the oauth page; just select the code and copy manually.

Duplicate of #1540

**Closed by craigcitro** 2020-09-07 06:51 UTC

**Comment by sajanraj** [comment] 2020-09-07 11:05
thank you @craigcitro. I feel it like a rare reason made on indention to avoid something?!
