### ISSUE TITLE
Error fetching credentials

### ISSUE THREAD

**Issue by cbmaine** [googlecolab/colabtools#1567] opened 2020-09-07 07:49 UTC
**Bug report for Colab:** http://colab.research.google.com/.

**Current behavior:**
The following code throws an Authorization Error for any account I try to use, even for accounts that worked previously.
```
from google.colab import auth
auth.authenticate_user()
```
```
/usr/local/lib/python3.6/dist-packages/google/colab/auth.py in _gcloud_login()
     97     _os.remove(name)
     98   if gcloud_process.returncode:
---> 99     raise _errors.AuthorizationError('Error fetching credentials')
    100 
    101 

AuthorizationError: Error fetching credentials
```

**Comment by craigcitro** [comment] 2020-09-07 15:39
The copy button on the oauth page isn't working; manually select and copy the code to paste in.

Duplicate of #1540.

**Closed by craigcitro** 2020-09-07 15:39 UTC
