### ISSUE TITLE
Heavier compatibility with Jupyter commands?

### ISSUE THREAD

**Issue by rdipietro** [googlecolab/colabtools#132] opened 2018-04-17 12:56 UTC
First, thank you for Colab ! It's really amazing for getting large groups of people up and running in only a few minutes.

I am wondering whether it might be worth creating a checklist of very simple compatibility that was lost, for consistency when switching between Jupyter / Colab (e.g. as I do on a regular basis, for my own work vs. teaching).

Example 1: Ctrl M vs. Esc for multi-key shortcuts. This seems simple enough, but when regularly switching back and forth, it is inevitable that I accidentally (but repeatedly) hit Esc in Colab and Ctrl M in Jupyter.

Example 2: "Run cells before the current" vs "Run all cells above". Again, simple enough, but it adds the mental overhead of "which arbitrary choice was it?" when we hit Ctrl Command P and need to decide between "above" and "before". (Also "above" is more consistent with other commands.)

**Comment by rdipietro** [comment] 2018-04-17 14:52
Another example:

a
b
(my cursor is here)
c

Jupyter: Ctrl + shift + - cleanly splits this into two cells, the first with 2 lines and the second with 1 line.

Colab: Ctrl + shift + - does nothing. Ctrl M, - splits, but less cleanly, leaving 3 lines in the first cell and 2 lines in the second, which then need to be manually removed.

**Comment by CSEMike** [comment] 2018-04-17 15:34
Duplicate of #75

**Closed by CSEMike** 2018-04-17 15:34 UTC

**Comment by rrmistry** [comment] 2019-03-20 03:32
Keyboard shortcuts aside, I have noticed that the command palette command names are very different from Jupyter as well.

I think @rdipietro's example 2 was trying to address the command palette rather than the keyboard shortcuts.

The palette was the primary way for me to navigate Jupyter notebooks. But now I have to figure out what the new command key words are mapped to in Google Colab.

Not a deal breaker but definitely would help a lot to have consistent naming conventions.

@CSEMike, I am not sure if this belongs in a new [Feature Request] issue or can this be issue re-opened?

Thank you!

**Comment by aeamaea** [comment] 2019-05-21 18:39
Just shaking my head!
