### ISSUE TITLE
Error: Folder Creation Failed

### ISSUE THREAD

**Issue by Tylersuard** [googlecolab/colabtools#1116] opened 2020-04-04 06:14 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I created a folder called "checkpoints."  I am now trying to create a folder inside of that one.  I right-click on "checkpoints" and click "new folder".  I receive the following error message:

Error
Folder creation failed

Could not fetch resource at https://colab.research.google.com/tun/m/gpu-p100-s-dcu6mqtg4n9q/api/contents/content/music-translation/checkpoints?authuser=0: 500 Internal Server Error
Rb@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200402-085600-RC00_304410412:114:91
Tv@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200402-085600-RC00_304410412:774:536
Uv@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200402-085600-RC00_304410412:774:753
k.newFile/<@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200402-085600-RC00_304410412:3931:448
Ga@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200402-085600-RC00_304410412:17:336
Ea.prototype.next_@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200402-085600-RC00_304410412:15:474
Ia/this.next@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200402-085600-RC00_304410412:18:206
b@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200402-085600-RC00_304410412:26:268

- Describe the expected behavior:
I was hoping to create a folder inside the "checkpoints" folder.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Firefox

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/github/facebookresearch/music-translation/blob/master/notebooks/Generate.ipynb

**Comment by gorodnitskiy** [comment] 2021-07-10 08:42
Same issue. Solved by factory reset runtime and changing folder name. Checkpoints is damned on colab.

**Comment by cperry-goog** [comment] 2021-07-15 21:26
Duplicate of #621

**Closed by cperry-goog** 2021-07-15 21:26 UTC
