### ISSUE TITLE
I have been having this RAM problem for 48 hours and nobody knows how to give an answer

### ISSUE THREAD

**Issue by sucioyarrastrado** [googlecolab/colabtools#4412] opened 2024-02-29 16:04 UTC
I've been using colab PRO for months, two days ago it won't let me connect because "I reached my daily usage limit" (???), although I finished the units, there is no excuse for not letting me connect anymore, to top it off when it connects without GPU it only gives you 12gb of RAM.

I keep insisting and there is no answer, I paid the subscription less than 10 days ago.

**What web browser you are using**
Chrome

**Additional context**
[https://i.ibb.co/ft55qNL/t.png]

**Comment by colaboratory-team** [comment] 2024-02-29 16:29
Duplicate of #4410.

**Closed by colaboratory-team** 2024-02-29 16:29 UTC
Labels: bug

**Comment by sucioyarrastrado** [comment] 2024-02-29 16:32
> Duplicate of #4410.

and also not solved
