### ISSUE TITLE
After i doing Factory reset runtime, this message was appear for me "Colab is experiencing issues connecting to Drive" How i solve it.

### ISSUE THREAD

**Issue by Ehab-Hegazi** [googlecolab/colabtools#1433] opened 2020-07-23 06:23 UTC
After i doing Factory reset runtime, this message was appear for me "Colab is experiencing issues connecting to Drive" How i solve it.

![Colab](https://user-images.githubusercontent.com/55968266/88257370-1d0f9800-ccf0-11ea-9b2a-e059a67c5391.png)

**Comment by dhaval-zala** [comment] 2020-07-23 06:38
i have same problem. did you solve this?

**Comment by Smankusors** [comment] 2020-07-23 06:38
you can't solve this. Please track on #1428 and wait for Google to fix it.

(in the meantime, don't close this issue so another people don't recreate same issue again and again until this solved)

**Comment by dhaval-zala** [comment] 2020-07-23 06:53
how much time required to fix this problem by google?

**Comment by craigcitro** [comment] 2020-07-23 16:48
Dupe of #1428. (Should now be fixed.)

**Closed by craigcitro** 2020-07-23 16:48 UTC
