### ISSUE TITLE
Google colab is not connecting to Google Drive #URGENT #URGENT #URGENT

### ISSUE THREAD

**Issue by karanaryan07** [googlecolab/colabtools#951] opened 2020-01-17 21:51 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
The Google Drive File Stream is not able to send an authentication code to connect my google drive to my google colab
![Screenshot (58)](https://user-images.githubusercontent.com/43538207/72648487-2ca8cf80-39a1-11ea-8e8d-7e0a93a26566.png)

I am not able to go through this. I am not able to get an authentication code to connect my google drive

- Describe the expected behavior:
Google Drive File Stream should be able to connect with my google drive

- The web browser you are using (Chrome, Firefox, Safari, etc.):
   I am using Firefox
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/10JPsLZy1U4Fh3kbjgAv8D63rjy_Vaqwa?authuser=1#scrollTo=ASZjg_iJcAJJ

**Comment by colaboratory-team** [comment] 2020-01-17 23:16
Duplicate of #947

**Closed by colaboratory-team** 2020-01-17 23:16 UTC
