### ISSUE TITLE
Colab Pro not running .py files

### ISSUE THREAD

**Issue by kamalWam** [googlecolab/colabtools#1426] opened 2020-07-23 01:37 UTC
Scripts were running fine in the free version. As soon as I upgraded to Colab Pro, they no longer work.

!python --version   # works ok
!python example.py  #Does not work. Even when example.py is a simple print statement

I also see:  get_ipython().system = undefined

Any idea? Thanks.

**Comment by kechan** [comment] 2020-07-23 02:51
Did you ever see [Errno 5] Input/output error on accessing your .py file. I have been seeing this starting today, accessing short .py file from a mounted gdrive failed. I think something is wrong and hope they are looking into this.

**Comment by PeiJieSun** [comment] 2020-07-23 03:00
When I open the py file from the mounted drive, I met the following error:
<img width="965" alt="Screen Shot 2020-07-23 at 09 33 19" src="https://user-images.githubusercontent.com/14069445/88248420-bd0af880-ccd3-11ea-915b-9cb2ba1bdd07.png">

**Comment by PeiJieSun** [comment] 2020-07-23 03:01
> When I open the py file from the mounted drive, I met the following error:
> <img alt="Screen Shot 2020-07-23 at 09 33 19" width="965" src="https://user-images.githubusercontent.com/14069445/88248420-bd0af880-ccd3-11ea-915b-9cb2ba1bdd07.png">

I am also the Pro user.

**Comment by PeiJieSun** [comment] 2020-07-23 03:02
When I try to open the .py file from the mounted drive, I met the following error:
<img width="965" alt="Screen Shot 2020-07-23 at 09 33 19" src="https://user-images.githubusercontent.com/14069445/88248493-f17eb480-ccd3-11ea-9d39-118fbc13e74c.png">
I am also the Pro user.

**Comment by kechan** [comment] 2020-07-23 03:06
@PeiJieSun 

Could you also try to tail a file you know should exist after a successful gdrive mount? 

!tail /content/drive/My\ Drive/myfile.txt

I got:

tail: error reading '/content/drive/My Drive/myfile.txt': Input/output error

This I/O error had been reported as an issue with a much longer thread, and that was about gdrive timing out on transferring large files (or a lot of small files). However, I don’t think this is the cause this time. There’s something much general that went wrong today.

**Comment by OrangeCat95** [comment] 2020-07-23 03:20
I am also the Pro user and I found this problem today. After mounting Google drive, I found it's impossible to copy any files from Google drive whatever the file is big or small by using cp command. Hope that there could be a solution!

**Comment by cpboost** [comment] 2020-07-23 03:27
also,pro user open py file error,today

**Comment by PeiJieSun** [comment] 2020-07-23 03:32
> @PeiJieSun
> 
> Could you also try to tail a file you know should exist after a successful gdrive mount?
> 
> !tail /content/drive/My\ Drive/myfile.txt
> 
> I got:
> 
> tail: error reading '/content/drive/My Drive/myfile.txt': Input/output error
> 
> This I/O error had been reported as an issue with a much longer thread, and that was about gdrive timing out on transferring large files (or a lot of small files). However, I don’t think this is the cause this time. There’s something much general that went wrong today.

Yeah, I also got tail: error reading '/content/drive/My Drive/task/train_abae_mtl.py': Input/output error

**Comment by craigcitro** [comment] 2020-07-23 04:59
See #1428.

**Closed by craigcitro** 2020-07-23 04:59 UTC
