### ISSUE TITLE
Dialog window for 'Runtime->Change runtime type' is too small

### ISSUE THREAD

**Issue by meirsolomon** [googlecolab/colabtools#4266] opened 2023-12-28 03:59 UTC
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
Trying to change the runtime type while using colab. 
The dialog window that opens is just too small and it is not possible to see any of the contents.
![change-runtime-type](https://github.com/googlecolab/colabtools/assets/127951809/9161a4f1-1069-4c97-a1dd-677ac4895095)
![change-runtime-type](https://github.com/googlecolab/colabtools/assets/127951809/15c47c1f-6173-4b1f-9542-7a5d80b52c1d)

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
A standard dialog window where one can see the text ...

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by katlyn-edwards** [comment] 2023-12-28 17:44
Hey there!

Can you try this in an incognito window? We've seen reports of this before, but it's been caused by extensions installed.

In [#4018](https://github.com/googlecolab/colabtools/issues/4018) it was caused by a Norton extension, for example.

**Comment by cperry-goog** [comment] 2024-01-04 17:42
Closing as almost certainly a bug caused by extensions. If this reproduces in an incognito window please open a new report.

**Closed by cperry-goog** 2024-01-04 17:42 UTC
Labels: bug

**Comment by ws723514** [comment] 2024-03-06 22:07
What if we want to use the Norton password manager? Is there any way to fix it? I got the same problem today on Chrom.

**Comment by katlyn-edwards** [comment] 2024-11-14 22:46
If you want to use Norton Password manager please reach out on their end -- their extension should not be messing with websites CSS.
