### ISSUE TITLE
Sorry, no backends available. Please try again later.

### ISSUE THREAD

**Issue by hayupadhyaya** [googlecolab/colabtools#1183] opened 2020-04-25 19:01 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I have been disconnected from my session and unable to connect to any sessions. In any cases it says "Sorry, no backends available. Please try again later." It has been more than two hours and I can still not connect to any VMs. I even subscribed to pro and it didn't solve my issue.

- Describe the expected behavior:
I should be able to connect to an instance.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
It happened in safari so I started using Chrome. Nevertheless, same issue.

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by anoukstein** [comment] 2020-05-28 15:50
I am having the same problem with Colab Pro. For several days on multiple notebooks, I'm getting the message 'Sorry, no backends available. Please try again later.'  The runtime type is Standard and there are no active sessions. Please help.

**Comment by koksalkapucuoglu** [comment] 2020-05-30 10:49
I have same issue, how can i solve it.

**Comment by katlyn-edwards** [comment] 2020-05-30 17:55
Duplicate of #1287

**Closed by katlyn-edwards** 2020-05-30 17:55 UTC
