### ISSUE TITLE
Jupyter Magic functions lead to disconnection from runtime 

### ISSUE THREAD

**Issue by Lazy-Propagator** [googlecolab/colabtools#103] opened 2018-03-27 05:47 UTC
While using magic functions like %load and %loadpy, the runtime disconnects after about 15 seconds, I've tried executing them with and without the %, as autoMagic is on, but with no avail. There is a stackoverflow issue as well on this: https://stackoverflow.com/questions/48687091/how-to-edit-and-save-text-files-py-in-google-colab

Anyone facing this issue?

**Comment by colaboratory-team** [comment] 2019-02-19 17:40
Please share a self-contained notebook that reproduces the crash and we'll take a closer look.

**Comment by craigcitro** [comment] 2019-02-19 17:43
This is a dupe of #42 -- closing, but follow that issue for updates.

**Closed by craigcitro** 2019-02-19 17:43 UTC
