### ISSUE TITLE
after updating windows i can not open my colab files

### ISSUE THREAD

**Issue by umairjavaid** [googlecolab/colabtools#1499] opened 2020-08-12 21:59 UTC
getting error 400.
https://colab.research.google.com/drive/1MjBqwKkCGDdmY0UAwb5oG3h8C-CKGHWY?ouid=116469667804339088430
https://colab.research.google.com/drive/1sDGNxxWk5YpWRXu6LMNMELZ8NgTYrxcq?ouid=116469667804339088430
https://colab.research.google.com/drive/1dEV3SSofyYVppDAsy1ICgoOiXpnyHu0X?ouid=116469667804339088430
GETTING THE SAME ERROR 400 on all my files

**Comment by dczechowski** [comment] 2021-04-08 15:15
I have students with this same error.

A work around is to remove the ?ouid=_____________________ from the URL

**Comment by cperry-goog** [comment] 2024-05-09 16:42
Closing due to staleness. File a new bug with reproducible steps if this is an issue.

**Closed by cperry-goog** 2024-05-09 16:42 UTC
