### ISSUE TITLE
Changing the python version.

### ISSUE THREAD

**Issue by adanacademic** [googlecolab/colabtools#1202] opened 2020-05-02 08:36 UTC
I want to work with python 2.7. the google Colab has support for this version, however, I couldn't find the way to change the python version. 

> `import sys`
>  `print(sys.version)`

> 3.6.9 (default, Nov  7 2019, 10:44:02) 
> [GCC 8.3.0]

**Comment by craigcitro** [comment] 2020-05-02 16:27
See #1164 for an explanation and workaround.

Duplicate of #1164

**Closed by craigcitro** 2020-05-02 16:27 UTC
