### ISSUE TITLE
when i do try restored image then in inference became like this. how do i fix this? thank you

### ISSUE THREAD

**Issue by joey4411** [googlecolab/colabtools#4536] opened 2024-04-29 11:35 UTC
when i do try restored image then in inference became like this. how do i fix this? thank you
![Capture](https://github.com/googlecolab/colabtools/assets/167850776/19261bc0-ddb6-4a6e-a9bb-ba2ae6936942)

**Comment by cperry-goog** [comment] 2024-05-02 16:40
We'll need a minimal reproducible notebook to investigate, or contact the original notebook author.

**Comment by cperry-goog** [comment] 2024-05-02 20:55
Okay a bit more info after one of our eng looked (thanks!)

It looks like you're following [this notebook](https://colab.research.google.com/drive/1sVsoBd9AjckIXThgtZhGrHRfFI6UUYOo), but the torchvision api has been deprecated. The correct issue to upvote is here: https://github.com/TencentARC/GFPGAN/issues/539

In the meantime you can clone the repo and change the code as described here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13985#issuecomment-1814870368

As this does not appear to be a Colab issue, I'm closing this.

**Closed by cperry-goog** 2024-05-02 20:55 UTC
Labels: bug, reply-needed

**Comment by shishirahm3d** [comment] 2024-05-16 18:46
@joey4411 run this code on colab before running  3. Inference. it will replace the degradation.py line 8
from torchvision.transforms.functional_tensor import rgb_to_grayscale
to:
from torchvision.transforms.functional import rgb_to_grayscale

then you're good to go...

```
# Define the file path
file_path = '/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py'

# Define the new import statement
new_import_statement = "from torchvision.transforms.functional import rgb_to_grayscale\n"

# Read the content of the file
with open(file_path, 'r') as file:
    lines = file.readlines()

# Modify the desired line (line 8 in this case)
if len(lines) >= 8:
    lines[7] = new_import_statement  # Index 7 corresponds to line 8 (0-based indexing)

# Write the modified content back to the file
with open(file_path, 'w') as file:
    file.writelines(lines)

print("Replacement completed successfully!")
```

**Comment by joey4411** [comment] 2024-05-30 07:40
thanks a lot it fixed now 👍
