### ISSUE TITLE
Stuck when using tf.gfile API

### ISSUE THREAD

**Issue by zlwu** [googlecolab/colabtools#193] opened 2018-06-22 10:58 UTC
Stuck when calling tf.gfile.* API to access GCS public directory.

```python
import tensorflow as tf

print(len(tf.gfile.Glob('gs://images.cocodataset.org/val2017/*.jpg')))
```

**Comment by craigcitro** [comment] 2019-02-04 18:00
See tensorflow/tensorflow#25463: this was reported & marked fixed upstream, but apparently isn't working. I'll take a look.

In the interim, a silly workaround is to authenticate first:

    from google.colab import auth
    auth.authenticate_user()

(This sidesteps waiting for a really long timeout.)

Duplicate of tensorflow/tensorflow#25463

**Closed by craigcitro** 2019-02-04 18:00 UTC
