### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by gdmaru** [googlecolab/colabtools#454] opened 2019-03-01 22:44 UTC
Dear all,

I was trying to download BERT model from googleapis but now it's not working. Please help. Below is my code in Colab.

!wget https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip

--2019-03-01 22:42:06--  https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip
Connecting to 127.0.0.1:11233... failed: Connection refused.

**Comment by craigcitro** [comment] 2019-03-01 22:48
Dupe of #453

**Closed by craigcitro** 2019-03-01 22:49 UTC
