### ISSUE TITLE
shell-init error when current working directory is deleted (cannot change dir unless restarted) 

### ISSUE THREAD

**Issue by gorkemgoknar** [googlecolab/colabtools#1818] opened 2021-01-16 23:26 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
When working directory is deleted via 'rm -r' or 'rmdir'  following error is given when changing to another directory.
You need to restart runtime OR use os to change directory

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
pwd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

```
Replication:
```
!mkdir '/content/somedirectory'
%cd '/content/somedirectory'
!rm -r '/content/somedirectory'
%cd '/content/'
```

- Describe the expected behavior:
Although expected to not get the deleted directory , should be able to navigate to at least root or /content directory
Note that although %cd , !cd do not work you can change directory via python os

Following allows continue without a restart:
```
import os
path = "/content" # /content is pretty much the root. you can choose other path in your colab workspace
os.chdir(path)
```

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

```
!mkdir '/content/somedirectory'
%cd '/content/somedirectory'
!rm -r '/content/somedirectory'
%cd '/content/'
```

**Comment by rajat-tech-002** [comment] 2021-10-09 04:26
@gorkemgoknar any update?

**Comment by craigcitro** [comment] 2021-10-14 21:16
Duplicate of #1366

**Closed by craigcitro** 2021-10-14 21:16 UTC
