### ISSUE TITLE
Unable to download the Diffusers Models

### ISSUE THREAD

**Issue by vedantdere** [googlecolab/colabtools#4272] opened 2024-01-03 13:11 UTC
**Describe the current behavior**
Currently I am not able to download the SDXL models from huggingface 
`base = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16"
).to("cuda")`
Im using the above code.
I have also set the huggingface token in the secrets 

**Describe the expected behavior**
Earlier the models are downloaded very easily. Also I am able to download the models without secrets keys of Huggingface token.

**What web browser you are using**
Chrome

**Additional context**
![image](https://github.com/googlecolab/colabtools/assets/62639479/18bd130c-989c-4326-8df9-6264d85af303)
as we can see from the above image the tqdm progression bar is not moving

**Comment by KevinJBoyer** [comment] 2024-01-03 16:29
Confirming I'm seeing the same behavior, as are several others. You can reproduce it using the Diffusers intro notebook.

The related issue on the `diffusers` GitHub is here: https://github.com/huggingface/diffusers/issues/6431

**Comment by yinglingyang** [comment] 2024-01-04 04:25
Same here. I cannot download SDXL in colab. Someone help!

**Comment by pranauv1** [comment] 2024-01-04 08:28
This might help!
https://github.com/huggingface/diffusers/issues/6446#issuecomment-1876407646

**Comment by cperry-goog** [comment] 2024-01-04 17:51
Thanks for reporting; HuggingFace is working on a fix on their end: https://github.com/huggingface/huggingface_hub/issues/1952

And we're also going to do some work to prevent this from occurring.

**Comment by sandeshrajbhandari** [comment] 2024-01-05 00:03
for the time being, a quick workaround is to use `use_auth_token` paramter in the `.from_pretrained` method. can confirm that this way works, but its a tedious workaround. 
`pipeline = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", use_auth_token="hf_xxxxxxxxxxxxxxxxx")`

**Comment by JhonDan1999** [comment] 2024-01-05 07:46
I think something is changing in the Google Colab environment because the same code was working perfectly fine last week for downloading the stable diffusion XL model. However, now it is stuck at downloading just 19 files, with 0% progress. I tried adding the Hugging Face API key tokens in the Colab settings, but it didn't work!

**Comment by Wauplin** [comment] 2024-01-05 09:38
Thanks everyone for reporting and sorry for the inconvenience. I have been able to reproduce the issue and created a PR (https://github.com/huggingface/huggingface_hub/pull/1953) to fix it. The plan is to make a hot-fix release once it's merged and make it the default in google colab. In the meantime, a temporary solution is to install a different version of `huggingface_hub` before executing any code. More details in https://github.com/huggingface/huggingface_hub/pull/1953#issuecomment-1878364894.

**Comment by EvanWiederspan** [comment] 2024-01-11 17:56
This should now be fixed

**Closed by EvanWiederspan** 2024-01-11 17:56 UTC
Labels: bug

**Comment by Wauplin** [comment] 2024-01-12 08:42
Thanks @EvanWiederspan!
