### ISSUE TITLE
Print to PDF not working anymore

### ISSUE THREAD

**Issue by zhordiffallah** [googlecolab/colabtools#4823] opened 2024-09-04 18:17 UTC
**Describe the current behavior**
When I click File -> print, I can no longer print to PDF the entire colab notebook but instead I am only able to print 1 page (the page I am currently on).

**Describe the expected behavior**
I should be able to print the entire document to a PDF and save it such as.

**What web browser you are using**
Chrome

**Comment by cperry-goog** [comment] 2024-09-05 16:32
Dupe of #4815

**Closed by cperry-goog** 2024-09-05 16:32 UTC
Labels: bug
