### ISSUE TITLE
Does Colab plan to support Python3.8 going forward. 

### ISSUE THREAD

**Issue by stewartmandell** [googlecolab/colabtools#1852] opened 2021-02-08 19:43 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment] 2021-02-08 22:44
Duplicate of #1422

**Comment by craigcitro** [comment] 2021-02-23 22:01
I forgot to close this -- we've finally updated to 3.7, and we don't intend to stop there, but no specific timeframe I'm comfortable committing to. :)

**Closed by craigcitro** 2021-02-23 22:01 UTC
