### ISSUE TITLE
Keras training progress bar issue

### ISSUE THREAD

**Issue by draconus21** [googlecolab/colabtools#201] opened 2018-07-06 16:07 UTC
For every other epoch the keras progress bar has incorrect formatting.
See attached image for details
![colab-keras-bug](https://user-images.githubusercontent.com/6926094/42388963-34dff7c8-8115-11e8-9d21-e66e1d9b2623.png)

**Comment by colaboratory-team** [comment] 2019-03-26 16:38
Can you share a self-contained notebook that reproduces this issue?

**Comment by colaboratory-team** [comment] 2019-03-26 16:44
Duplicate of #209

**Closed by colaboratory-team** 2019-03-26 16:44 UTC
