### ISSUE TITLE
Entering '^' or '`' into a code cell produces graphical glitch.

### ISSUE THREAD

**Issue by tobias-wilfert** [googlecolab/colabtools#3665] opened 2023-05-11 12:07 UTC
**Describe the current behavior**
When entering the '^' character into a code cell a graphical glitch appears (see video below). ***Note*** the same behaviour appears when entering the '`' character so it seems to be related to these kind of characters.

https://github.com/googlecolab/colabtools/assets/36408720/7064a0dc-014c-4b09-990a-d5e95c7f3be4

**Describe the expected behavior**
Ideally there should not be any graphical glitches that appear after entering a character.

**What web browser you are using**
Chrome

**Additional context**
Happens in any Repository for me.

**Comment by EvanWiederspan** [comment] 2023-05-11 16:41
I'm having trouble reproducing, can you share the notebook you were using? Also, does this still happen for you in incognito mode with extensions disabled?

**Comment by LilyShevchenko** [comment] 2023-05-15 16:05
Having exactly the same problem, in any notebook for the last several days but _only when the notebook has been alrealy in use for about 30-40 minutes_. Reloading and closing the page does not solve the problem, the runtime does not have to be connected. The problem persists in Firefox troubleshooting mode and in Safari (no extensions enabled). The issue appeared simultaneously with #3676 and exhibits identical pattern.

**Comment by cperry-goog** [comment] 2023-05-18 16:46
If you can figure out what triggers this, that would be absolutely amazing. Trying to repro on our side.

**Comment by ragman-google** [comment] 2023-05-18 16:47
Being tracked internally as b/283265789.

**Comment by ragman-google** [comment] 2023-05-19 16:41
Hi Tobias, thanks for the video, that's very helpful.

One quick question: Are you by chance using a non-US/non-English keyboard setting? 

This appears to be a different manifestation of https://github.com/googlecolab/colabtools/issues/3660, trying to track down exactly what set of unicode is triggering it.

Thanks!

**Comment by tobias-wilfert** [comment] 2023-05-19 17:19
Yeah I am using French Keyboard (AZERTY) on Mac.

**Comment by tobias-wilfert** [comment] 2023-05-19 17:28
Yeah https://github.com/googlecolab/colabtools/issues/3660 indeed seems to be the same problem, seem to be caused by any key that combines with other input to form a new character (i.e ^ + a -> â & ` + a -> à)?

**Comment by ragman-google** [comment] 2023-05-19 17:31
I was able to reproduce both of your videos with the AZERTY keyboard. I think you're exactly right -- it's "insertCompositionText" input events that are triggering the glitch.

Still working on finding the root cause in our code that is causing this, hopefully I'll have some updates later today!

Thank you Tobias for the help debugging :)

**Comment by ragman-google** [comment] 2023-05-19 23:42
Close to a fix, but still working on it.  I'll update this issue when the fix is live. Thank you all for your patience, and I apologize for the inconvenience.

**Comment by LilyShevchenko** [comment] 2023-05-20 17:21
Hi and sorry for a late response. Yes, I think you are correct - my device keyboard is also non-US, but on-screen English keyboard also generates the same problem, as long as there are input modifying keys. Not sure why my glitch was with a delay, probably just missed something. 

The only think I have noticed in the debugger is that when text area changes class to ime-input, the line wrap switches off, hope this helps.
![image](https://github.com/googlecolab/colabtools/assets/43030071/4e4a1b2c-054b-42e2-9dd5-4fdea5585dea)

**Closed** 2023-05-25 17:03 UTC
Labels: bug, reply-needed
