### ISSUE TITLE
File browser Disappears and dsnt comes back

### ISSUE THREAD

**Issue by jaideep11061982** [googlecolab/colabtools#2052] opened 2021-05-27 15:44 UTC
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
Connecting to a runtime to enable file browsing.
When kernel is running suddenly this message will come and one cant see file browser back like it was earlier  till kernel finishes.
This was neven an issue before. 
I cant save my best weights  till kernel is runnning in
**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
one should always see file browser  file kernel is running in.
**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by craigcitro** [comment] 2021-05-27 19:50
Looks like a duplicate of #2040; let's consolidate conversation there.

**Closed by craigcitro** 2021-05-27 19:50 UTC
Labels: bug
