### ISSUE TITLE
Unable to mount Google Drive

### ISSUE THREAD

**Issue by joyjitchatterjee** [googlecolab/colabtools#704] opened 2019-08-19 19:02 UTC
- Describe the current behavior:
I am unable to mount Google Drive to my Colab Notebook. Earlier, it was working just fine. But now, I get the prompt for the authorisation key with the link, and when I go to link it follows onto Google Drive File Stream, and clicking on next gives "Something went wrong Sorry, something went wrong there. Please try again."
- Describe the expected behavior:
It should give me the Authorisation Code to enter into Colab. I am unable to receive the authorisation code, without which I cannot access files on Colab.
- The web browser you are using (Chrome, Firefox, Safari, etc.):
I have tried on Chrome and Safari. Getting the same error.

**Comment by craigcitro** [comment] 2019-08-19 19:05
This is a service outage.

Duplicate of #703

**Comment by joyjitchatterjee** [comment] 2019-08-19 19:05
![Screenshot 2019-08-19 at 8 03 44 PM](https://user-images.githubusercontent.com/18656061/63292006-a63a7580-c2bc-11e9-8a2e-709fab8882f7.png)
![Screenshot 2019-08-19 at 8 04 40 PM](https://user-images.githubusercontent.com/18656061/63292019-aaff2980-c2bc-11e9-92bb-2b48e19926de.png)

**Closed by craigcitro** 2019-08-19 19:05 UTC
