### ISSUE TITLE
Arrow keys on iPad Pro not working

### ISSUE THREAD

**Issue by wezleysherman** [googlecolab/colabtools#493] opened 2019-03-23 07:18 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
When I'm in a code cell I can't use the arrow keys on my iPad Pro's keyboard. This is due to the keyboard utilizing a different set of key codes than normal keyboards (thanks Apple).

- Describe the expected behavior:
For the arrow keys on the iPad Pro keyboard to work normally.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Safari

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by colaboratory-team** [comment] 2019-03-23 15:50
Duplicate of #113

**Closed by colaboratory-team** 2019-03-23 15:50 UTC

**Comment by lizhicq** [comment] 2019-03-26 17:25
any fix so far?

**Comment by wezleysherman** [comment] 2019-03-26 17:46
Nope. 

It’s a really simple fix on the developer side. You just have to add a case for the keycodes.

**Comment by lizhicq** [comment] 2019-04-03 17:50
Reasonable, but could not bring it to star buck any more.
