### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by salmannauman6** [googlecolab/colabtools#510] opened 2019-04-15 07:42 UTC
Bug report for Colab: http://colab.research.google.com/.

- Basically, I am getting OSError: [Errno 5] Input/output error when trying to read a large (6GB) CSV file which is placed on my google drive. This was working fine earlier. I was able to read the data, but then all of a sudden, the same thing has stopped working. This is completely random and the root cause is not understandable. I am working on google chrome browser.

**Comment by colaboratory-team** [comment] 2019-04-16 00:06
Does https://research.google.com/colaboratory/faq.html#drive-timeout help?

**Comment by salmannauman6** [comment] 2019-04-16 06:00
No, it does not. I have just one folder in my root folder which contains this one CSV file I am reading.

**Comment by colaboratory-team** [comment] 2019-04-16 06:14
Thanks for confirming.
Can you share a minimal self-contained repro notebook, either publicly or just with colaboratory-team@google.com ?
(it would be helpful to see precisely how you're reading the data)

Does the problem go away if you first 
`!cp path/to/data.csv local.csv`
and then read from the local path?

**Comment by ShHsLin** [comment] 2019-04-22 20:40
Similar issue here. 
Get
`gzip: stdin: Input/output error`
`tar: Child returned status 1`
`tar: Error is not recoverable: exiting now`

when doing,
``
!tar -zxvf /content/gdrive/My\ Drive/data.tgz -C ./ > /dev/null
``

**Comment by Syzygy2048** [comment] 2019-04-25 15:44
I've no issue accessing 20 GB files.

What causes this issue for me is when there are many files in the folder (or parent folders) I'm accessing.
Instead of having path/to/data/data_x_of_1000files_in_folder.csv, I transformed the file structure to path/to/data/20folders/data_x_of_50files_in_folder.csv

**Try making sure that there are no more than 50 files in the folder the file is in, or in any of the parent folders.**

When I was only accessing a single file, or accessing files sequentially, I could also just try to load the file again, that worked because the context has been loaded already. This didn't work for random access.

Works for me, hope this helps you too.

**Comment by sgabor1** [comment] 2019-05-01 00:09
Things were working without a problem until today, now the untar won't finish anymore with a large file:
`tar: /content/gdrive/My Drive/bigfile.tar: Cannot read: Operation not permitted`
`tar: /content/gdrive/My Drive/bigfile.tar: Cannot read: Input/output error`
`tar: Too many errors, quitting`
`tar: Error is not recoverable: exiting now`
It could successfully untar all the files (31GB tar with 10000 files) even yesterday multiple times..
The command I'm using:
`!tar -C features -xf /content/gdrive/My Drive/bigfile.tar`

**Comment by furkanyildiz** [comment] 2019-05-20 00:54
I have same problem. I can not read my files on drive. It's sometimes working but mostly giving OSError


```
OSError: Can't read data (file read failed: time = Mon May 20 00:34:07 2019
, filename = '/content/drive/My Drive/train/trainX_file1', file descriptor = 83, errno = 5, error message = 'Input/output error', buf = 0xc71d3864, total read size = 42145, bytes this sub-read = 42145, bytes actually read = 18446744073709551615, offset = 119840768)
```


Also creating file giving the OSError.

`OSError: Unable to create file (unable to open file: name = '/content/drive/My Drive/train/model.hdf5', errno = 5, error message = 'Input/output error', flags = 13, o_flags = 242)`

"https://research.google.com/colaboratory/faq.html#drive-timeout" does not helped me.

**Comment by kallianisawesome** [comment] 2019-05-20 21:48
I have same problem too. I can't load my data which is not very large, I can load it with num_workers = 1(use PyTorch Dataloader method), but I can't get my files. The number of my files is about 40000.  I have tried io.imread or cv2.imread, they are all work fine in my own computer, and I am sure that my files are in right place. I can't figure it out for days, I guess it' not my problem. I will try to get image matrix in my own computer and upload by csv format. If this work out, I will feedback.

**Comment by colaboratory-team** [comment] 2019-05-21 16:25
Duplicate of #559

**Closed by colaboratory-team** 2019-05-21 16:25 UTC

**Comment by yuuSiVo** [comment] 2019-06-11 03:59
I have same issue too. Today, I made voice conversion program in Google Colaboratory. Yesterday it was works. But, today not working since this morning in Japan

**Comment by abiantorres** [comment] 2019-06-22 02:00
I have the same issue. I can't access to a hdf5 file of 42 GB. At some point of my processing pipe comes an OSError, as @furkanyildiz commented. I access each element sequentially and then stored it instantaneously in another .tfrecords file.

**Comment by glenn-jocher** [comment] 2019-06-29 10:28
I have the same problem. **This issue should not be closed.** When copying a 20GB file from a mounted Google Drive folder:

```bash
!cp -r 'drive/My Drive/cloud/data/coco_colab2.zip' . && unzip -q coco_colab2.zip
cp: error reading 'drive/My Drive/cloud/data/coco_colab3.zip': Input/output error
```

**Comment by gilgarad** [comment] 2019-07-30 03:04
Have same problem. 
I thought the file was corrupted first time, and I downloaded and opened on my local computer it was working fine. Then I uploaded to my brother's account and it was working as well. It is not the problem with the file. I can load other files except that csv file.

**Comment by AlanCh3n** [comment] 2019-11-01 08:34
Same problem. Working perfectly and then suddenly stops with no changes implemented.

**Comment by invincible-akshay** [comment] 2019-11-02 20:46
> Thanks for confirming.
> Can you share a minimal self-contained repro notebook, either publicly or just with [colaboratory-team@google.com](mailto:colaboratory-team@google.com) ?
> (it would be helpful to see precisely how you're reading the data)
> 
> Does the problem go away if you first
> `!cp path/to/data.csv local.csv`
> and then read from the local path?

I tried this and getting 
`cp: error reading '/content/drive/My Drive/DSF/file_name.csv': Input/output error`

**Comment by deqncho2** [comment] 2019-11-11 02:54
Same problem here as well, reopen the issue.

**Comment by invincible-akshay** [comment] 2019-11-11 03:03
I made an observation but not tested it. It seems that large files on Google Drive have some daily download limits. Could it be that trying to read from Colab is also counted as a download? If yes, then that explains why it suddenly stops working.

**Comment by deqncho2** [comment] 2019-11-11 03:09
I have no issue downloading to a local machine.

**Comment by glenn-jocher** [comment] 2019-11-11 03:40
Same problem. I can download to a local machine fine. Downloading to Colab from Google Drive is a nightmare, it takes 5 or 6 tries before it completes successfully.

**Comment by deqncho2** [comment] 2019-11-11 03:58
I think it's a quota problem actually. I can't actually download to a local machine.

**Comment by invincible-akshay** [comment] 2019-11-11 05:06
@deqncho2 you can test by creating a copy of the file in your Drive and trying to read the new file. 
That had worked for me hence I had not investigated further but came across this later - https://support.google.com/drive/thread/2035857?hl=en

**Comment by MittalShruti** [comment] 2019-11-22 03:43
Same issue. Trying to read a folder with >40k files from gdrive to colab

**Comment by invincible-akshay** [comment] 2019-11-22 04:05
@MittalShruti , maybe you could try this- https://github.com/googlecolab/colabtools/issues/510#issuecomment-552294940 ?

Or check this thread for details: https://support.google.com/drive/thread/2035857?hl=en

**Comment by prashants975** [comment] 2019-12-08 19:12
similar issue, reading the csv file through pandas was working fine and suddenly later that day I can't get it into the RAM.
First I got this error , ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'. 
then after using engine='python' I got this:-
OSError: [Errno 5] Input/output error

**Comment by rajubjc** [comment] 2019-12-09 08:19
> Thanks for confirming.
> Can you share a minimal self-contained repro notebook, either publicly or just with [colaboratory-team@google.com](mailto:colaboratory-team@google.com) ?
> (it would be helpful to see precisely how you're reading the data)
> 
> Does the problem go away if you first
> `!cp path/to/data.csv local.csv`
> and then read from the local path?

No, It didn't work.

**Comment by talhaanwarch** [comment] 2019-12-27 07:31
any one got the solution?

**Comment by peterpalos** [comment] 2020-01-03 23:48
Same problem in colab reading from gdrive >100k file

**Comment by talhaanwarch** [comment] 2020-01-04 10:05
i noticed that there is some sort of limitation by google. if we access data multiple time from drive, this issue occurs. take a break of 24 hours, and this issue has gone

**Comment by Nandutu** [comment] 2020-01-20 19:55
I am facing the same issue here. Any solution?

**Comment by prbsh9** [comment] 2020-01-28 05:02
Same issue.. I have 4 npy file... 2 files around 10GB and 2 around 6GB..
.
`ss = np.load('train_abnormal.npy')`
Also,.. I cant open any of those 4 files. 
Files with lesser size can be opened though.

**Comment by JonathanSum** [comment] 2020-02-14 07:17
I have the same problem too, so I am sure this will affect colab pro too.

**Comment by cpietsch** [comment] 2020-02-14 20:13
I have the same issue when copying a folder of images (around 2000 jpgs)

**Comment by cpietsch** [comment] 2020-02-14 20:33
Found a fix for the error when copying a lot of files. Use:
`%cp -av fromfolder tofolder`
Works for me

**Comment by kechan** [comment] 2020-02-23 19:50
It just happened to me, apparently after doing various file operations (cp, tar, etc) leading to I/O between my gdrive and local colab VM. After this, i got random python OSError and Input/Output error, sometimes even at importing a python module. At another times, my colab notebook just entirely crashed (during a read feather of >1G) and log showed nothing meaningful. 

I hope this is just the case of a gdrive daily quota issue as someone mentioned. Has anyone confirm this? I will wait for a day to pass and re-try.

**Comment by mujtabaxd** [comment] 2020-02-29 15:46
Today it happened to me as well, when trying to unrar 30gb file in colab. I'm getting input/output error. Read error in the file

**Comment by chyan0411** [comment] 2020-03-20 09:11
I also got the same error:  'OSError: [Errno 5] Input/output error' when I was trying to import a 14G-large file from gdrive.  This error occurred so suddenly, cuz like several minutes ago I did the same operation and everything was alright.   When I tried importing a much smaller file from the same folder, it worked normally. It seems like colab has some limits for importing large files ???
Why this issue closed???
btw, I have subscribed colab pro!!!! 

> Duplicate of #559

**Comment by sowmen** [comment] 2020-03-29 05:22
I am also getting the Input/Output error. I downloaded a dataset from kaggle into my drive. It has 50 zip files each having 2000 images. I successfully extracted 2 zip files but then the error started. Any solutions to this?

**Comment by dipam7** [comment] 2020-04-01 19:59
Same error, I am trying to load 194082 image files from the drive. It worked once, the first time that I extracted the data and tried to load it. It hasn't worked ever since. Even after I updated to colab pro it doesn't work. Frustrating.

**Comment by dreamerriver** [comment] 2020-04-08 05:15
same as well,how can I deal with it?

**Comment by shadabtughlaq** [comment] 2020-04-09 12:45
Got the same error 
```
Could not read file
Errno 5] Input/output error: .........
```

Was working fine until some time back.
Had loaded files from a mounted drive

**Comment by gaceladri** [comment] 2020-04-10 15:00
Same error here trying to load a pretrained model from google drive. First I mount the drive disk on colab and then when I try to load the checkpoint, it fails giving me this error. Yesterday was no issue loading it.

**Comment by kechan** [comment] 2020-04-11 23:19
For anyone having this problem with colab + gdrive, the mostly cause is excessive I/O due to large files, or merely "ls -l" on a folder with too many files. The latter case is more harmless (as long as you don't do that again, I find using glob much better behaved). But the former case, you need to do this. The former case you most likely violate some google quota. In my experience, it is either large size (or extremely large # of small files such that the total is big) or, throughput (i.e. size/time).

The limit for me for a single file seemed to be around 10gb. Mileage seemed to vary. So don't copy file from gdrive <---> colab. Note, it counts as "upload" if you access gdrive file in colab via a Mount

Best solution is to use linux "split" to split your huge files into 500m-1g, and then upload it one by one to gdrive. When you need it in colab, then copy the fragment onto your colab's VM local disk, and then perform a "cat .....". This way, no giant file is ever moved from gdrive. The downside is you have to repeat for every new colab session.

It is a pain, but this whole thing isn't designed for huge scale dataset. Note if you violated and hit I/O Error, you have to wait for 1 day for this to go away. I would try not to do anything at all to your gdrive for at least 24 hrs for this to recover.

Hope this helps.

**Comment by gaceladri** [comment] 2020-04-12 16:55
@kechan The answer would be perfect if you could provide an example of how to do this split with the command line. Thanks anyway for your answer.

**Comment by homerdiaz** [comment] 2020-04-18 01:43
I have the same problem too.
OSError: [Errno 5] Input/output error: '/content/drive/My Drive/COVID-Net/rsna-pneumonia-detection-challenge/stage_2_train_images/003d8fa0-6bf1-40ed-b54c-ac657f8495c5.dcm'

Will i get the same error with Colab Pro?

**Comment by dipam7** [comment] 2020-04-18 05:45
I tried using Colab pro and the error does not go. I then segregated my data from all the images in one folder to 50 images per folder. Now it runs however it does not return all the image files. Only 165034 out of 194082. Maybe I need to keep even lesser images per folder. However, this is really frustrating. I like paperspace better now.

**Comment by salmanhiro** [comment] 2020-04-24 20:59
Same issue here, It works yesterday, but not now. With the same code. How could?

**Comment by Zappytoes** [comment] 2020-04-27 14:21
This an unacceptable flaw in Colab and in my view, completely delegitimizes it as a platform for Machine learning. The ability of a computing platform to handle large amounts of data is absolutely essential in this field, and I think it's just plain crooked of Google to tell people they have a product that is designed for deep learning and ML. I paid for a Pro account and have tried every work around and "OSError: [Errno 5] Input/output error" will always show up again eventually and stop you dead in your tracks.  This is not just a "bug", this is the reason you should not use Colab if you have other options.

**Comment by dipam7** [comment] 2020-04-27 15:18
I feel the same. Even after Colab pro, I had to split my data into various folders and it would partially work. I was so frustrated because I couldn't focus on the project. All my time went in trying to make Colab work.

**Comment by gaceladri** [comment] 2020-04-27 15:40
It's free mate. Take a breath.

**Comment by kechan** [comment] 2020-04-27 16:34
@Zappytoes That error is highly likely to do with google drive quota limit than Colab. I have used for Colab for almost 2 years and I found it an excellent platform to experiment with DL on smaller dataset (by modern standard). You are right you shouldn't use Colab if you have other options (i.e. lot of $$). If you work on >10g or more routinely, you should use GCP or AWS and pay the fair price. Pro is only $10? It is the best deal around for the sort of GPU and TPU you get.

**Comment by kechan** [comment] 2020-04-27 16:40
> @kechan The answer would be perfect if you could provide an example of how to do this split with the command line. Thanks anyway for your answer.

Use Linux "split" to shard a huge file is an old trick you can google around and read far better than i can explain it. Shipping around big file has been an issue since the internet is here. It is only what you mean by "big" that has changed.

**Comment by Zappytoes** [comment] 2020-04-27 19:15
@kechan I agree with all that, but I would like Google to be more upfront about these limitations so users can better monitor their usage or pick the right platform for their task before investing lots of time into Colab/ Drive as a computing environment. I admit I probably would't even be using it if it weren't for needing to find work-at-home solutions given the state of things.  I will probably take your advice and look into GCP. Thanks!

**Comment by Zappytoes** [comment] 2020-04-27 20:02
> It's free mate. Take a breath.

"Colab Pro", but for the price I guess I'll need to accept this limitation.

**Comment by GadirajuSanjayvarma** [comment] 2020-05-09 11:37
I bypassed it by following steps
1)first make a copy of that file in drive
2)mount your drive to google colab
3)drag it to google colab local directory
4)restore it to your drive by going to trash
5)if you have any doubts plz comment below

**Comment by me10b031** [comment] 2020-05-13 19:05
> I bypassed it by following steps
> 1)first make a copy of that file in drive
> 2)mount your drive to google colab
> 3)drag it to google colab local directory
> 4)restore it to your drive by going to trash
> 5)if you have any doubts plz comment below

Hi, restore part I'm still a bit confused

**Comment by GadirajuSanjayvarma** [comment] 2020-05-13 23:57
@me10b031 
If you file is belo 7 gb then it works but i didnt try it more than that size.
create a folder in google colab
mount drive
drag and drop the file into the google colab folder(local folder)
now disconnect wifi
after 5 minutes colab automatically disconnects
now turn on wifi again and try to conect to colab without any restart runtime.Just click connect.
now the file will be there in that folder.

**Comment by GadirajuSanjayvarma** [comment] 2020-05-13 23:58
after connecting to runtime.

**Comment by Zappytoes** [comment] 2020-05-14 14:38
The best, but non-free, solution to this issue is to host your data on a cloud bucket, such as a Google Cloud Platform (GCP) bucket. It's free to set up, but charges you as you go. I've been training with ~13Gb of imagery data almost non-stop for 14 days and its cost me about $7 so far. 

**1) Create a Google Cloud Storage project. Go to the Resource Manager and create a new project.** https://console.cloud.google.com/cloud-resource-manager

<img width="704" alt="Screen Shot 2020-05-14 at 10 10 32 AM" src="https://user-images.githubusercontent.com/18469106/81944757-32b76180-95cb-11ea-905f-451c4b01377d.png">

**2) Enable billing for the project:** https://cloud.google.com/billing/docs/how-to/modify-project

**3) After the project is created (and you need to have billing enabled, as the storage will cost you a few cents per month) click on the menu in the upper right corner and select Storage (somewhere way down the menu). Next you need to create a bucket for the data (The name of the bucket must be globally unique, not only for your account but for all accounts).**

<img width="1650" alt="Screen Shot 2020-05-14 at 10 15 25 AM" src="https://user-images.githubusercontent.com/18469106/81945538-3d262b00-95cc-11ea-8e29-41fe806eb145.png">

**4) Once your bucket is set up, you can connect Colab to GCS using Google Auth API and gcfuse.**

**## Authenticate ##**

from google.colab import auth
auth.authenticate_user()

**## Use this to install gcsfuse on colab. Cloud Storage FUSE is an open source FUSE adapter that allows you to mount Cloud Storage buckets as file systems on Colab, Linux or macOS systems. ####**

!echo "deb http://packages.cloud.google.com/apt gcsfuse-bionic main" > /etc/apt/sources.list.d/gcsfuse.list
!curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
!apt -qq update
!apt -qq install gcsfuse

**## Make a directory name for your bucket in Colab and mount the bucket at that directory in Colab ##**

!mkdir name_of_bucket_on_Colab
!gcsfuse --implicit-dirs name_of_bucket_on_GCP name_of_bucket_on_Colab

**5) You can continue to also have other storage mounted, such as your Google Drive**
from google.colab import drive
drive.mount('/content/drive')

**Further reading:**

https://medium.com/@philipplies/transferring-data-from-google-drive-to-google-cloud-storage-using-google-colab-96e088a8c041

https://gist.github.com/korakot/f3600576720206363c734eca5f302e38

https://cloud.google.com/storage/docs/gcs-fuse

https://stackoverflow.com/questions/51715268/how-to-import-data-from-google-cloud-storage-to-google-colab

https://stackoverflow.com/questions/61600439/how-to-mount-gcp-bucket-in-google-colab/61615097#61615097

**Comment by shwetaketu** [comment] 2020-05-31 13:44
having same issue while reading a file by line by line  from google drive.
Seems like it just times out after reading certain records 
 20 
     21                 a=line.rstrip().split(" ")[1:]

OSError: [Errno 125] Operation canceled

**Comment by skag1nnya86** [comment] 2020-06-01 04:53
> @me10b031
> If you file is belo 7 gb then it works but i didnt try it more than that size.
> create a folder in google colab
> mount drive
> drag and drop the file into the google colab folder(local folder)
> now disconnect wifi
> after 5 minutes colab automatically disconnects
> now turn on wifi again and try to conect to colab without any restart runtime.Just click connect.
> now the file will be there in that folder.

How can I drag and drop a file from _google drive_ to _google colab local folder_?
_google colab local folders_ aren't viewable at all in the _google drive_ user interface.
Could you please explain more this step?

**Comment by dimitry-ishenko** [comment] 2020-06-01 21:47
Another work-around using wget:

    FILEID="<your-gdrive-file-id>"
    FILENAME="/path/to/saved/file"
    !wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id={FILEID}' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id={FILEID}" -O {FILENAME} && rm -rf /tmp/cookies.txt

Found it [here](https://medium.com/@acpanjan/download-google-drive-files-using-wget-3c2c025a8b99).

**Comment by shwetaketu** [comment] 2020-06-02 02:53
Thanks, will try this if have the issue again. It automatically got
resolved yesterday.

**Comment by SonOfAntonv0** [comment] 2020-07-03 14:35
> Thanks for confirming.
> Can you share a minimal self-contained repro notebook, either publicly or just with [colaboratory-team@google.com](mailto:colaboratory-team@google.com) ?
> (it would be helpful to see precisely how you're reading the data)
> 
> Does the problem go away if you first
> `!cp path/to/data.csv local.csv`
> and then read from the local path?

I am facing a similar issue but my file size is ~37.5 GB. I have saved it in a subfolder. 
![image](https://user-images.githubusercontent.com/30777433/86478711-5778bb80-bd68-11ea-9f5a-c97b0adbf072.png)
The !cp approach won't work as the internal storage quota whilst using GPU is 37 GB. Any work around?

**Comment by GusSand** [comment] 2020-07-22 16:26
This issue shouldn't be closed. I got it today with a 600MB file.  It was working and then it was not. Can you please investigate? Thanks!

**Comment by nickagee** [comment] 2020-07-22 17:06
I just received the same error for a 2KB python file when trying to run 
`!cp "/content/drive/My Drive/DL_Class/face-generation/data/processed-celeba-small.zip" /content/`

**Comment by raghada** [comment] 2020-07-22 19:31
I got this error today with a 1GB file. I'm using Colab Pro as well. This is super frustrating.

**Comment by CpSquared** [comment] 2020-07-22 19:46
I literally got this error hour ago and was very frustrated bcoz the exact cell block was working fine earlier. I got this error with mere  files no more than 1 GB. Wow, the number of people getting this error does comfort my frustration a little bit, but again plz fix this issue asap. Such a major issue, how to get around it? Do I just have to wait until that G drive Quota expires

**Comment by GusSand** [comment] 2020-07-22 19:59
I'm also a Colab Pro user and this was literally working yesterday. 
Now I changed my code to use wget from this article to make it work. 

https://medium.com/@acpanjan/download-google-drive-files-using-wget-3c2c025a8b99

**Comment by CpSquared** [comment] 2020-07-22 20:23
> I'm also a Colab Pro user and this was literally working yesterday.
> Now I changed my code to use wget from this article to make it work.
> 
> https://medium.com/@acpanjan/download-google-drive-files-using-wget-3c2c025a8b99
Can you please tell me how to access the file once it is downloaded on colab,

**Comment by raghada** [comment] 2020-07-22 20:28
I'm wondering why did they close the issue if it isn't solved!

**Comment by DJW41023** [comment] 2020-07-22 21:19
Within Google Drive, navigate to "Trash", hit the dropdown and "Empty Trash". 

Remount drive, and you have no further issues.

**Comment by raghada** [comment] 2020-07-22 23:07
> Within Google Drive, navigate to "Trash", hit the dropdown and "Empty Trash".
> 
> Remount drive, and you have no further issues.

This didn't help, unfortunately.

**Comment by christincha** [comment] 2020-07-22 23:47
> Within Google Drive, navigate to "Trash", hit the dropdown and "Empty Trash".
> 
> Remount drive, and you have no further issues.

This actually for me. I was importing the python file when it comes Input/Output Error.

**Comment by xaerincl** [comment] 2020-07-23 01:36
Im getting the same error trying to   !cp /mydrive/x/something.zip ../    Input/output error

**Comment by dinhngoc267** [comment] 2020-07-23 02:10
Same error. What's wrong with Colab today

**Comment by kevin-yauris** [comment] 2020-07-23 02:32
Hello, I got this issue as well. I tried several solutions but the issue still persists. Now I think the way to do it is by download the files and then upload to session storage, but it takes too long.

**Comment by xaerincl** [comment] 2020-07-23 02:37
> Hello, I got this issue as well. I tried several solutions but the issue still persists. Now I think the way to do it is by download the files and then upload to session storage, but it takes too long.

I tried that and it takes way too long even for files like 500 mb. Not only that, since it takes too long sometimes i get kicked out of colab

**Comment by xusky69** [comment] 2020-07-23 02:40
Having the same problem rn

**Comment by kechan** [comment] 2020-07-23 02:48
This input/output error started happening to me even access directories with few files. In fact, it was just some python script I am trying to import through sys.path.insert(...) I think there’s something wrong with Colab today in mounting gdrive.

**Comment by Entongsu** [comment] 2020-07-23 03:00
I  encoutered with the same problem today when using Colab pro.

**Comment by ktingyew** [comment] 2020-07-23 03:05
Same, encountered the same issue

**Comment by kechan** [comment] 2020-07-23 03:09
I suspect there’s a general “outage” going on concerning reading from gdrive after a mount from a Colab VM. This may also be the root cause on a new issue reported on github (But with no explicit I/O error, but symptoms the same, inability to read any python module files hosted on gdrive). I sent a tweet to Colab and hopefully they can take a look at it.

**Comment by Smankusors** [comment] 2020-07-23 04:31
if anyone wondering why this closed, this issue is tagged as duplicate of #559. If you have same issue, please go to that open issue instead of this.

**Comment by DJW41023** [comment] 2020-07-23 05:02
Now displayed by the google team: 'Colab is experiencing issues connecting to Drive, and we are actively investigating.'

**Comment by szl0144** [comment] 2020-07-23 05:18
I can run my code normally in the afternoon, but I can't run it now and the window shows the error.

**Comment by Modulariti** [comment] 2020-07-23 05:42
I run into the same problem, simply copying small text file does not work:

%cp "drive/My Drive/Download/test.txt" .

cp: error reading 'drive/My Drive/Download/test.txt': Input/output error

**Comment by sharysky** [comment] 2020-07-23 06:02
Same problem here as well, reopen the issue.

**Comment by becks-ddf** [comment] 2020-07-23 06:33
Trying to load json file in colab from gdrive  and get the same error.

**Comment by Smankusors** [comment] 2020-07-23 06:34
> if anyone wondering why this closed, this issue is tagged as duplicate of #559. If you have same issue, please go to that open issue instead of this.
> 
> edit: for the current outage issue, please go to #1428 instead

let me repeat this

please all go to #1428 instead continuing this issue.

**Comment by vogelPaul** [comment] 2020-07-23 06:49
it seems that google collab has a problem today. I was working right well with my files from the my driver, but suddenly it stopped and started to give Error: OSError: [Errno 5] Input/output error.

**Comment by msdey** [comment] 2020-07-23 07:08
I am facing the same problem since yesterday. This issue should be reopened.

**Comment by GeorgeLiang3** [comment] 2020-07-23 09:29
same problem here

**Comment by coelhogonzalo** [comment] 2020-07-23 17:01
I have the same problem when reading a csv file. It happened to a friend too. Our respective codes were executing normally a couple of days ago and now they aren't. I highly doubt we messed up. I am really disappointed considering that I am paying for Colab PRO.

**Comment by rchurt** [comment] 2020-07-23 23:50
This issue has been reported here https://github.com/googlecolab/colabtools/issues/1428

**Comment by maximmasterr** [comment] 2020-07-24 08:08
Have same problem now, only on GPU instances

**Comment by seanggggggg** [comment] 2020-07-30 03:23
Encountered the same problem again today, the code works perfectly in the morning.

Anyone got the same problem today as me?


<decorator-gen-60> in time(self, line, cell, local_ns)

<timed exec> in <module>()

/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py in _next_iter_line(self, row_num)
   2889 
   2890         try:
-> 2891             return next(self.data)
   2892         except csv.Error as e:
   2893             if self.warn_bad_lines or self.error_bad_lines:

OSError: [Errno 5] Input/output error

**Comment by raynt** [comment] 2020-08-03 04:14
I am an occasional Colab Pro/Drive (paid subscription) user, maybe using a 2-3 times a month. I have this problem about half the time over the last few months. I'll come back later and run the same code and it will work fine...

**Comment by danjohnvelasco** [comment] 2020-08-12 04:00
I encountered this issue as well. I'm trying to load ~14gb images from google drive. It was working fine yesterday.

**Comment by t0efL** [comment] 2020-08-28 06:56
It's still broken even with pro version

**Comment by renukaik** [comment] 2020-09-03 01:09
Throwing I/O error even with the pro version. It fails to either load or copy file which is 4GB in size. 
OpError: /content/drive/Shared drives/.../model.ckpt-0.data-00000-of-00001; Input/output error

**Comment by zectre** [comment] 2020-11-21 12:13
still got this error

**Comment by manjithreddy** [comment] 2020-11-30 03:07
any solution to this problem found?

**Comment by rchurt** [comment] 2020-11-30 04:54
Inferring from what others have posted, it seems that Google puts some read/write caps on Drive, and if you exceed them, you'll get this error unless you wait for 24 hours without reading or writing. It would be nice if the error message were more specific.

**Comment by AlainMindana** [comment] 2020-12-08 00:16
@rchurt  yup, even with google colab pro and having 100gb storage in drive if this error occurs(in my case this only occur if I factory reset the runtime and run colab again) then you have to wait 1 day to reset the quota. This might be a cloud issue here they have to "empty" the virtual storage and machine used to compute large files.

**Comment by arcticant** [comment] 2020-12-09 08:01
same problem for me, very annoying

**Comment by huynguyenbao** [comment] 2020-12-31 04:00
Yeah, the same problem with colab pro, anyone has fixed it?

**Comment by CharleoY** [comment] 2021-01-04 11:14
Same error, subscribed 200gb gdrive

**Comment by Deferf** [comment] 2021-01-28 07:47
Same problem here, still.

**Comment by manastahir** [comment] 2021-01-28 15:09
Same problem here, copying even just a 10GB zip file gives this error

**Comment by mpriessner** [comment] 2021-02-04 11:04
I ran into the same problem training a neural network using big LMBD files (~ 15GB). First it was working and after some time I also observed the Input/output error discussed here. 

Since I was quite under time pressure to finish the training I found a workaround with the help of a friends google drive account.
I shared my big training files with him, then I created a copy of that file using the browser google drive and I moved the copied trainings files onto his account which I then was able to access to continue my training. 

It is not ideal but if you are under time pressure this might be a workaround solution.

**Comment by richtertill** [comment] 2021-03-30 08:29
A workaround that helped me with a similar issue* was to use incognito mode, as suggested by google support, because of the Cache.

*I have accessed a folder with many (~250k) subfolders which resulted in the I/O error.

**Comment by rozerinyildiz** [comment] 2022-03-20 10:14
I have the same problem, and unfortunately didn't find any solution for that yet. In my opinion it is about the size of dataset, that's why i ve cut some dataset and used less datas then fixed it.

**Comment by Sugandha14** [comment] 2022-08-19 19:08
OSError: [Errno 5] Input/output error: on 12 GB dataset. I am barely able to train ones in three days. Time-out error is persistant. Even after buying 100 GB storage and Colab pro+. Problem is still persisting. @colaboratory-team hwta else do you need us to buy for a smooth data load? Clearly no solution has been provided even after so many comments.

**Comment by mpriessner** [comment] 2022-08-23 03:55
One solution which worked for me is to zip the files and folders -> Upload them to google drive -> download them locally on the google colab instance -> unzip them locally 

this worked for me when working with many files and folders
Good luck!

**Comment by agiveon** [comment] 2023-07-22 12:27
Here's a solution that works

def get_filenames(path):
    with os.scandir(path) as entries:
        for entry in entries:
            yield entry.name

all_images_and_labels = list(get_filenames(images_and_labels_folder))

**Comment by deanp70** [comment] 2024-03-17 14:51
Posting with permission from @cperry-goog - we're collaborating with the Colab team to provide DagsHub Storage as an alternative to GDrive that is more scalable and built for use with large datasets. It's an S3-compatible bucket that has much simpler access controls, and can be mounted easily.

It might help avoid the issues above - [here's a link to an example notebook to try it out](https://colab.research.google.com/#fileId=https%3a%2f%2fdagshub.com%2fDagsHub%2fDagsHubxColab%2fraw%2f7a674bc098ac6a25e78ac89adb3527aee45fe278%2fDagsHub_x_Colab-DagsHub_Storage.ipynb)

We're looking for community feedback, so I'd love to get your input if it helps with the issue at hand.

(If you're curious, [DagsHub](https://dagshub.com/) is a platform for ML teams which is why we think Colab should have a storage solution suitable for ML workloads)
