### ISSUE TITLE
Unable to load collab. invalid command

### ISSUE THREAD

**Issue by Rajpal9** [googlecolab/colabtools#2255] opened 2021-09-17 17:34 UTC
**Describe the current behavior**
I am unable to open my google collab notebooks or even create new ones as collab specifies the error as unable to load collab
![collab error](https://user-images.githubusercontent.com/90927685/133830236-76e330b1-b72c-4ca1-8c43-9d40a3f472e7.PNG)
**What web browser you are using**
Chrome, Firefox

**Comment by roylau98** [comment] 2021-09-17 17:39
Having the same exact issue, closing all extensions does not solve this problem. Tried on Chrome, Firefox and Microsoft Edge.

**Comment by craigcitro** [comment] 2021-09-17 18:19
Duplicate of #2250

**Closed by craigcitro** 2021-09-17 18:19 UTC
Labels: bug
