### ISSUE TITLE
Vulkan Rendering Support

### ISSUE THREAD

**Issue by Bam4d** [googlecolab/colabtools#3302] opened 2022-12-17 14:16 UTC
**Is your feature request related to a problem? Please describe.**

Vulkan is a next-generation rendering pipeline and is used in RL environments such as Griddly:
https://griddly.readthedocs.io/en/latest/

Vulkan allows fast headless rendering of pixel-based RL environments... but currently google colab does not support this and throws an error saying libvulkan is missing.

Usually libvulkan is included in mesa (software rendering using llvmpipe) and nvidia drivers by default, but they may have been removed from the colab runtime.

**Describe the solution you'd like**
Colab servers should contain libvulkan support and allow these vulkan pipelines to be used for fast pixel-based rendering in RL environments.

**Describe alternatives you've considered**
Render cpu side manually using numpy (which is significantly slower)

**Additional context**

Currently this simple example crashes due to the missing driver:

```
!pip install griddly
!pip install pyglet
!pip install gym[classic_control]
!pip install gym[other]

from google.colab.patches import cv2_imshow
import gym

env = gym.make("GDY-Spiders-v0")

env.reset()

for i in range(10):
   obs, reward, done, info = env.step(env.action_space.sample())

   if reward > 0:
     print(f"reward at step {i}: {reward}")
     pixels = env.render(observer="global", mode="rgb") # CRASH because vulkan attempts to load
     cv2_imshow(pixels)

   if done:
     print("resetting environment")
     env.reset()

"""
```

**Comment by Bam4d** [comment] 2022-12-17 15:01
I've answered my own question with some googling.

you can install vulkan using `!apt-get install libvulkan-dev`

**Comment by AnukritiSinghh** [comment] 2023-04-05 20:26
@Bam4d Its now showing 
`Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
/build/vulkan-tools-KEbD_A/vulkan-tools-1.2.131.1+dfsg1/vulkaninfo/vulkaninfo.h:371: failed with ERROR_INCOMPATIBLE_DRIVER`
Can you help me resolve this please?

**Comment by Bam4d** [comment] 2023-04-06 11:30
I'm not entirely sure how to fix this other than trying to install updated vulkan drivers?

**Comment by Bam4d** [comment] 2023-04-06 12:53
#3556

**Comment by AnukritiSinghh** [comment] 2023-04-06 12:58
The solution mentioned in #3302 is not working anymore. That was my issue,
that it changed overnight. And I am confused if there were any updates in
the driver that caused this?

You can reproducing this by first installing and then trying vulkaninfo

**Comment by cperry-goog** [comment] 2023-04-13 16:45
I think this is a dupe of #3556

**Closed by cperry-goog** 2023-04-13 16:45 UTC
Labels: feature
