### ISSUE TITLE
Tesla K80 GPU shown instead of Tesla T4

### ISSUE THREAD

**Issue by ManzarIMalik** [googlecolab/colabtools#661] opened 2019-08-01 15:52 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I was training my YOLO based dataset using Google Colab for quite some days, it was working perfectly fine and using Tensor cores, making training. Earlier it was using Tesla T4 GPU, checked with
`!nvidia-smi`  
![image](https://user-images.githubusercontent.com/25642527/62307886-dfda4680-b49d-11e9-80d2-cf35fc3e415f.png)
but now I am only seeing Tesla K80 GPU on my Google account, Is there any limitations to GPU usage? Any way to get Tesla T4 back in my notebook?
- Describe the expected behavior:
I expect to use Tesla T4 GPU instead of Tesla K80 but it's not showing up now, want to use Tesla T4 again on my current Google account. 
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link to self-contained notebook that reproduces this issue:
  https://colab.research.google.com/github/shoji9x9/train-yolov3-on-google-colaboratory/blob/master/Training.ipynb

**Comment by OPHoperHPO** [comment] 2019-08-07 09:16
**+1**
I have a similar issue.
I tried to create new .ipynb notebooks, but the problem remained in its place.

Most likely this issue is a duplicate of [this](https://github.com/googlecolab/colabtools/issues/655)

**Comment by ManzarIMalik** [comment] 2019-08-07 18:01
@OPHoperHPO, 

Yes, @googlecolab might have a limitation on per account usage, which they haven't disclosed yet. Tried to get their comment on this, but they seem to be unreachable. However, if you switch account and use Colab, the problem seems fixed but on the earlier account, you may never get access to Tesla T4 GPU. That's very strange. 

[This](https://github.com/googlecolab/colabtools/issues/655) issue was closed by author despite no comment on by @googlecolab. So I made this issue. Cheers.

**Comment by tmabraham** [comment] 2019-08-10 22:31
I am having the same problem. Will any member of the @googlecolab team care to comment? @CSEMike @craigcitro @corrieann @colaboratory-team

**Comment by craigcitro** [comment] 2019-08-10 22:59
https://research.google.com/colaboratory/faq.html#gpu-availability

**Comment by tmabraham** [comment] 2019-08-10 23:28
@craigcitro does this mean I cannot ever use the Tesla T4 GPU for my Colab account or is this temporary?

**Comment by OPHoperHPO** [comment] 2019-08-16 10:20
> @craigcitro does this mean I cannot ever use the Tesla T4 GPU for my Colab account or is this temporary?

This is temporary. I have not used colab for several days, and this problem was resolved on its own.

**Comment by OPHoperHPO** [comment] 2019-08-16 10:23
@tmabraham
This is temporary. I have not used colab for several days, and this problem was resolved on its own.

**Comment by ManzarIMalik** [comment] 2019-08-16 13:54
Yes @OPHoperHPO, you are right. I can now see T4 too after about 15 days of no use Colab. 

> This is temporary. I have not used colab for several days, and this problem was resolved on its own.

**Closed** 2019-08-16 13:54 UTC

**Comment by donmahallem** [comment] 2019-08-25 19:34
AFAIK it is luck of the draw if you do get a K80 or a T4. It's completly random for me

**Comment by tmabraham** [comment] 2019-09-05 21:20
I have not received access to T4 at all. I have not used the account for almost a month and when I checked, it was still K80.

**Comment by ceciliacsilva** [comment] 2019-10-15 12:08
Same problem here...

**Comment by pjmartel** [comment] 2019-10-19 13:07
Most likely this is not an "issue" at all. It's just that Google resources for Colab are limited and when all T4 nodes are in use you will get what's available (K80). I don't think it has anything to do with specific accounts.

**Comment by mengfu188** [comment] 2020-01-15 08:03
[/nvidia-tesla-t4-gpus-now-available](https://cloud.google.com/blog/products/ai-machine-learning/nvidia-tesla-t4-gpus-now-available-in-beta)

**Comment by qo4on** [comment] 2020-02-25 13:43
I also have K80 instead of T4. I used it for several minutes computation, never for a long time.

**Comment by qo4on** [comment] 2020-02-25 13:46
upd:
Now it shows `Tesla P4 `.

**Comment by Rexfarell** [comment] 2020-03-24 04:42
The more you use colab, the lower your chances to have access to a Tesla T4.

**Comment by qo4on** [comment] 2020-03-24 07:42
Tesla P100 costs more than T4.

**Comment by IbrohimBest** [comment] 2021-11-21 12:43
That's not judge. Only 12hours using Best GPUs and 15 or even a month to wait is not judge. I tried more accounts, still getting That oldfarmer Tesla K80

**Comment by qo4on** [comment] 2021-11-21 14:06
For months now, I've been getting nothing but K80 and nothing but it. Colab has become useless.
