### ISSUE TITLE
PRO+ GPU problem

### ISSUE THREAD

**Issue by ivanhonis** [googlecolab/colabtools#3117] opened 2022-10-04 15:59 UTC
I have a PRO+ account,
But I can't connect to premium GPU, I also paid for extra calculation but nothing changed.
The notebook recommends to use premium GPU, but I can't turn it on.
And I can't turn off background running because that checkbox is missing.

It was working 3 days before but the environment window has changed.

AND sorry to write this here, But I don't have any other forum: NO ONE has ASNWER MY LETTERS.

Actually there is notthing suport.

I HAVE PAID 50 USD + 9 USD EXTA CAPACITY but I GET have less then the free version.

**Comment by masterinfo** [comment] 2022-10-05 08:15
I have a PRO+ account+ drive,
But I can't connect with  GPU 
since yesterday and cannot work !!!!

**Comment by sundog777** [comment] 2022-10-05 13:38
same boat here, scratching my head over how this is possible, that they would treat their premium members this way.... I kept on trying and once or twice was lucky over the past 5 or 6 days... I did once get a warning that i didnt have the latest drivers for nvidia... did anybody else get this? Could this be the issue?

I was on a colab pro+ account too

**Comment by zsaid01** [comment] 2022-10-05 14:52
i have a pro plus account too and i have the same issue ... when the problem is going to be solved ? i have an urgent work and i have no other alternative ...

**Comment by pnorridge** [comment] 2022-10-05 16:15
similar for me - I have Colab Pro, but was allocated no compute units and am having difficulty connecting to a GPU

**Comment by cperry-goog** [comment] 2022-10-05 16:37
Thanks for reporting, we had an intermittent issue where some Pro+ users weren't getting assignments, that is getting fixed shortly.

As for background execution, all Pro+ notebooks will now default to background execution, no setting required.

**Comment by cperry-goog** [comment] 2022-10-05 18:17
The primary bug is resolved in prod now; do submit in-product feedback if you encounter other problems.

**Closed by cperry-goog** 2022-10-05 18:17 UTC
Labels: bug

**Comment by sundog777** [comment] 2022-10-06 18:40
> The primary bug is resolved in prod now; do submit in-product feedback if you encounter other problems.

Hello! 
It was working from when you last said it was... However,
It just happened again, I shut my laptop while it was generating I come back home and all of a sudden its saying the gpu problem. I've retried it a few times now. Whatever solution you have found, it is not proving to have longevity.

**Comment by sundog777** [comment] 2022-10-06 19:45
[image: Screenshot 2022-10-06 at 20.38.10.png]

**Comment by sundog777** [comment] 2022-10-06 19:57
i definately havent over-done my balance, i've barely been able to use it because all of these problems started around the time I signed up to pro+... I can't find the error you spoke of... 

I also submitted on product feedback but maybe its better to talk on here so others who may have the same problem could get a quick fix... 

<img width="601" alt="Screenshot 2022-10-06 at 20 38 10" src="https://user-images.githubusercontent.com/115086592/194406633-3aee59d3-cd56-4472-9047-f20b9be654e6.png">
