### ISSUE TITLE
Unable to upload local files: google.colab.__files is undefined

### ISSUE THREAD

**Issue by xprilion** [googlecolab/colabtools#51] opened 2018-02-08 02:17 UTC
Using the file upload code snippet on both python3 and python2 I get the error message:

```
---------------------------------------------------------------------------
MessageError                              Traceback (most recent call last)
<ipython-input-3-292f82be1b7a> in <module>()
      1 from google.colab import files
      2 
----> 3 uploaded = files.upload()
      4 
      5 for fn in uploaded.keys():

/usr/local/lib/python3.6/dist-packages/google/colab/files.py in upload()
     59   result = output.eval_js(
     60       'google.colab._files._uploadFiles("{input_id}", "{output_id}")'.format(
---> 61           input_id=input_id, output_id=output_id))
     62   files = collections.defaultdict(six.binary_type)
     63 

/usr/local/lib/python3.6/dist-packages/google/colab/output/_js.py in eval_js(script, ignore_result)
     37   if ignore_result:
     38     return
---> 39   return _message.read_reply_from_input(request_id)
     40 
     41 

/usr/local/lib/python3.6/dist-packages/google/colab/_message.py in read_reply_from_input(message_id, timeout_sec)
     84         reply.get('colab_msg_id') == message_id):
     85       if 'error' in reply:
---> 86         raise MessageError(reply['error'])
     87       return reply.get('data', None)
     88 

MessageError: TypeError: google.colab._files is undefined
```

**Comment by craigcitro** [comment] 2018-02-08 04:25
I can't seem to reproduce this -- does this always happen, or only sometimes?

If you open the chrome JS console (ctrl-shift-j or cmd-shift-j on a mac), do you have any errors there?

**Comment by blois** [comment] 2018-02-08 16:26
Which browser is this occurring in? If Chrome, are you seeing a warning when initially opening the document?

**Comment by xprilion** [comment] 2018-02-09 15:15
I am using Firefox 58.0.1 (64 bit) on Ubuntu 17.10 with lxqt env

**Comment by blois** [comment] 2018-02-14 00:24
I'm working on a fix for this, in the meantime I would recommend using Chrome. This is specifically running into https://bugzilla.mozilla.org/show_bug.cgi?id=1279406.

**Comment by rocarvaj** [comment] 2018-02-14 03:44
I'm also experiencing the same issue on Safari 11.0.3. I guess I'll stick to Chrome.

**Comment by blois** [comment] 2018-02-14 17:06
Safari's Service Worker implementation is available in the preview version, though we haven't had a chance to test them yet. See https://webkit.org/status/#specification-service-workers.

**Comment by hynekcer** [comment] 2018-02-19 18:29
I was also experiencing this issue in Chrome an Firefox, together with this small issue #17 on Colaboratory notebook startup:

> Could not access the resources needed to display output.
This is probably because third-party cookies are not allowed by your browser.
>
> NotSupportedError: Failed to register a ServiceWorker: The user denied permission to use Service Worker.

The notebook worked acceptably then, except `files.upload()`.
 
When I enabled **third-party cookies** in Chrome settings the issue was solved.

I would prefer a solution with setting only some allow rules for Google domains.

**Comment by hynekcer** [comment] 2018-02-21 13:40
I am adding some context for other people because I found a link to this issue from an [stackoverflow answer](https://stackoverflow.com/a/48777857/448474).

Shortly: **Chrome** works if **third-party cookies** are enabled in settings. No easy or complicated solution exists currently for Firefox (that say posts above)

I wrote some [summary about `files.upload()`](https://stackoverflow.com/a/48904662/448474), especially for people that search a solution by error messages.

**Comment by hynekcer** [comment] 2018-02-21 14:01
It would be nice to customize the message
>  Upload widget is only available when the cell has been executed in the current browser session. Please rerun this cell to enable.

and replace the words "Please rerun this cell to enable." by "This browser is probably not supported for upload." if detected by some simple whitelist or blacklist.

This will help very much temporarily.  (question "I rerun the cell but it doesn't work...")

It also helps to get more complete questions or issue reports because all four questions at stackoverflow that I found (and fixed little) were without information about the browser and sometimes neither considered it in answers. (like "I have no problem.")

**Comment by guptasaurabh9868** [comment] 2018-04-22 20:52
It is also happening in google chrome.

**Comment by blois** [comment] 2018-08-28 00:43
There is a new file upload UI in the notebook sidebar, alongside the table of contents.

**Closed by blois** 2018-08-28 00:43 UTC

**Comment by martosinc** [comment] 2020-06-07 23:23
You can also just reinstall all your packages

**Comment by chez8990** [comment] 2021-12-12 14:49
![image](https://user-images.githubusercontent.com/16471709/145717136-6f8272f1-526c-4c02-924f-1731e758d1c9.png)
It's been 3 years and I'm still getting this error

**Comment by craigcitro** [comment] 2021-12-13 16:41
@chez8990 could I ask you to file a new issue and include (1) info about what browser you're using and (2) whether it works in an incognito window?

**Comment by myaouri** [comment] 2021-12-23 12:04
@chez8990 Could you please tell me on which browser have you been having this issue? If it's firefox, I had a fix for mine.

**Comment by ankur-bohra** [comment] 2021-12-26 13:54
@myaouri I'm running into this issue on Firefox, sharing the solution would be appreciated.

**Comment by myaouri** [comment] 2021-12-28 04:50
Under 'Cookies and Site Data' I simply unchecked '**Delete cookies and site data when Firefox is closed**' from Privacy and Security from firefox preferences. My Firefox version : 91.4.1esr

<img width="990" alt="Screen Shot 2021-12-27 at 11 42 30 PM" src="https://user-images.githubusercontent.com/60943384/147529210-0f0c4bf4-79ca-4f83-b105-3c052b8cc41d.png">

**Comment by myaouri** [comment] 2021-12-28 04:52
@ankur-bohra Under 'Cookies and Site Data' I simply unchecked 'Delete cookies and site data when Firefox is closed' from Privacy and Security from firefox preferences. My Firefox version : 91.4.1es


<img width="990" alt="Screen Shot 2021-12-27 at 11 42 30 PM" src="https://user-images.githubusercontent.com/60943384/147529432-21bcf568-7407-4eba-aa0a-f6282e1b08e6.png">
r

**Comment by ichsanputr** [comment] 2022-03-17 03:34
Just information if you get error message like this

Upload widget is only available when the cell has been executed in the current browser session. Please rerun this cell to enable.

**Comment by izadimasoome** [comment] 2022-08-18 08:10
hi thanks.......I tried it with chrome and got the result

**Comment by JackSCJackson** [comment] 2022-09-09 14:37
Issue happening with latest chrome version, anyone got a fix?
