### ISSUE TITLE
Runtime disconnected error - Google Colab notebook gets disconnect after every 5-6 minutes

### ISSUE THREAD

**Issue by Abhishek-Soni-93** [googlecolab/colabtools#2125] opened 2021-07-09 20:31 UTC
**Describe the current behavior**
I was trying to train my tensor flow object detection model on colab notebook using GPU runtime and it suddenly gets disconnected after every 5-6 minutes. Even though I was working and writing code simultaneously while running the notebook. And when I tried to reconnect and run the notebook it again disconnect after 5-6 mintues. 

Getting error - 
**Runtime disconnected**

"Your runtime has been disconnected due to inactivity or reaching its maximum duration.
For longer running notebooks, consider upgrading to Colab Pro.
To connect to a new runtime, click the connect button below."

**Describe the expected behavior**
It should be run at least for 90 minutes with out inactivity.

**What web browser you are using**
I tried with Google chrome and Firefox both. I'm getting the same error in both the browser.

**Comment by cperry-goog** [comment] 2021-07-15 21:28
Duplicate of #2032

**Closed by cperry-goog** 2021-07-15 21:28 UTC
Labels: bug

**Comment by ZOD07** [comment] 2023-07-12 11:39
Does anyone got sny solution for this?
