### ISSUE TITLE
Sorry no backends available error popping up everytime I try to connect to runtime

### ISSUE THREAD

**Issue by sd2001** [googlecolab/colabtools#1293] opened 2020-05-30 13:03 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by Bluff-0** [comment] 2020-05-30 13:28
<img width="288" alt="Screenshot (51)" src="https://user-images.githubusercontent.com/46003015/83329475-6373e800-a2a7-11ea-8827-6f021d057a56.png">
 The same problem is happening.

**Comment by colaboratory-team** [comment] 2020-05-30 17:23
Duplicate of #1287

**Closed by colaboratory-team** 2020-05-30 17:23 UTC
