### ISSUE TITLE
Managing Colab Sessions via Google Colab Povided Code

### ISSUE THREAD

**Issue by faruknane** [googlecolab/colabtools#2633] opened 2022-02-19 16:03 UTC
I often run some code on google colab and when it is finished, the colab session just waits for no reason until it closes itself subsequently when I am away from keyboard. I think this happening a lot of time will affect my priority to access colab since it probably measures GPU usage and wasted time that is not utilized. I searched if there is a way to close colab instance via code. However, I couldn't find any recent solution on the internet, there was always written like "this no longer works". That's why I wanted to write here. Can we have decent code that is provided from google colab to close the current colab instance in the notebook and also maybe to manage all colab instances?

I can automatically close the current instance via javascript code by running it in the console like every 3-5 secs and check if my work is finished, then click appropriate buttons to close the current session. However, this is not the best way to do it. So, I am wondering if can make some efforts on this issue?

Thanks.

**Comment by blois** [comment] 2022-02-24 22:29
This is a duplicate of https://github.com/googlecolab/colabtools/issues/2536

**Closed by blois** 2022-02-24 22:29 UTC
Labels: feature
