### ISSUE TITLE
Failed to assign a backend google colab

### ISSUE THREAD

**Issue by deeppatel4557** [googlecolab/colabtools#1295] opened 2020-05-30 14:09 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).
![bug](https://user-images.githubusercontent.com/51253332/83330467-c3b95880-a2ac-11ea-848d-c19ce5376184.PNG)

- Describe the current behavior:
I am not able to use any of the resources from colab not even simple notebook without accelerator
- Describe the expected behavior:
Colab has backend machines available till now, but today it has no backend machines available!!!!
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Firefox
- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by colaboratory-team** [comment] 2020-05-30 17:23
Duplicate of #1287

**Closed by colaboratory-team** 2020-05-30 17:23 UTC
