### ISSUE TITLE
Colab shows pickle 5 protocol error (python 3.7)

### ISSUE THREAD

**Issue by karbapi** [googlecolab/colabtools#2561] opened 2022-01-19 13:06 UTC
**Describe the current behavior**
**....
....
  File "/usr/local/lib/python3.7/dist-packages/networkx/utils/decorators.py", line 795, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
  File "<class 'networkx.utils.decorators.argmap'> compilation 5", line 5, in argmap_read_gpickle_1
  File "/usr/local/lib/python3.7/dist-packages/networkx/readwrite/gpickle.py", line 105, in read_gpickle
    return pickle.load(path)
ValueError: unsupported pickle protocol: 5**

**Describe the expected behavior**
I should be able to load the input data files using pickle.load()
Python version in Colab: 3.7.12 with cloudpickle 1.3.0 and pickleshare 0.7.5 . On the contrary, my local machine running with python 3.8.2 and cloudpickle 2.0.0 and pickleshare 0.7.5  does not have any issues in loading the files using pickle.load().

Note: both have networkx 2.6.3 in this case.

**What web browser you are using**
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by craigcitro** [comment] 2022-01-20 07:15
Pickle protocol 5 was added in python 3.8: https://www.python.org/dev/peps/pep-0574/

Duplicate of #2165 (which is a permutation of this bug number, amusingly enough).

**Closed by craigcitro** 2022-01-20 07:15 UTC
Labels: bug
