### ISSUE TITLE
Spelling and grammar checked in text cells

### ISSUE THREAD

**Issue by fickas** [googlecolab/colabtools#3038] opened 2022-08-30 23:20 UTC
**Is your feature request related to a problem? Please describe.**
I write a lot of text as part of a notebook I hand to my students. It is embarrassing to have misspellings.

**Describe the solution you'd like**
Ideal, link into Grammarly. Second best, integrate a spellchecker into text cells.

**Describe alternatives you've considered**
I have to download the notebook to py file then open in Sublime, which does have a spellchecker.

**Additional context**

**Comment by craigcitro** [comment] 2022-09-01 21:08
Agreed this would be nice -- we have a pending feature request for this, but no active work in this direction. Marking as dupe of the existing issue (which I'm reopening).

Duplicate of #43

**Closed by craigcitro** 2022-09-01 21:08 UTC
Labels: feature

**Comment by fickas** [comment] 2022-09-02 20:05
Thanks. I'd take a simple off-the-shelf spellchecker to start.
