### ISSUE TITLE
Interrupting Keras execution causes lost connection to Google Drive

### ISSUE THREAD

**Issue by haavepaja** [googlecolab/colabtools#794] opened 2019-10-06 11:09 UTC
Bug report for Colab: http://colab.research.google.com/.

- Describe the current behavior:
Interrupting a long running Keras execution cell causes lost connection to Google Drive. Interrupting other cells doesn't seem to cause the same.

- Describe the expected behavior:
Interrupting a long running Keras execution cell: see an interrupt error message but maintain connection to Google Drive (this used to work perfectly for at least a year, but got broken just a couple of days ago).

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/1ltTbHgmvCeXMIO08XoAf7t1QIKQyqiom

**Comment by intEll1gent** [comment] 2019-10-09 11:39
Just adding to this issue (didn't start a new one as it is essentially the same):

- The problem doesn't happen only with Keras, interrupting sklearn `LogisticRegression.fit` threw up the same issue for me. 
- The cell need not be running for a long time, the issue pops up right after you interrupt such a cell. 
- Google Drive features becomes unusable after this on that particular notebook only, restarting the runtime, or the whole notebook does not help. 
- Other code, not related to Google Drive works fine, as already reported by the op.

Web browser: Safari

**Comment by colaboratory-team** [comment] 2019-10-31 15:46
Duplicate of https://github.com/googlecolab/colabtools/issues/837

**Closed by colaboratory-team** 2019-10-31 15:46 UTC
