### ISSUE TITLE
"Run all" issue

### ISSUE THREAD

**Issue by aveshag** [googlecolab/colabtools#1175] opened 2020-04-24 10:02 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
on "Run all" Colab did not execute cells sequentially and skip some intermediate cells and result in an error because of dependency on the above cells. 

- Describe the expected behavior:
It should run sequentially so that upcoming cells can find their variables or other dependencies 
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Firefox

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://colab.research.google.com/drive/13FXkchCXXHF50IkETboIaUtbXPns4Qoa

**Comment by jakevdp** [comment] 2020-04-24 12:43
I'm not able to reproduce this: I opened the notebook you linked to, chose *Runtime->Run All*, and the cells executed in order.

Can you give more details about this? Is it something you observe consistently?

**Comment by aveshag** [comment] 2020-04-25 09:06
Now, It is also working fine for me but I don't know why this was happening earlier. Do you know why this was the case?

**Comment by VSumanth99** [comment] 2020-05-02 10:59
It happens with me as well. It happens quite frequently, but it is not consistent, i.e. sometimes the issue just corrects itself when I run all a few times.

**Comment by craigcitro** [comment] 2020-05-06 18:05
If anyone manages to repro this:

* if you have a consistent repro notebook, that's amazing
* if you see it happen, `Help` -> `Send feedback` with the approximate time you saw it and we can see if we can find any clues

**Comment by craigcitro** [comment] 2020-05-06 18:13
... or a screencast.

**Comment by short-circuitt** [comment] 2020-05-27 10:29
I replicated it with the following notebook:

https://colab.research.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Probabilistic_Layers_VAE.ipynb

Using the "Restart and run all" command (interrupting execution at the inference step) it failed for me 4/10 runs.

I used the Help -> Send feedback function on one of the examples.

**Comment by craigcitro** [comment] 2020-05-27 17:25
Thanks for the notebook -- sadly, I still can't manage to repro the bug.

What browser/version? Can you still repro in an incognito window?

**Comment by short-circuitt** [comment] 2020-05-27 18:45
Browser: Mozilla Firefox for Ubuntu 76.0.1 (64-bit)
OS: Ubuntu 18.04.4

Error also exists in incognito window, but I have to log into my account to execute the notebook anyway.

I also tested on Google Chrome Version 83.0.4103.61 (Official Build) (64-bit) on same Ubuntu 18.04.4 system and could not replicate this bug in ~10 tests.

**Comment by blois** [comment] 2020-05-27 19:07
Thank you- we can now repro the issue and the fix should be out in a few days.

**Comment by blois** [comment] 2020-06-01 16:44
This should be fixed now.

**Closed by blois** 2020-06-01 16:44 UTC
Labels: triaged

**Comment by nikita-galileo** [comment] 2022-05-10 20:17
How was this fixed? I seem to be encountering a similar issue on Colab still where cells run out of order.
