### ISSUE TITLE
I cannot pay for Colab pro

### ISSUE THREAD

**Issue by miracle6719** [googlecolab/colabtools#1569] opened 2020-09-08 08:53 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: When I extend my membership of colab pro, I got this error message [OR-FGBFDL-25]

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment] 2020-09-08 15:50
duplicate of #1562

**Closed by craigcitro** 2020-09-08 15:50 UTC
