### ISSUE TITLE
Accessing/Copying a large file from a `drive.mount()`d directory can incorrectly trigger "A Google Drive quota has been exceeded" toast (and I/O error)

### ISSUE THREAD

**Issue by world2vec** [googlecolab/colabtools#1607] opened 2020-09-26 22:31 UTC
Hi google,
I am struggle with this issue, I do copy the file to colab /tmp after mount the drive, but I still get this issue.
It happen even for files less then 1M sometimes.
Thanks.

**Comment by world2vec** [comment] 2020-09-26 23:04
Well, I just think does you guys use RL algorithm to control the QUOTA? Because the file blocked looks a little randomly choosed from visited files.
Thanks

**Comment by ruchikalalit** [comment] 2020-09-27 03:06
I am also facing the same issue, while using colab with google drive. I mount the drive with 2tb of storage space, but the program execution takes only disk storage available with colab and when it get filled it, message popups that you have exceeded the  drive limit. my program need around 400gb or may be more space for complete execution but am not able to do it as every time program generates error due to storage.
Thanks

**Comment by colaboratory-team** [comment] 2020-09-29 02:43
@world2vec there are various quotas in play; is the under-1MiB file that you see this with private or shared?  A common cause for quota-exceeded errors on not-huge files like this is per-file limits (across all users). Making a private copy of the file in your Drive and using that will prevent this issue.

@ruchikalalit your issue is different (very large data) and is replied to in #1608.

**Comment by world2vec** [comment] 2020-09-30 10:15
@colaboratory-team 
Could you reopen it?
My files are not shared.
It also happen when I copy files bigger than 10G. So what is the limit of  amount of data I can transfer from my drive? 
Is it possible to give us details of the quota? What should I do to transfer large amount of data from My drive? (10g is really tiny for modern day deep learning task)

Thanks.

**Comment by colaboratory-team** [comment] 2020-09-30 23:45
@world2vec the fact that a 10G copy causes transfer quota to be exceeded is a bug (the issue is not that there's a quota less than 10G but rather that copying large files can incorrectly charge for much much more than 10G); tracked internally as b/168928162. 
An unfortunate workaround is to download the file directly (outside the `drive.mount()`'d directory) using a tool like `!gdown ...` or the [PyDrive API](http://colab.research.google.com/notebooks/io.ipynb#scrollTo=7taylj9wpsA2).

**Comment by world2vec** [comment] 2020-10-02 00:57
Hi,
Actually I tried gdown by share the link of my Drive file, it also failed, but I will double check.

**Comment by world2vec** [comment] 2020-10-14 10:39
gdown worked

**Comment by colaboratory-team** [comment] 2020-10-19 18:46
Thanks for confirming, @world2vec.

Reopening this issue pending the fix becoming available to users, which sadly is likely to take a couple of months (sorry about that).
Until then: users who encounter this issue should the workarounds in https://github.com/googlecolab/colabtools/issues/1607#issuecomment-701704057.

**Comment by world2vec** [comment] 2020-11-13 22:35
@colaboratory-team
unfortunately, even with gdown if I access the 10G file several times in 24 hours, it will be blocked.
I do not know why google drive block the link, but what should I do?
By the way, when this bug will be solved so I can copy from mounted drive?

**Comment by colaboratory-team** [comment] 2020-11-13 22:50
@world2vec downloading the file in chunks of e.g. 128MiB should help (e.g. using https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range).
Hopefully bug will be resolved so that vanilla `cp` doesn't trigger spurious quota exhaustion with by year-end.

**Comment by colaboratory-team** [comment] 2020-12-11 00:09
This issue should be fixed in VMs started in the last few hours.
(though, of course, since the quotas involved are not instantaneous it might take existing exhaustion some hours/days to wear off).
Sorry for the hassle and thanks for bearing with us.

**Comment by colaboratory-team** [comment] 2021-02-23 18:08
Belated update: the fix deployed in Dec had to be reverted for a different bug. Reopening this issue to track eventual resolution of this issue. 

Until then: users who encounter this issue should use the workarounds in https://github.com/googlecolab/colabtools/issues/1607#issuecomment-701704057.

**Comment by truboxl** [comment] 2021-02-24 05:04
I find that `rsync` works reliably compared to `cp`. If you only work within the VM's disk space and not directly R/W gdrive, maybe give that a try...

**Comment by colaboratory-team** [comment] 2021-03-29 19:38
Fix from Dec is finally rolled out again and current status is https://github.com/googlecolab/colabtools/issues/1607#issuecomment-742880362.

**Closed by colaboratory-team** 2021-03-29 19:38 UTC
