### ISSUE TITLE
while文、input、clear_outputの組み合わせで枠が表示されなくなる~The combination of while statement, input, and clear_output does not display the frame.~

### ISSUE THREAD

**Issue by KantanRamen** [googlecolab/colabtools#4922] opened 2024-10-28 08:22 UTC
**Describe the current behavior**
while文、input、clear_outputの組み合わせで
inputの枠が消滅し、先に進まなくなる。
With a combination of while statements, input, and clear_output
The input frame disappears and you can't move forward.

**Describe the expected behavior**
inputの枠が表示される。
The input frame is displayed.

**What web browser you are using**
Chrome

**Additional context**
https://colab.research.google.com/drive/1x2OPbi6S5QO22CV204HhXNALUMFaIabI?usp=sharing

**Comment by EvanWiederspan** [comment] 2024-10-31 21:54
Duplicate of https://github.com/googlecolab/colabtools/issues/2889

**Closed by EvanWiederspan** 2024-10-31 21:54 UTC
Labels: bug
