### ISSUE TITLE
ValueError: mount failed: invalid oauth code

### ISSUE THREAD

**Issue by kaiyungtan** [googlecolab/colabtools#1568] opened 2020-09-07 14:11 UTC
Hi, i am trying drive mount on google colab and this happened as showned below: I have used google colab before with no problem. Please assist.

from google.colab import drive
drive.mount('/content/drive')

Enter your authorization code:
··········
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-d5df0069828e> in <module>()
      1 from google.colab import drive
----> 2 drive.mount('/content/drive')

/usr/local/lib/python3.6/dist-packages/google/colab/drive.py in mount(mountpoint, force_remount, timeout_ms, use_metadata_server)
    247       wrote_to_fifo = True
    248     elif case == 5:
--> 249       raise ValueError('mount failed: invalid oauth code')
    250   if not wrote_to_fifo:
    251     with open(fifo, 'w') as fifo_file:

ValueError: mount failed: invalid oauth code

**Comment by codygunton** [comment] 2020-09-07 15:08
I am experiencing the same issue.

**Comment by craigcitro** [comment] 2020-09-07 15:37
The copy button is broken on the oauth page; manually select and copy the code and you'll be good to go.

Duplicate of #1540.

**Closed by craigcitro** 2020-09-07 15:37 UTC

**Comment by kaiyungtan** [comment] 2020-09-07 17:50
thanks. it works. indeed the copy button is broken. Thanks Craig.

**Comment by jerronl** [comment] 2022-01-21 02:13
I got the same problem today. It didn't bring up the link to the auth page but failed with the same error msg.

**Comment by jonathanraditya** [comment] 2022-01-21 02:39
Same here, 12hrs ago works just fine, and now failed with "ValueError: mount failed: invalid oauth code" error message.

**Comment by vicchen-qf** [comment] 2022-01-21 02:44
Same here too! Can only mount the google drive account the colab notebook itself with "drive.mount('/content/drive')"

**Comment by iwashinn** [comment] 2022-01-21 02:56
I also got this error "ValueError: mount failed: invalid oauth code" just today.

**Comment by kdassharma** [comment] 2022-01-21 05:15
Using:
```
from google.colab import drive
drive.mount('/content/drive')
```
gives me (after singing in using the popup):
```
/usr/local/lib/python3.7/dist-packages/google/colab/_message.py in read_reply_from_input(message_id, timeout_sec)
    104         reply.get('colab_msg_id') == message_id):
    105       if 'error' in reply:
--> 106         raise MessageError(reply['error'])
    107       return reply.get('data', None)
    108 

MessageError: Error: credential propagation was unsuccessful
```
and using:
```
from google.colab import drive
drive._mount('/content/drive')
```
gives me:
```
/usr/local/lib/python3.7/dist-packages/google/colab/drive.py in _mount(mountpoint, force_remount, timeout_ms, use_metadata_server, ephemeral)
    294       wrote_to_fifo = True
    295     elif case == 5 and not use_metadata_server:
--> 296       raise ValueError('mount failed: invalid oauth code')
    297     elif case == 6:
    298       # Terminate the DriveFS binary before killing bash.

ValueError: mount failed: invalid oauth code
```

**Comment by researchk** [comment] 2022-01-21 07:02
Hi i am facing this issue since morning. Yesterday it was working perfectly fine. Anybody got the solution?

**Comment by researchk** [comment] 2022-01-21 07:03
> Using:
> 
> ```
> from google.colab import drive
> drive.mount('/content/drive')
> ```
> 
> gives me (after singing in using the popup):
> 
> ```
> /usr/local/lib/python3.7/dist-packages/google/colab/_message.py in read_reply_from_input(message_id, timeout_sec)
>     104         reply.get('colab_msg_id') == message_id):
>     105       if 'error' in reply:
> --> 106         raise MessageError(reply['error'])
>     107       return reply.get('data', None)
>     108 
> 
> MessageError: Error: credential propagation was unsuccessful
> ```
> 
> and using:
> 
> ```
> from google.colab import drive
> drive._mount('/content/drive')
> ```
> 
> gives me:
> 
> ```
> /usr/local/lib/python3.7/dist-packages/google/colab/drive.py in _mount(mountpoint, force_remount, timeout_ms, use_metadata_server, ephemeral)
>     294       wrote_to_fifo = True
>     295     elif case == 5 and not use_metadata_server:
> --> 296       raise ValueError('mount failed: invalid oauth code')
>     297     elif case == 6:
>     298       # Terminate the DriveFS binary before killing bash.
> 
> ValueError: mount failed: invalid oauth code
> ```

Have you found any solution?

**Comment by kdassharma** [comment] 2022-01-21 07:05
> > Using:
> > ```
> > from google.colab import drive
> > drive.mount('/content/drive')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gives me (after singing in using the popup):
> > ```
> > /usr/local/lib/python3.7/dist-packages/google/colab/_message.py in read_reply_from_input(message_id, timeout_sec)
> >     104         reply.get('colab_msg_id') == message_id):
> >     105       if 'error' in reply:
> > --> 106         raise MessageError(reply['error'])
> >     107       return reply.get('data', None)
> >     108 
> > 
> > MessageError: Error: credential propagation was unsuccessful
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and using:
> > ```
> > from google.colab import drive
> > drive._mount('/content/drive')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gives me:
> > ```
> > /usr/local/lib/python3.7/dist-packages/google/colab/drive.py in _mount(mountpoint, force_remount, timeout_ms, use_metadata_server, ephemeral)
> >     294       wrote_to_fifo = True
> >     295     elif case == 5 and not use_metadata_server:
> > --> 296       raise ValueError('mount failed: invalid oauth code')
> >     297     elif case == 6:
> >     298       # Terminate the DriveFS binary before killing bash.
> > 
> > ValueError: mount failed: invalid oauth code
> > ```
> 
> Have you found any solution?

A temporary solution is to mount the drive with the button on the "Files" menu option, this worked for me.

**Comment by researchk** [comment] 2022-01-21 07:14
> 

but I want to mount from my other google account that's why it's not working for me.

**Comment by DinalieLiyanage** [comment] 2022-01-21 09:00
Facing the same issue and I want to mount from another drive as well

**Comment by DinalieLiyanage** [comment] 2022-01-21 09:26
https://github.com/googlecolab/colabtools/issues/2399#issuecomment-1018178585

he has mentioned a solution there, which is the old method. But yet it works

@zechenli03

**Comment by abhilashmandal** [comment] 2022-01-21 10:36
from google.colab import drive
drive.mount('/content/drive')

This code started working again

**Comment by researchk** [comment] 2022-01-21 11:12
> 

not working for me.

**Comment by researchk** [comment] 2022-01-21 11:13
> 
@DinalieLiyanage not working for me.

**Comment by mustafahasankhan** [comment] 2022-01-21 11:31
![image](https://user-images.githubusercontent.com/65130881/150519807-cb9178fb-df00-4f77-8d64-20d4759ed32a.png)
Use this button

![image](https://user-images.githubusercontent.com/65130881/150519864-c5ac9b90-2802-4a0f-a35a-a0301a2536ff.png)

then mount

**Comment by wizmain** [comment] 2022-01-21 13:13
> ![image](https://user-images.githubusercontent.com/65130881/150519807-cb9178fb-df00-4f77-8d64-20d4759ed32a.png) Use this button
> 
> ![image](https://user-images.githubusercontent.com/65130881/150519864-c5ac9b90-2802-4a0f-a35a-a0301a2536ff.png)
> 
> then mount

thanks it works

**Comment by jlmarrugom** [comment] 2022-01-21 14:01
> [#2399 (comment)](https://github.com/googlecolab/colabtools/issues/2399#issuecomment-1018178585)
> 
> @zechenli03 has mentioned a solution there, which is the old method. But yet it works
> 
> @researchk you can use this

This works for me, thanks

**Comment by cperry-goog** [comment] 2022-01-21 18:20
dupe with #2563

**Comment by Vision238** [comment] 2022-01-21 19:05
> Hi, i am trying drive mount on google colab and this happened as showned below: I have used google colab before with no problem. Please assist.
> 
> from google.colab import drive drive.mount('/content/drive')
> 
> ## Enter your authorization code:
> ··········
> ValueError Traceback (most recent call last) in () 1 from google.colab import drive ----> 2 drive.mount('/content/drive')
> 
> /usr/local/lib/python3.6/dist-packages/google/colab/drive.py in mount(mountpoint, force_remount, timeout_ms, use_metadata_server) 247 wrote_to_fifo = True 248 elif case == 5: --> 249 raise ValueError('mount failed: invalid oauth code') 250 if not wrote_to_fifo: 251 with open(fifo, 'w') as fifo_file:
> 
> ValueError: mount failed: invalid oauth code

It happens only when you don't give all the permissions to google colab when it asks for the permission to access your google drive after running this command

**Comment by noha-El-Haddad** [comment] 2022-01-22 01:48
We have the same problem ! it did work 2 days ago , is the problem global!

**Comment by gauravgund** [comment] 2022-02-04 07:48
The following code worked for me:

!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}
%cd /content
!mkdir drive
%cd drive
!mkdir MyDrive
%cd ..
%cd ..
!google-drive-ocamlfuse /content/drive/MyDrive
