### ISSUE TITLE
Malfunction of the copy button for authorizing google drive mount

### ISSUE THREAD

**Issue by starp0wer** [googlecolab/colabtools#1556] opened 2020-09-04 14:24 UTC
This issue is already reported on [stackoverflow](https://stackoverflow.com/questions/63723763/error-using-drive-mount-with-google-colab). Mounting Google drive to Colab kept failing since 24 hours ago due to malfunction of the auth code copy button. It can be resolved by manually copy and paste the authorization code instead of clicking on the copy button. If the copy button is used, then colab will throw a timeout error like the following:

`TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7fbb4bcb4eb8>`
`searcher: searcher_re:`
   ` 0: re.compile('google.colab.drive MOUNTED')`
`    1: re.compile('root@8b8902e0947a-a99c1728f0ea42b7945521b616ce7066: ')`
`    2: re.compile('(Go to this URL in a browser: https://.*)$')`
   ` 3: re.compile('Drive File Stream encountered a problem and has stopped')`
`    4: re.compile('drive EXITED')`

The issue still persists as of now. Can someone fix it?

**Comment by colaboratory-team** [comment] 2020-09-04 14:54
Duplicate of #1540.

**Closed by colaboratory-team** 2020-09-04 14:54 UTC
