### ISSUE TITLE
25GB RAM runtime crashes after filling up only around 13GB of RAM!!

### ISSUE THREAD

**Issue by naveen-kumar-123** [googlecolab/colabtools#1211] opened 2020-05-05 07:12 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I have been prompted to connect to higher RAM runtime after filling up and crashing my 12GB RAM (without GPU or TPU) runtime. So, i connect to 25GB runtime and this again crashed at same cell as the previous one which needs and uses exact amount of RAM, that is 13GB.

- Describe the expected behavior:
expected behavior is that my higher RAM runtime doesn't crash only when half of it is filled.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Google Chrome Version 81.0.4044.129 (Official Build) (64-bit) on windows 10 laptop

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):
https://drive.google.com/file/d/17WO_kVlVu_2GAM_HxE2KGCbDmL4sK0_C/view?usp=sharing
(this is the same notebook from https://github.com/awslabs/handwritten-text-recognition-for-apache-mxnet/blob/master/0_handwriting_ocr.ipynb)

**Comment by colaboratory-team** [comment] 2020-05-16 04:46
Duplicate of #1246

**Closed by colaboratory-team** 2020-05-16 04:46 UTC

**Comment by naveen-kumar-123** [comment] 2020-05-16 04:51
> Duplicate of #1246

No, this is not a duplicate of #1246. That issue is about not being able to connect to higher RAM runtime. and my issue is about session getting crashed without even filling the RAM in higher RAM session completely.

**Comment by firdauzcn007** [comment] 2023-08-25 09:54
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

Describe the current behavior:
I have been prompted to connect to higher RAM runtime and crashing. 
And now i have only 12GB RAM and can't change to higher RAM runtime anymore because i cant find toolbox to change it in "change runningtime type".

Describe the expected behavior:
i can freely change my RAM.

The web browser you are using (Chrome, Firefox, Safari, etc.):
Safari and Chrome
