### ISSUE TITLE
data file not uploaded correctly

### ISSUE THREAD

**Issue by maxxx580** [googlecolab/colabtools#436] opened 2019-02-20 22:22 UTC
As I upload a dataset to the runtime, it seems that only latter half of the file is actually uploaded. It also fails to open the file with the error shown below. Please review this issue. Thanks. 

The column it found is actually a line in the middle of the file. 
![screen shot 2019-02-20 at 5 16 52 pm](https://user-images.githubusercontent.com/8864669/53128801-af2bd380-3533-11e9-9ba4-8b1f3f13e8d3.png)
![screen shot 2019-02-20 at 5 18 20 pm](https://user-images.githubusercontent.com/8864669/53128872-e39f8f80-3533-11e9-90fd-ecfedf27d4c1.png)

Error when I attempted to open the file 
![screen shot 2019-02-20 at 5 17 15 pm](https://user-images.githubusercontent.com/8864669/53128895-f6b25f80-3533-11e9-8051-aa5b69b27298.png)

**Comment by colaboratory-team** [comment] 2019-02-21 18:15
Duplicate of #437

**Closed by colaboratory-team** 2019-02-21 18:15 UTC
