### ISSUE TITLE
colab networking issues

### ISSUE THREAD

**Issue by sangidileep** [googlecolab/colabtools#3718] opened 2023-05-27 15:03 UTC
I am unable to use Colab because of the below error I have tried using different browsers, and accounts even tried deleting browsing data and cookies, and also tried using incognito mode nothing works. please someone help me with this 

A network error occurred and the request could not be completed.
GapiError: A network error occurred and the request could not be completed.
    at NF.KB [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/60069d65d27ffb6abfb0ab565eeb81fc/external_polymer_binary.js:1519:2482)
    at new NF (https://ssl.gstatic.com/colaboratory-static/common/60069d65d27ffb6abfb0ab565eeb81fc/external_polymer_binary.js:1964:424)
    at jGa (https://ssl.gstatic.com/colaboratory-static/common/60069d65d27ffb6abfb0ab565eeb81fc/external_polymer_binary.js:2100:224)
    at ua.program_ (https://ssl.gstatic.com/colaboratory-static/common/60069d65d27ffb6abfb0ab565eeb81fc/external_polymer_binary.js:2114:389)
    at xa (https://ssl.gstatic.com/colaboratory-static/common/60069d65d27ffb6abfb0ab565eeb81fc/external_polymer_binary.js:21:57)
    at ua.throw_ (https://ssl.gstatic.com/colaboratory-static/common/60069d65d27ffb6abfb0ab565eeb81fc/external_polymer_binary.js:20:201)
    at laa.throw (https://ssl.gstatic.com/colaboratory-static/common/60069d65d27ffb6abfb0ab565eeb81fc/external_polymer_binary.js:22:90)
    at c (https://ssl.gstatic.com/colaboratory-static/common/60069d65d27ffb6abfb0ab565eeb81fc/external_polymer_binary.js:22:345)

**Comment by EvanWiederspan** [comment] 2023-06-01 16:41
We'll need more information to follow up on this bug report. Please submit feedback within Colab at Help > Send feedback.

**Comment by quintendewilde** [comment] 2023-06-01 21:24
That's the issue I can't see the error message because my browser is frozen on that page only...

**Comment by jadisayang** [comment] 2023-06-13 08:39
i can't make a new one or open any notebooks from my drive. 

A network error occurred and the request could not be completed.
GapiError: A network error occurred and the request could not be completed.
    at qG.nC [as constructor] (https://ssl.gstatic.com/colaboratory-static/common/a7dbc30dc1e88b1af99a821b1a669082/external_polymer_binary.js:1553:2482)
    at new qG (https://ssl.gstatic.com/colaboratory-static/common/a7dbc30dc1e88b1af99a821b1a669082/external_polymer_binary.js:1998:424)
    at UGa (https://ssl.gstatic.com/colaboratory-static/common/a7dbc30dc1e88b1af99a821b1a669082/external_polymer_binary.js:2134:224)
    at ua.program_ (https://ssl.gstatic.com/colaboratory-static/common/a7dbc30dc1e88b1af99a821b1a669082/external_polymer_binary.js:2148:389)
    at xa (https://ssl.gstatic.com/colaboratory-static/common/a7dbc30dc1e88b1af99a821b1a669082/external_polymer_binary.js:21:57)
    at ua.throw_ (https://ssl.gstatic.com/colaboratory-static/common/a7dbc30dc1e88b1af99a821b1a669082/external_polymer_binary.js:20:201)
    at laa.throw (https://ssl.gstatic.com/colaboratory-static/common/a7dbc30dc1e88b1af99a821b1a669082/external_polymer_binary.js:22:90)
    at c (https://ssl.gstatic.com/colaboratory-static/common/a7dbc30dc1e88b1af99a821b1a669082/external_polymer_binary.js:22:345)

**Comment by cperry-goog** [comment] 2023-06-29 16:58
looks like a dupe of #3775

**Closed by cperry-goog** 2023-06-29 16:58 UTC
Labels: bug, reply-needed
