### ISSUE TITLE
Colab is crashing and disconnecting

### ISSUE THREAD

**Issue by Souvik-Debnath** [googlecolab/colabtools#1962] opened 2021-04-17 14:11 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
It's disconnecting in between execution of the cell
- Describe the expected behavior:
It shall complete the tasks before disconnecting
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by cperry-goog** [comment] 2024-05-09 16:42
Closing due to staleness. File a new bug with reproducible steps if this is an issue.

**Closed by cperry-goog** 2024-05-09 16:42 UTC
