### ISSUE TITLE
Can not mount google drive.

### ISSUE THREAD

**Issue by alongstar518** [googlecolab/colabtools#1561] opened 2020-09-05 22:34 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Can not mount google drive.

Enter your authorization code:
··········
<pexpect.popen_spawn.PopenSpawn object at 0x7f80b089ebe0>
searcher: searcher_re:
    0: re.compile('google.colab.drive MOUNTED')
    1: re.compile('root@807517d03f50-964aebad1085457197c4de51d79312ec: ')
    2: re.compile('(Go to this URL in a browser: https://.*)$')
    3: re.compile('Drive File Stream encountered a problem and has stopped')
    4: re.compile('drive EXITED')
<pexpect.popen_spawn.PopenSpawn object at 0x7f80b089ebe0>
searcher: searcher_re:
    0: re.compile('google.colab.drive MOUNTED')
    1: re.compile('root@807517d03f50-964aebad1085457197c4de51d79312ec: ')
    2: re.compile('(Go to this URL in a browser: https://.*)$')
    3: re.compile('Drive File Stream encountered a problem and has stopped')
    4: re.compile('drive EXITED')
- Describe the expected behavior:
Mount successful

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment] 2020-09-05 23:20
The copy button is broken on the oauth2 page; just select the text and copy manually.

Duplicate of #1540.

**Closed by craigcitro** 2020-09-05 23:20 UTC
