### ISSUE TITLE
Scrolling up/down: jumping back to code block

### ISSUE THREAD

**Issue by MorphineBear** [googlecolab/colabtools#2455] opened 2021-11-24 05:11 UTC
**Describe the current behavior**

- Unsure if this is normal behavior of Google Colab, but the page will jump back to a certain point, like to a  specific code block repeatedly when I scroll up or down. 

- Other times, I get stuck between two "scrolls" and Colab attempts to show both screens at the same time.

**Describe the expected behavior**
I expect a smooth scroll up or down the page.

**What web browser you are using**
Firefox 94.0.2

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

I'd prefer not to share this notebook publicly as it is personal-ish but can try sharing privately. Google Colab is the only site where I've experienced this scroll issue. Notebook is about 26 KB. 

Tried clearing outputs but still experiencing problem.

Edit: Made a quick video: https://youtu.be/kiYgLVSfzqY

Wonder if [this](https://github.com/googlecolab/colabtools/issues/1394#issuecomment-659117725) may be related.

**Comment by blois** [comment] 2021-11-24 05:46
Does this repro in Chrome or in private browsing? There was a recent performance change which could potentially cause this sort of behavior though it's been on for a few weeks now and haven't had any reports.

**Comment by MorphineBear** [comment] 2021-11-24 06:01
> Does this repro in Chrome or in private browsing?

When I scroll in Chrome, it makes a one big scroll (I think) at the end of each code block. Can make another video of that if needed. However, it looks more manageable and does not have the problem I have in Firefox where it pulls me back up the page.

In Firefox private browsing, I do have the same issue. I read in a different thread that an extension might be responsible? Will have to check tomorrow as it's getting late to do so today.

**Comment by MorphineBear** [comment] 2021-11-24 16:32
What it looks like is that when I click in a code cell, I can't continue scrolling past the output (or where the output would be if executed) of the **next** cell below it. 

The beginning of the output box cannot reach the top bar (+Code +Text ... RAM/DISK usage).

**Comment by quental96** [comment] 2021-11-25 15:10
I am getting a similar behavior on Chrome. I've played around with the bug on different notebooks and it doesn't seem to be related with cell output or scrolling position relative to the cell. For me the jumping seems completely random and erratic.

**Comment by dantrag** [comment] 2021-11-25 16:48
Same on current Chrome (96.0.4664.45). I see these jumps whenever a new cell enters the view while scrolling.

**Comment by JonOnEarth** [comment] 2021-11-25 16:54
Yep, same issue on Chrome.

**Comment by Germandev55** [comment] 2021-11-25 18:09
A similar problem. Tried it on different browsers: Chrome, Firefox, Yandex browser and on different OS: Windows 10 and Ubuntu 20.04

**Comment by EMplIFil** [comment] 2021-11-25 21:38
I've noticed a similar issue on Chrome 95.0.4638.69 (using MacOS).

It's like a weird "snap" feature but never snaps to the block of code I actually intended on seeing.

Furthermore, around this time I also noticed the outputs are not rendering. They appear briefly, then disappear. You can see the outputs again after trying to highlight the text in the output block. Not sure if related to the scrolling issue.

**Comment by recycletechno** [comment] 2021-11-26 10:12
Same with me on Chrome 96.0.4664.45(64) Win10. It's beginning to be very annoying while looking around for the little pieces of code though the notebook. It's rather acceptable when cells are short, but when cells are 3-4 monitor heights - its not good

**Comment by DavidHarar** [comment] 2021-11-26 18:42
Same here, but apparently it is something of the last couple of weeks (at least for me). It happened when I used Win 11, Ubuntu, and MacOS.

**Comment by rondinellimorais** [comment] 2021-11-27 00:52
Same bug here! I made a video https://youtu.be/CxgZ-_0wh9E

It's jumping when I scroll smoothly, fix it please.

It seems like this only happens when there's a cell running and you're inspecting the rest of the code.

Chrome version 96.0.4664.55 (x86_64)
macOs Big Sur

**Comment by artoowang** [comment] 2021-11-27 14:11
Same here, and I have a way to reproduce the issue quite reliably:
(At least on my macbook with Chrome 96.0.4664.55. Curious to see if others can also try repro it with the instructions below.)

1. Open https://colab.research.google.com/github/artoowang/ray_tracer_colab/blob/main/Ray_Tracer.ipynb
2. Scroll to the code cell under "ray_tracer_wrapper.pyx", and select and highlight a random line in the cell.
3. Scroll to the bottom of the notebook, **and click on another cell**
4. Slowly scroll up to the "ray_tracer_wrapper.pyx" cell until you see the highlight line you selected
5. Scroll to the bottom of the notebook again
6. Slowly scroll up to the "ray_tracer_wrapper.pyx" cell again. This time as soon as you see the cell, the notebook jumps.

**Comment by Estorva** [comment] 2021-11-28 18:45
I also have a similar issue when I scroll into a cell that is not currently in edit mode, the page jumps to the last cursor position I left in that cell. Lets say you have two cells, each with 100 lines of code:

1. You click on line 50 in cell 2. Now Colab remembers that your cursor position in that cell.
2. Now click on anywhere in cell 1 so that cell 2 is no longer in edit mode.
3. Scroll back to cell 2. Colab now tries to bring you to line 50 where your cursor was.

I am running Colab on Chrome 96.0.4664.55 (arm64) and macOS Big Sur 11.6.

**Comment by dstekol** [comment] 2021-11-28 22:14
Same issues on Chrome 96.0.4664.45
Scrolling makes sudden jumps to specific parts of certain cells instead of moving smoothly (like a weird snap-to feature except it doesn't snap to things I want to see).
Also, as mentioned above (may be a separate issue): outputs disappear when cell is done executing, and only reappears if you try to select.

**Comment by bwilder95** [comment] 2021-11-28 22:56
I am also having this issue with Firefox Version 94 on Linux. I want to inspect my outputs but Google Colab keeps scrolling to the next code block.

**Comment by Bressack** [comment] 2021-11-29 09:13
Same problem. For me it happens when I scroll up or down quickly, sometimes the problem goes away when I edit a cell that crashed on the last run.

**Comment by MARABOTTO** [comment] 2021-11-29 09:38
+1. Same problem. Fix it please.

**Comment by Vikdemen** [comment] 2021-11-29 14:24
Had the same issue, started googling, found that thread.
Currently editing large notebooks in colab is extremely annoying.
Waiting for the fix.

**Comment by vslaykovsky** [comment] 2021-11-29 19:05
+1 same for me

**Comment by craigcitro** [comment] 2021-11-29 19:10
Thanks for all the reports! We think we have a fix for this landed, and it should roll out to everyone tomorrow; one of us will respond once it's live, in which case a page refresh should have everything back in order.

The "outputs might disappear until you click" issue seems to be separate; filed #2467.

**Comment by blois** [comment] 2021-11-29 20:44
A temporary fix may be in right now.

**Comment by MorphineBear** [comment] 2021-11-29 20:50
> Thanks for all the reports! We think we have a fix for this landed, and it should roll out to everyone tomorrow; one of us will respond once it's live, in which case a page refresh should have everything back in order.
> 
> The "outputs might disappear until you click" issue seems to be separate; filed #2467.



> A temporary fix may be in right now.

Thanks, will try it later.

**Comment by jaytoone** [comment] 2021-12-01 00:03
it works now, thanks

**Closed** 2021-12-01 18:56 UTC
Labels: bug

**Comment by quental96** [comment] 2021-12-09 10:37
I don't know why this was closed, the problem is still there for me.

**Comment by blois** [comment] 2021-12-09 16:20
There is one remaining issue with collapsed code folding, fix will be arriving shortly.

**Comment by GodotMisogi** [comment] 2023-12-14 07:54
Bump. I am currently facing this issue.

**Comment by Xses-1** [comment] 2024-03-15 14:36
Still broken. Firefox 123.0

**Comment by Rhitabrat** [comment] 2024-07-07 17:47
The scrolling issue persists. Firefox 127.0.2.

**Comment by jjhartmann** [comment] 2024-11-28 00:01
This is still broken. Chrome Version 131.0.6778.86

**Comment by akilkarthikeyan** [comment] 2025-03-08 00:43
Still broken, why is this issue closed?

**Comment by Xses-1** [comment] 2025-03-08 08:50
@akilkarthikeyan because f* us, that's why - crappy UI by design.
