### ISSUE TITLE
mdir models da error ,, arreglar este apartado da error y no se puede colorear

### ISSUE THREAD

**Issue by coloreando9999** [googlecolab/colabtools#3904] opened 2023-08-06 21:29 UTC
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by coloreando9999** [comment] 2023-08-06 21:31
/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet101_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet101-63fe2227.pth" to /root/.cache/torch/hub/checkpoints/resnet101-63fe2227.pth
100%|██████████| 171M/171M [00:02<00:00, 76.7MB/s]
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
[<ipython-input-7-81c07a854ecc>](https://localhost:8080/#) in <cell line: 1>()
----> 1 colorizer = get_video_colorizer()
MKDIR  MODELS GIVE ERROR SOLUTION PLEASE

**Comment by colaboratory-team** [comment] 2023-08-07 20:13
Duplicate of https://github.com/googlecolab/colabtools/issues/3905

**Closed by colaboratory-team** 2023-08-07 20:13 UTC
Labels: bug
