### ISSUE TITLE
Drive unmounts after a min of running a fully loaded cell

### ISSUE THREAD

**Issue by NaotoEnjoyer** [googlecolab/colabtools#4778] opened 2024-08-14 16:38 UTC
hello, sry for bothering but i think i may be having issue with drive rn, see, when i try to start my session it load fine, mounts drive as usual and all, but when my cell is fully loaded, for some reason after a min or so drive folder just unmounts..
![image](https://github.com/user-attachments/assets/72890741-cc7d-4d47-8032-72f24e6dffee)
and when i try to mount it one more time while session is on, it just gives me this error..
![image](https://github.com/user-attachments/assets/6708b7e7-153c-4164-94a2-a21614f50440)
pls how do i fix this its so sad :'(
p.s yes i use force remount too

**Comment by AurekC** [comment] 2024-08-14 16:52
I am facing the same issue

**Comment by EvanWiederspan** [comment] 2024-08-15 16:48
Looks to be a duplicate of https://github.com/googlecolab/colabtools/issues/4773

**Closed by EvanWiederspan** 2024-08-15 16:48 UTC
Labels: bug
