### ISSUE TITLE
Failing to open the gRPC Driver

### ISSUE THREAD

**Issue by dbubbins87** [googlecolab/colabtools#3513] opened 2023-03-17 19:15 UTC
**Describe the current behavior**
Whenever I try to connect to my Colab instance's TPU, I get this.

2023-03-17 19:08:36.468458: E external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/grpc_tpu_driver.cc:1070] Failed to open the gRPC driver: 4: Deadline Exceeded: 
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "/content/KoboldAI-Client/aiserver.py", line 10284, in <module>
    load_model(initial_load=True)
  File "/content/KoboldAI-Client/aiserver.py", line 2807, in load_model
    tpu_mtj_backend.load_model(vars.custmodpth, hf_checkpoint=vars.model not in ("TPUMeshTransformerGPTJ", "TPUMeshTransformerGPTNeoX") and vars.use_colab_tpu, **vars.modelconfig)
  File "/content/KoboldAI-Client/tpu_mtj_backend.py", line 1194, in load_model
    devices = np.array(jax.devices()[:cores_per_replica]).reshape(mesh_shape)
  File "/usr/local/lib/python3.9/dist-packages/jax/_src/lib/xla_bridge.py", line 314, in devices
    return get_backend(backend).devices()
  File "/usr/local/lib/python3.9/dist-packages/jax/_src/lib/xla_bridge.py", line 258, in get_backend
    return _get_backend_uncached(platform)
  File "/usr/local/lib/python3.9/dist-packages/jax/_src/lib/xla_bridge.py", line 248, in _get_backend_uncached
    raise RuntimeError(f"Requested backend {platform}, but it failed "
RuntimeError: Requested backend tpu_driver, but it failed to initialize: DEADLINE_EXCEEDED: Failed to connect to remote server at address: grpc://10.121.241.202:8470. Error from gRPC: Deadline Exceeded.

**Describe the expected behavior**
I expect it to open the gRPC driver.

**What web browser you are using**
Firefox AND Chrome

**Additional context**
https://colab.research.google.com/github/KoboldAI/KoboldAI-Client/blob/main/colab/TPU.ipynb

**Comment by metrizable** [comment] 2023-03-23 16:55
@dbubbins87 Thanks for filing the issue. This [comment](https://github.com/googlecolab/colabtools/issues/3405#issuecomment-1451048147) from a related issue is relevant. Resolving as duplicate of #3405.

**Closed by metrizable** 2023-03-23 16:55 UTC
Labels: bug
