### ISSUE TITLE
Unable to enter auth code for mounting google drive

### ISSUE THREAD

**Issue by anurags397** [googlecolab/colabtools#424] opened 2019-02-12 08:17 UTC
Browser: Firefox 65
OS: Ubuntu 18.04 LTS

The input to enter the auth code either doesn't work (i.e. Return button doesn't work on that password input) or it just keeps running until timeout. 

![screenshot from 2019-02-12 13-28-02](https://user-images.githubusercontent.com/19914954/52620905-ebc05500-2ecb-11e9-8274-02f28459c10a.png)
Stuck forever.

No response what-so-ever. It used to work totally fine.
I saw issue #382 but unlike their drive, my drive only has 5 files/folders in the "root" Drive folder.

Upon Interruption, it throws the following traceback:
```
KeyboardInterrupt                         Traceback (most recent call last)

<ipython-input-4-4996ee3d8d09> in <module>()
      1 from google.colab import drive
----> 2 drive.mount('/content/gdrive')

/usr/local/lib/python3.6/dist-packages/google/colab/drive.py in mount(mountpoint, force_remount)
    135       # Not already authorized, so do the authorization dance.
    136       auth_prompt = d.match.group(1) + '\n\nEnter your authorization code:\n'
--> 137       d.send(_getpass.getpass(auth_prompt) + '\n')
    138   d.sendcontrol('z')
    139   d.expect(u'Stopped')
```

**Comment by colaboratory-team** [comment] 2019-02-12 16:41
Sorry for the trouble. You can obtain some additional logging to help diagnose by adjusting the invocation as follows:

```
from google.colab import drive
drive.mount._DEBUG = True
drive.mount('/content/drive', force_remount=True)
```

**Comment by anurags397** [comment] 2019-02-13 06:53
Thanks. I did add the debug mode and checked and this is what I got:

```
2019-02-13T06:07:09.114ZI [111111] drive_fs.cc:161:LogSystemConfig OS: 4.14.79+ #1 SMP Wed Dec 19 21:19:13 PST 2018
2019-02-13T06:07:09.114ZI [111111] drive_fs.cc:168:LogSystemConfig Architecture: 64-bit
2019-02-13T06:07:09.114ZI [111111] drive_fs.cc:177:LogSystemConfig Total RAM: 12 GiB
2019-02-13T06:07:09.114ZI [111111] drive_fs.cc:193:LogSystemConfig Disk space: 361.13 GB free / 384.69 GB total
2019-02-13T06:07:09.114ZI [111111] drive_fs.cc:209:LogSystemConfig Timezone: UTC+0000 (UTC)
2019-02-13T06:07:09.114ZI [111111] client.cc:1497:LoadPreferencesFromDisk preferences: {
local_machine_defaults {
}
local_user {
}
local_machine_override {
}
combined_preferences {
}
}
2019-02-13T06:07:09.115ZI [111111] client.cc:1499:LoadPreferencesFromDisk effective_preferences: {
mount_point_path: "/content/drive"
content_cache_base_path: "/root/.config/Google/DriveFS"
trusted_root_certs_file_path: "/opt/google/drive/roots.pem"
disable_ssl_validation: false
disable_crl_check: false
direct_connection: false
force_spotlight: false
force_browser_auth: false
disable_realtime_presence: false
do_not_show_dialogs {
  mount_point_changed: false
  confirm_shared_folder_move_in: false
  confirm_shared_folder_move_out: false
  confirm_td_file_move_out: false
  confirm_move_to_untrusted_td: false
  warning_move_to_untrusted_td: false
  warning_td_file_move_out: false
  warning_shared_folder_move_in: false
  warning_shared_folder_move_out: false
}
autostart_on_login: true
}
```
**2019-02-13T06:07:09.115ZE [111111] ipc_socket_posix.cc:222:Connect Failed to connect to domain socket: Connection refused**
```
2019-02-13T06:07:10.006ZI [000000] credential_store.cc:55:InitCredential Credential initUser: 
Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=abc
Enter your authorization code: 2019-02-13T06:07:10.006ZI [000000] drive_cloud_store.cc:152:CreateDriveCloudStoreSync Using Drive API v2.
2019-02-13T06:07:10.006ZI [000000] curl_api.cc:1324:Create SSL verification with CAcerts path: /opt/google/drive/roots.pem
2019-02-13T06:07:10.006ZI [000000] curl_api.cc:593:Init Using cacerts from /opt/google/drive/roots.pem
2019-02-13T06:07:10.006ZI [000000] credential_store.cc:55:InitCredential Credential initUser: 

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=abc

Enter your authorization code:
```
After pasting the code into the textbox, it doesn't seem to perform any action. 

I'm assuming that the code in bold is what is causing the problem.

**Comment by colaboratory-team** [comment] 2019-02-13 15:51
Thanks for the debug logs. We'll take a look and keep this issue updated.
b/124365834

**Comment by colaboratory-team** [comment] 2019-02-13 16:43
@anurags397 can you try
```
import getpass
print(getpass.getpass())
```
and type anything into the text box and press enter; does it print what you typed back at you or keep spinning?

Once you do the above, please Help->Send feedback and include in the message #b124365834 so we can see your browser details etc.

Finally, does this reproduce for you in an incognito window?

**Comment by ManelBoucenna** [comment] 2019-02-14 03:20
Hi @colaboratory-team I am facing exactly the same issue. I did what you said before but nothing happens it keeps spinning (same thing in an incognito window).  What could be the possible cause?
![screenshot from 2019-02-13 22-16-52](https://user-images.githubusercontent.com/27954195/52760336-24038880-2fdd-11e9-8fca-6edfc7dd71c9.png)

**Comment by colaboratory-team** [comment] 2019-02-14 07:28
@ManelBoucenna After you reproduce the getpass failure, please Help->Send feedback and include in the message #b124365834 so we can see your browser details etc. Also please paste anything that looks like an error from the DevTools JS console. Thanks!

**Comment by colaboratory-team** [comment] 2019-03-02 07:58
Closing issue pending replies to requests above of anyone still seeing the issue.

**Closed by colaboratory-team** 2019-03-02 07:58 UTC

**Comment by colaboratory-team** [comment] 2019-03-07 20:26
@yacinedexter thanks for sending feedback; I'm not seeing any obvious smoking guns.
Does typing "hello" and hitting enter also do nothing when you run 
```
import getpass
getpass.getpass()
```
?  Can you confirm what you see if you "Reset all runtimes" first from the Runtime menu? How about in a Private Window in firefox and in an Incognito window in chrome?

**Comment by yacinedexter** [comment] 2019-03-07 20:52
-Yes  typing "hello" and hitting enter also do nothing when I run getpass.
-Nothing happened when i "Reset all runtimes" just it stop running the command, then i run it again same issue.
-In private firefox it's the same issue also.

**Comment by yacinedexter** [comment] 2019-03-07 20:59
I just tried from chrome and everything is fine, it looks that the issue is related to firefox. thanks for your help

**Comment by colaboratory-team** [comment] 2019-03-07 20:59
Thanks for confirming.
Can you describe your physical computer setup?  Brands/model/versions of keyboard, and intermediates between it and your computer, and computer?  Do you have any non-standard keyboard mappings in effect? What is your enter key labeled? (some keyboards have an "enter" and a "return" on different keys, and so on). Do you still see the same (non-)behavior with ctrl-enter, shift-enter, and alt-enter when focus is in the getpass input box?

(I'm really grasping at straws here because this works fine for me and for our automated tests in firefox, too, and for most of our users)

**Comment by yacinedexter** [comment] 2019-03-07 21:12
Keyboard : microsoft wiredkeboard600 directily connected to desktop via usb
computer desktop CIARAtech i7
I already tried ctrl-enter, shift-enter, and alt-enter and i dont think it's the issue since it works before with the same hardware and it works on chrome actually with enter key normally.
anyway i will switch to chrome, thanks for helping.

**Comment by colaboratory-team** [comment] 2019-03-07 23:36
@yacinedexter thanks for confirming. If you wouldn't mind, I'd love for you to run another check to hopefully narrow this down (even though switching to Chrome works for you it'd be nice to know the root cause of this issue, if not fix it). In the firefox that exhibits the problem, execute a cell containing:
```
from google.colab import output
print('hello\n\ngoodbye')
output.eval_js('document.addEventListener("keydown", function(event) {  document.body.innerText += event.which + ":" + event.keyCode + ":" + event.key;})')
```
then click the mouse in the empty line between "hello" and "goodbye" and hit the problematic enter key once. A bit of extra output should be emitted ot the output area of the codecell (below "goodbye"). Can you tell me what you see there?

**Comment by yacinedexter** [comment] 2019-03-08 16:10
![screenshot from 2019-03-08 11-12-14](https://user-images.githubusercontent.com/25806178/54040203-cce37480-4192-11e9-8427-3e5d31a7b5d0.png)

**Comment by colaboratory-team** [comment] 2019-03-08 17:53
Darn, that doesn't shed light (is the same as in working setups). 
To confirm, JS console says nothing during the getpass() repro?

**Comment by yacinedexter** [comment] 2019-03-08 19:15
![screenshot from 2019-03-08 14-18-39](https://user-images.githubusercontent.com/25806178/54050239-adf1dc00-41ac-11e9-9af2-70bc7930552f.png)

**Comment by colaboratory-team** [comment] 2019-03-08 19:26
`Invalid chrome URI: /` is likely an indicator of the issue; can you list the Add-Ons you have installed in firefox? Would also be worth trying to disable all of them and seeing if that changes things (though, obvs., if that helps IWBN to know which of them was the culprit for future travelers).

**Comment by yacinedexter** [comment] 2019-03-08 19:30
I have no add-on, they are all disabled :(

**Comment by yacinedexter** [comment] 2019-03-08 19:33
the invalid chrome uri happen when i put the mouse into the field and before i past the uri, and when i hit enter nothing happen

**Comment by colaboratory-team** [comment] 2019-03-08 20:33
Thanks for checking. The only other thing I'm thinking of is maybe a browser pref is the difference. 
Can you try repro'ing in a new firefox profile (with profile/account sync disabled)?

**Comment by yacinedexter** [comment] 2019-03-08 21:24
it works, when i disconnect my profile and restarted the browser.
then i signed in again with my mozila profile and it works also.
so i am not sure what really fixed it, either the profile or restarting the browser.
anyway thank you for your help.

**Comment by lusiahli** [comment] 2019-07-18 19:35
Hi @colaboratory-team Sorry to bother you. I'm seeing the same error and unable to enter auth code for mounting google drive. Please help!

**Comment by blois** [comment] 2020-09-03 04:22
See https://github.com/googlecolab/colabtools/issues/1540

**Comment by tokenflow** [comment] 2020-09-04 06:35
I solved it by copy the auth code instead of clicking the copy button; it seems java-script compatibility issue within the code of the copy button.
![Screen Shot 2020-09-04 at 10 16 24 AM](https://user-images.githubusercontent.com/8538953/92207433-41879400-ee9a-11ea-8fdc-46be5ec55f3e.png)

**Comment by dmzlingyin** [comment] 2020-09-04 13:16
> I solved it by copy the auth code instead of clicking the copy button; it seems java-script compatibility issue within the code of the copy button.
> ![Screen Shot 2020-09-04 at 10 16 24 AM](https://user-images.githubusercontent.com/8538953/92207433-41879400-ee9a-11ea-8fdc-46be5ec55f3e.png)

Wow! Thanks bro. That is the problem, I solved it.

**Comment by Aekpreya** [comment] 2020-09-08 11:55
> I solved it by copy the auth code instead of clicking the copy button; it seems java-script compatibility issue within the code of the copy button.
> ![Screen Shot 2020-09-04 at 10 16 24 AM](https://user-images.githubusercontent.com/8538953/92207433-41879400-ee9a-11ea-8fdc-46be5ec55f3e.png)

thank you 👍
