### ISSUE TITLE
Your Jupyter Notebook is too old. Please upgrade to version 6 or higher.

### ISSUE THREAD

**Issue by RushnaiwalaTaki** [googlecolab/colabtools#1917] opened 2021-03-21 16:04 UTC
!pip install git+https://github.com/OpenMined/PySyft@dev#egg=syft
import syft as sy

- It show me the Error while importing **syft** Library.

/usr/local/lib/python3.7/dist-packages/syft/core/common/environment.py in <module>()
     17     if NOTEBOOK_VERSION < version.parse("6.0.0"):
     18         raise Exception(
---> 19             "Your Jupyter Notebook is too old. Please upgrade to version 6 or higher."
     20         )
     21 except NameError:

Exception: Your Jupyter Notebook is too old. Please upgrade to version 6 or higher.

**Comment by craigcitro** [comment] 2021-03-21 19:41
duplicate of #1582

**Closed by craigcitro** 2021-03-21 19:41 UTC
