### ISSUE TITLE
Resolving library installation issues

### ISSUE THREAD

**Issue by pagakarthik** [googlecolab/colabtools#8] opened 2017-12-23 06:36 UTC
A previous run-time error continues to sustain when attempting to import a different library.

Particularly when testing installation of ROS framework -
 `!apt-get install ros-indigo-desktop-full`
Its obvious this wouldn't work. But I was curious about the result. 

Result
> E: Malformed entry 1 in list file /etc/apt/sources.list.d/ros-latest.list (Component)
> E: The list of sources could not be read.

The point being post this attempt, any other attempt to install a valid library results in the similar error. 
`!apt-get -qq install -y libarchive-dev && pip install -q -U libarchive`
`import libarchive`

Result:

> E: Malformed entry 1 in list file /etc/apt/sources.list.d/ros-latest.list (Component)
> E: The list of sources could not be read.
> E: Malformed entry 1 in list file /etc/apt/sources.list.d/ros-latest.list (Component)
> E: The list of sources could not be read.
ImportErrorTraceback (most recent call last)
<ipython-input-1-f3250392652e> in <module>()
      1 get_ipython().system(u'apt-get -qq install -y libarchive-dev && pip install -q -U libarchive')
----> 2 import libarchive
ImportError: No module named libarchive
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.
Examples of installing some common dependencies can be found at:
https://colab.research.google.com/notebook#fileId=/v2/external/notebooks/snippets/importing_libraries.ipynb

Here's the interesting observation, 
When the libarchive installtion is attempted in a different working directory (different Google drive), it executes as suggested in the tutorial. 

I am suspecting the cause to be in the build environment.

**Comment by craigcitro** [comment] 2017-12-27 17:45
I think this is all working as intended:

* a bad entry in `/etc/apt/sources.list.d` will lead to further failures to install new packages; the usual remedy here is to just let your machine idle out and we'll reassign you a fresh VM

* using a different account (which is what I assume you mean by "different Google Drive") will give you a different VM without the erroneous apt entry.

**Closed by craigcitro** 2017-12-27 17:45 UTC
