### ISSUE TITLE
Mounting drive timeout

### ISSUE THREAD

**Issue by frunkad** [googlecolab/colabtools#1551] opened 2020-09-04 04:46 UTC
- Describe the current behavior: While connecting to drive via `drive.mount`, it timeouts. I tried with 4 different Google/GSuite Accounts, one of which was entirely new with just 1 file and 1 folder.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome 85 on Linux Mint

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1scDg-7meUS_SyAwFH07hJtScX42cfTXd?usp=sharing

Tried resetting the runtime multiple times - no success there.

**Comment by craigcitro** [comment] 2020-09-04 05:35
Try manually selecting the code to copy-paste rather than using the "copy" button.

Duplicate of #1540

**Closed by craigcitro** 2020-09-04 05:35 UTC
