### ISSUE TITLE
Sort Git Repository List

### ISSUE THREAD

**Issue by sirinath** [googlecolab/colabtools#1988] opened 2021-04-30 12:02 UTC
Please sort the repo list when showing.

**Comment by blois** [comment] 2021-05-13 21:17
Note: example URL showing the issue is https://colab.research.google.com/github/tensorflow/, with the repository selector being unsorted.

**Comment by katlyn-edwards** [comment] 2021-05-20 21:59
The fix has been submitted for this, and should be live by tomorrow afternoon. Thanks for the report!

**Closed by katlyn-edwards** 2021-05-20 21:59 UTC
Labels: feature
