### ISSUE TITLE
Failed to fetch TypeError: Failed to fetch

### ISSUE THREAD

**Issue by abeyzamzam** [googlecolab/colabtools#4845] opened 2024-09-16 09:11 UTC
**Describe the current behavior**
A clear and concise explanation of what is currently happening.
Can't download the process file
**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
Output: 
Failed to fetch
TypeError: Failed to fetch
**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome
**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by cperry-goog** [comment] 2024-09-19 16:36
can you share a minimal reproducible notebook that triggers this?

**Comment by karlkran** [comment] 2024-09-27 07:50
Below is a sample notebook to reproduce bug where bigger files cannot be downloaded, getting this:

Error download failed pop-up window
Failed to fetch
TypeError: Failed to fetch

Big files triggering bug:

mnist_test.csv 17.44M
mnist_train_small.csv 34.83M

All other files in folder sample_data do not trigger bug.



https://colab.research.google.com/drive/1JVCO_AmmGLlMhEatjO4cr2gHtuEOdk3-?usp=sharing

**Comment by cperry-goog** [comment] 2024-10-03 16:42
Looks like it's working? My suspicion is there are issues with the source you're pulling from. Closing, please open a new bug if you spot this again.

**Closed by cperry-goog** 2024-10-03 16:42 UTC
Labels: bug, reply-needed
