### ISSUE TITLE
As a Colab Pro user can't use any GPU

### ISSUE THREAD

**Issue by rafaeling** [googlecolab/colabtools#1952] opened 2021-04-09 09:27 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

I get the GPU assigned 
![image](https://user-images.githubusercontent.com/8845460/114159801-7bd07c80-9926-11eb-93dc-53cadaa08d43.png)

But never works, after one hour waiting
![image](https://user-images.githubusercontent.com/8845460/114159742-678c7f80-9926-11eb-8519-1e1ad99724a1.png)

**Comment by cperry-goog** [comment] 2024-05-09 16:42
Closing due to staleness. File a new bug with reproducible steps if this is an issue.

**Closed by cperry-goog** 2024-05-09 16:42 UTC
