### ISSUE TITLE
AttributeError: module 'tensorflow_core.compat.v2' has no attribute '__internal__'

### ISSUE THREAD

**Issue by limzh123** [googlecolab/colabtools#2044] opened 2021-05-26 11:13 UTC
Hi, I have encountered a problem with when load segmentation model.

/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py in populate_deserializable_objects()
     47 
     48   LOCAL.ALL_OBJECTS = {}
---> 49   LOCAL.GENERATED_WITH_V2 = tf.__internal__.tf2.enabled()
     50 
     51   # Compatibility aliases (need to exist in both V1 and V2).

AttributeError: module 'tensorflow_core.compat.v2' has no attribute '__internal__'

**Comment by huyhoangpjn** [comment] 2021-05-26 15:21
I have got this bug too.

**Comment by duynguyendtvt** [comment] 2021-05-26 15:29
Have a same bug today. Didn't happen in yesterday 
![bug](https://user-images.githubusercontent.com/84862115/119687678-98daf380-be71-11eb-97be-6661ec50f9a6.png)

**Comment by HRishabh95** [comment] 2021-05-26 17:53
I have the same bug and it started coming recently, and I didnt change any code.

**Comment by PamDev0** [comment] 2021-05-26 20:21
Same here. Started yesterday.

Using TensorFlow backend.

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-3-e89862ff62f3> in <module>()
----> 1 import keras
      2 import keras.backend as K
      3 import keras.layers as KL
      4 import keras.engine as KE
      5 import keras.models as KM

6 frames

/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/util/module_wrapper.py in __getattr__(self, name)
    191   def __getattr__(self, name):
    192     try:
--> 193       attr = getattr(self._tfmw_wrapped_module, name)
    194     except AttributeError:
    195       if not self._tfmw_public_apis:

AttributeError: module 'tensorflow._api.v1.compat.v2' has no attribute '__internal__'

**Comment by colaboratory-team** [comment] 2021-05-26 20:34
Recently colab was upgraded to TF 2.5.0, forcing an upgrade to keras-nightly 2.5.0.dev2021032900.

A minimal reproduction recipe (starting from Runtime -> Factory reset runtime) of the issue being reported here would help narrow down a culprit/fix.

**Comment by PamDev0** [comment] 2021-05-26 21:01
Steps to reproduce:

! pip install tensorflow==1.15.0
! pip install keras==2.0.8

import keras

**Comment by bhsnada** [comment] 2021-05-26 21:08
> Steps to reproduce:
> 
> ```
> ! pip install tensorflow==1.15.0
> ! pip install keras==2.0.8
> 
> import keras
> ```

Thanks, but It doesn't work with me.

**Comment by PamDev0** [comment] 2021-05-26 21:57
hi@bhsnada, these are steps to reproduce my error.

**Comment by colaboratory-team** [comment] 2021-05-26 22:25
@PamDev0 per our last comment above, the recent change affecting you is the install of keras-nightly, which is incompatible with your `!pip install` of non-nightly `keras`. Adding `!pip uninstall keras-nightly` before `import keras` makes the error go away in your repro recipe.

**Comment by PamDev0** [comment] 2021-05-26 22:52
@colaboratory-team Thank you so much, worked for me!

**Comment by limzh123** [comment] 2021-05-27 01:59
@colaboratory-team 

Hi, this is the problem when I encountered

Using TensorFlow backend.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-929b109e7b26> in <module>()
      1 import tensorflow as tf
----> 2 import segmentation_models as sm
      3 BACKBONE = 'resnet34'
      4 preprocess_input = sm.get_preprocessing(BACKBONE)

10 frames
/usr/local/lib/python3.7/dist-packages/keras/initializers/__init__.py in populate_deserializable_objects()
     47 
     48   LOCAL.ALL_OBJECTS = {}
---> 49   LOCAL.GENERATED_WITH_V2 = tf.__internal__.tf2.enabled()
     50 
     51   # Compatibility aliases (need to exist in both V1 and V2).

AttributeError: module 'tensorflow_core.compat.v2' has no attribute '__internal__'

**Comment by Anupama74** [comment] 2021-05-27 04:13
Worked for me too

**Comment by limzh123** [comment] 2021-05-27 05:11
> @PamDev0 per our last comment above, the recent change affecting you is the install of keras-nightly, which is incompatible with your `!pip install` of non-nightly `keras`. Adding `!pip uninstall keras-nightly` before `import keras` makes the error go away in your repro recipe.

Hi, I have tried this '!pip uninstall keras-nightly'
The error (AttributeError: module 'tensorflow_core.compat.v2' has no attribute 'internal') is gone....

But When I run 
model = sm.Unet(BACKBONE, encoder_weights='imagenet')
This error appeared (AttributeError: 'str' object has no attribute 'decode')

**Comment by bhsnada** [comment] 2021-05-27 07:00
@colaboratory-team  thank you worked for me

**Comment by chulminkw** [comment] 2021-05-27 12:09
I have the same issue. 

!pip install tensorflow==2.3.0
!pip install keras==2.4

This brought  'AttributeError: module 'tensorflow._api.v1.compat.v2' has no attribute 'internal' message. 

!pip uninstall --yes keras-nightly comand makes the error message go away but keras doesn't seem to work properly. 

Many keras modules in my program give other unexpected error message after uninstall keras-nightly.   
Even this simple keras version check line doesn't work properly. 

import tensorflow as tf
import keras

print(tf.__version__)
print(keras.__version__)

### tensorflow version: 2.3.0

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-7-140fc05b61d7> in <module>()
      5 
      6 print('### tensorflow version:', tf.__version__)
----> 7 print('### keras version:', keras.__version__)
      8 
      9 

AttributeError: module 'keras' has no attribute '__version__'

**Comment by colaboratory-team** [comment] 2021-05-27 23:38
Duplicate of https://github.com/tensorflow/tensorflow/issues/49823

**Closed by colaboratory-team** 2021-05-27 23:38 UTC
Labels: bug

**Comment by SiddarthSamdani** [comment] 2021-07-27 03:50
Getting this error...

AttributeError                            Traceback (most recent call last)
<ipython-input-49-e3fd25dd8c48> in <module>
      1 get_ipython().system('pip uninstall keras-nightly')
      2 import tensorflow.keras
----> 3 from keras.models import Sequential
      4 from keras.layers import Dense
      5 

~\anaconda3\lib\site-packages\keras\__init__.py in <module>
     18 from . import callbacks
     19 from . import constraints
---> 20 from . import initializers
     21 from . import metrics
     22 from . import models

~\anaconda3\lib\site-packages\keras\initializers\__init__.py in <module>
    122 # from ALL_OBJECTS. We make no guarantees as to whether these objects will
    123 # using their correct version.
--> 124 populate_deserializable_objects()
    125 globals().update(LOCAL.ALL_OBJECTS)
    126 

~\anaconda3\lib\site-packages\keras\initializers\__init__.py in populate_deserializable_objects()
     47 
     48   LOCAL.ALL_OBJECTS = {}
---> 49   LOCAL.GENERATED_WITH_V2 = tf.__internal__.tf2.enabled()
     50 
     51   # Compatibility aliases (need to exist in both V1 and V2).

AttributeError: module 'tensorflow.compat.v2' has no attribute '__internal__'
