### ISSUE TITLE
Supporting Python 3.7+?

### ISSUE THREAD

**Issue by muellerzr** [googlecolab/colabtools#1698] opened 2020-11-11 01:04 UTC
Are there plans to have Colab use Python 3.7+? We're currently wanting to utilize some of the features in a new version of the [nbdev](https://github.com/fastai/nbdev) library, but we're afraid of dropping support for Google Colab by doing so (something we want to avoid!)

TIA!

**Comment by craigcitro** [comment] 2020-11-12 01:32
duplicate of #1422

**Closed by craigcitro** 2020-11-12 01:32 UTC
