### ISSUE TITLE
Google Drive Authentication sequence fails

### ISSUE THREAD

**Issue by LanceNorskog** [googlecolab/colabtools#1564] opened 2020-09-06 04:12 UTC
Bug report for Colab: http://colab.research.google.com/.

The double-square icon to copy the authenticate code fails in the Google Drive Authentication Sequence

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
```
from google.colab import drive
drive.mount('/content/gdrive')
```
Go to new window, copy authentication code: click Copy Link double-square icon,
Open a text editor
Paste the link text.
It's not the copy code. The double-square icon link did not copy anything to the clipboard.

- Describe the expected behavior:
Double-square icon copies authentication code.

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Opera.

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):
[https://colab.research.google.com/drive/19hs_4WbCaCkRncycJvXJm6B55BviuuNg?usp=sharing](https://colab.research.google.com/drive/19hs_4WbCaCkRncycJvXJm6B55BviuuNg?usp=sharing)

**Comment by craigcitro** [comment] 2020-09-06 05:12
Duplicate of #1540

**Closed by craigcitro** 2020-09-06 05:12 UTC
