### ISSUE TITLE
Constantly disconnects

### ISSUE THREAD

**Issue by andresespinosapc** [googlecolab/colabtools#526] opened 2019-04-26 14:40 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: The runtime of any Google Colab notebook constantly disconnects in my computer. I tried with two different accounts, with multiple different notebooks and from 2 different locations with a stable internet connection. The same notebooks work fine on other computers. **Update:** It works fine in Firefox.

- Describe the expected behavior: It should not disconnect too fast.

- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome.

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*): It doesn't matter because it happens with any notebook but connected from my computer. Anyway, here's a notebook I just created and in which I have the same problem: https://colab.research.google.com/drive/1mS8tujku57s7LLmtAPrnZDcay7zsxacq

**Comment by ykchong45** [comment] 2019-05-31 15:41
Yes same problem here! I'm using GAEProxy connecting the Colab over iPv6 Internet due to some reasons. Colab **disconnects so often** that it just keep reconnecting **every 10 or 15 seconds**.

![image](https://user-images.githubusercontent.com/50497617/58717203-45a64580-83fd-11e9-85c9-b3315e8fb52b.png)

**Comment by blois** [comment] 2019-05-31 18:06
Does this issue also occur in an incognito window?
Are there any particular errors appearing in Chrome's developer tools console?

If it's still occurring could you send feedback from the Help menu- we may be able to diagnose further from there.

**Comment by ykchong45** [comment] 2019-06-01 18:16
Well in Colab I can't upload screenshot of the developer tools console so here I am again. Yes, the frequent disconnections and reconnections still occur in incogito window, and there are the same 4 errors prompted in developer tools console whenever it disconnects. 

![image](https://user-images.githubusercontent.com/50497617/58752083-47463b00-84db-11e9-997b-fc6734ee7e93.png)

**Comment by blois** [comment] 2019-06-03 16:30
b/134265501

**Comment by ThisIsManuel** [comment] 2021-12-13 20:58
Same issue using Chrome Version 96.0.4664.93 and Colab Pro (runtime keeps disconnecting within a second).  

Switching to Firefox solved the issue for me too.

**Comment by craigcitro** [comment] 2021-12-13 21:00
@ThisIsManuel does it also repro in an incognito window in Chrome?

**Comment by ThisIsManuel** [comment] 2021-12-13 21:35
> 

No, in an incognito window it works fine in Chrome too.

**Comment by blois** [comment] 2021-12-13 21:43
If it works in an incognito window then this is usually indicative of a problem caused by a browser extension. 

You can try disabling extensions in chrome://extensions to narrow down which one causes the issue. If you are able to pinpoint it please leave a note for future users!

**Comment by cperry-goog** [comment] 2021-12-16 22:19
Thanks! Closing this as we believe disconnects are connected to browser extensions.

**Closed by cperry-goog** 2021-12-16 22:19 UTC
