### ISSUE TITLE
Colab is experiencing issues connecting to Drive, and we are actively investigating.

### ISSUE THREAD

**Issue by pandiyan2019** [googlecolab/colabtools#1432] opened 2020-07-23 06:12 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: Colab is experiencing issues connecting to Drive, and we are actively investigating.

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):  Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment] 2020-07-23 16:48
Dupe of #1428. (Should now be fixed.)

**Closed by craigcitro** 2020-07-23 16:48 UTC

**Comment by anirudha-akela** [comment] 2020-07-24 05:06
I am facing this issue again while trying to read a 9GB+ file from my Drive.
