### ISSUE TITLE
A small issue editing some of my notebooks in drive on Colab 

### ISSUE THREAD

**Issue by bacloud14** [googlecolab/colabtools#433] opened 2019-02-17 07:44 UTC
Hi,

I should say, I am not sure this is an issue, but I didn't find a solution and it triggers me, seeing the wonderful functionalities that Colab offers to me doing my experimentation. 

I use two Google accounts interchangeably. With no difference I edit, create, and share files between.

For some reason, that I totally ignore, some notebooks in Python aren't being colored as any other code editor would do.  

Trying to duplicate, doesn't solve the issue.

One known difference between colored and non colored, the ones initiated empty using Colab, are well colorized. 

Thank you so much.

**Comment by craigcitro** [comment] 2019-02-17 17:07
Duplicate of #431.

I would be curious to see a copy of the failing notebook (you can even delete all the cells, I want to see the notebook metadata). Workaround is to open `Edit` -> `Notebook settings` and save the kernel type, but if you can make a copy first, that'd be awesome. 😁

**Closed by craigcitro** 2019-02-17 17:07 UTC
