### ISSUE TITLE
Connect button displayed while I'm already connected

### ISSUE THREAD

**Issue by rigolitch** [googlecolab/colabtools#3755] opened 2023-06-08 17:41 UTC
Another wtf dumb bug on colab, the third of the day, lost 3 hours and still not able to do what I was supposed to do because of all these bugs... same context than the others... if I click the button then I'm disconnected from colab, but the button is still shown... I can't link my Gdrive to Colab anymore ! This is once again, insane !
How could I trust you, when I'm facing so much bugs, everytime I'm using Colab, whatever notebook  and most of them are never fixed ?! (and I've never used the Stable diffusion UI thing you have banned last month)
![image](https://github.com/googlecolab/colabtools/assets/19718683/3506c515-288e-4c4e-b659-5426d933b3fb)

**Comment by metrizable** [comment] 2023-06-09 22:21
Duplicate of #3756

**Closed** 2023-06-09 22:20 UTC
Labels: bug
