### ISSUE TITLE
Python 3.6 is missing

### ISSUE THREAD

**Issue by MedicDoesStuff** [googlecolab/colabtools#3350] opened 2023-01-18 15:10 UTC
**Describe the current behavior**
Starting today, python 3.6 is gone from Colab which messed up some of my notebooks and altogether caused them to stop working properly.

**Describe the expected behavior**
Normally i could run my code in the same good old way.

**What web browser you are using**
Chrome

**Comment by EvanWiederspan** [comment] 2023-01-18 15:19
This likely happened with our Ubuntu upgrade. For a little bit longer, you can get back to the old version by using the "Use fallback runtime version" in the command palette after connecting to a runtime. This will not be available for that long though, and we do not plan on supporting python 3.6 going forward due to security and maintainability reasons; it has been marked as end-of-life for [over a year](https://devguide.python.org/versions/). I recommend updating your notebooks

**Comment by MedicDoesStuff** [comment] 2023-01-19 10:34
Is it about the Ubuntu 20.04 LTS update? If so, my notebooks are using much more RAM after it to the point that it almost maxes out. Do y'all have a fix for this?

**Comment by mco-gh** [comment] 2023-01-19 10:36
Can you share a minimal notebook that reproduces the memory problem so we can try to verify and debug?

**Comment by MedicDoesStuff** [comment] 2023-01-19 11:13
I don't have the time to create one right now although when training models and it dumps/autosave, the RAM usage exponentially gets higher until the RAM usage meter turns almost orange

> Can you share a minimal notebook that reproduces the memory problem so we can try to verify and debug?

**Comment by mco-gh** [comment] 2023-01-19 11:24
Thanks for the report, closing this but please reopen this issue if you get a chance to create a new, or share an existing, notebook.

**Closed by mco-gh** 2023-01-19 11:24 UTC
Labels: bug

**Comment by MedicDoesStuff** [comment] 2023-01-20 04:30
I'm back, I wasn't able to create a simplified notebook that reproduces the exact same error. But overall, the RAM usage on the newer version has been much higher compared to the previous, older ones.
