### ISSUE TITLE
Can't Open Notebooks

### ISSUE THREAD

**Issue by smccraley** [googlecolab/colabtools#4687] opened 2024-07-11 14:45 UTC
-->

Whenever I try to open a Notebook file, I receive the message:

Error
Unable to load Colab
this.element_.close is not a function
g.setVisible@https://ssl.gstatic.com/colaboratory-static/common/8338d73ca0092021ac85c9c348ae2f18/external_binary.js:5145:63
g.enterDocument@https://ssl.gstatic.com/colaboratory-static/common/8338d73ca0092021ac85c9c348ae2f18/external_binary.js:6746:465
g.enterDocument@https://ssl.gstatic.com/colaboratory-static/common/8338d73ca0092021ac85c9c348ae2f18/external_binary.js:7917:66
Fn@https://ssl.gstatic.com/colaboratory-static/common/8338d73ca0092021ac85c9c348ae2f18/external_binary.js:564:379
g.render@https://ssl.gstatic.com/colaboratory-static/common/8338d73ca0092021ac85c9c348ae2f18/external_binary.js:564:93
z9a/<@https://ssl.gstatic.com/colaboratory-static/common/8338d73ca0092021ac85c9c348ae2f18/external_binary.js:4097:99
za@https://ssl.gstatic.com/colaboratory-static/common/8338d73ca0092021ac85c9c348ae2f18/external_binary.js:16:57
xa.prototype.next_@https://ssl.gstatic.com/colaboratory-static/common/8338d73ca0092021ac85c9c348ae2f18/external_binary.js:14:195
kaa/this.next@https://ssl.gstatic.com/colaboratory-static/common/8338d73ca0092021ac85c9c348ae2f18/external_binary.js:17:48
b@https://ssl.gstatic.com/colaboratory-static/common/8338d73ca0092021ac85c9c348ae2f18/external_binary.js:17:309

The Drive directory will continue to open in an endless loop, not allowing any program to be opened, and displaying this error when I click on any file name.

**Comment by smccraley** [comment] 2024-07-11 15:34
Yes, the issue is still present.

**Comment by katlyn-edwards** [comment] 2024-07-11 16:07
Thanks for confirming, if you can, open the console and paste `window.colabVersionTag` and let us know what it says? For example mine is "colab_20240711-060152_RC00_651359636"

**Comment by smccraley** [comment] 2024-07-11 16:14
Do you mind clarifying how to open the console in Colab? I am unsure of where to paste this command. Thank you.

**Comment by katlyn-edwards** [comment] 2024-07-11 16:49
Yeah! In Chrome, it's the top right three dot menu -> more tools -> developer tools 

That should open a bottom panel, and one of the tabs should say "Console"  where you can paste the command. Let me know if you're in a different browser, and I can figure out how to open the console in that browser.

**Comment by johnthorbreaker** [comment] 2024-07-11 17:49
exactly same problem for me to on firefox

this.element_.close is not a function
g.setVisible@https://ssl.gstatic.com/colaboratory-static/common/d187fd04d8694d9fb912e0e79930a278/external_binary_l10n__id.js:5154:63
g.enterDocument@https://ssl.gstatic.com/colaboratory-static/common/d187fd04d8694d9fb912e0e79930a278/external_binary_l10n__id.js:6759:465
g.enterDocument@https://ssl.gstatic.com/colaboratory-static/common/d187fd04d8694d9fb912e0e79930a278/external_binary_l10n__id.js:7936:66
Fn@https://ssl.gstatic.com/colaboratory-static/common/d187fd04d8694d9fb912e0e79930a278/external_binary_l10n__id.js:564:379
g.render@https://ssl.gstatic.com/colaboratory-static/common/d187fd04d8694d9fb912e0e79930a278/external_binary_l10n__id.js:564:93
q9a/<@https://ssl.gstatic.com/colaboratory-static/common/d187fd04d8694d9fb912e0e79930a278/external_binary_l10n__id.js:4105:99
za@https://ssl.gstatic.com/colaboratory-static/common/d187fd04d8694d9fb912e0e79930a278/external_binary_l10n__id.js:16:57
xa.prototype.next_@https://ssl.gstatic.com/colaboratory-static/common/d187fd04d8694d9fb912e0e79930a278/external_binary_l10n__id.js:14:195
kaa/this.next@https://ssl.gstatic.com/colaboratory-static/common/d187fd04d8694d9fb912e0e79930a278/external_binary_l10n__id.js:17:48
b@https://ssl.gstatic.com/colaboratory-static/common/d187fd04d8694d9fb912e0e79930a278/external_binary_l10n__id.js:17:309

**Comment by johnthorbreaker** [comment] 2024-07-11 17:51
open on chrome work fine for me

**Comment by katlyn-edwards** [comment] 2024-07-11 18:12
@johnthorbreaker  - Do you have a version tag that we could use? See:

> Thanks for confirming, if you can, open the console and paste `window.colabVersionTag` and let us know what it says? For example mine is "colab_20240711-060152_RC00_651359636"


Also, if there's specific reproducible steps, please let us know -- e.g. does it happen on page load? A specific dialog opening or closing?

**Comment by johnthorbreaker** [comment] 2024-07-11 19:12
the problem is I can't find anyting or I'm doing wrong
![clb](https://github.com/googlecolab/colabtools/assets/175347185/7c7cec7d-01f4-4d6f-a154-2abf351a4754)

**Comment by zelliott** [comment] 2024-07-16 18:20
What browsers and browser versions are folks hitting this on? We've traced this to [`HTMLDialogElement.close`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close) not being defined , and support for that method reached FF and Safari in March 2022.

**Comment by zelliott** [comment] 2024-07-22 22:15
Additionally, we submitted some additional code that mitigates this issue. Previously, if you tried to open Colab on an old browser with no `HTMLDialogElement.close` support, Colab would fail to load with the `this.element_.close is not a function
` error. Now, with the mitigation, Colab should load, but the popup comments pane (the dialog triggered by the "Comments" button in the top bar) will be non-functional.

**Comment by cperry-goog** [comment] 2024-07-25 16:39
We've released a fix here, please open a new bug if you have issues.

**Closed by cperry-goog** 2024-07-25 16:39 UTC
Labels: bug, reply-needed
