### ISSUE TITLE
Unable to use Colab - Getting error: "Sorry, no backends available. Please try again later

### ISSUE THREAD

**Issue by dshalin** [googlecolab/colabtools#1291] opened 2020-05-30 12:37 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use stackoverflow.

Describe the current behavior: Unable to use Colab - Getting error: "Sorry, no backends available. Please try again later."

Describe the expected behavior: Expected to be used without any error.

The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

Link to self-contained notebook that reproduces this issue
(click the Share button, then Get Shareable Link):
https://colab.research.google.com/drive/1Zi-kmQ35c0T2xGRzRC2j2kBaf-NEqTuq?usp=sharing

**Comment by colaboratory-team** [comment] 2020-05-30 17:23
Duplicate of #1287

**Closed by colaboratory-team** 2020-05-30 17:23 UTC
