### ISSUE TITLE
Runtime type does not show

### ISSUE THREAD

**Issue by brbisheng** [googlecolab/colabtools#1321] opened 2020-06-10 01:38 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment] 2020-06-10 03:23
duplicate of #1322

**Closed by craigcitro** 2020-06-10 03:23 UTC
