### ISSUE TITLE
Can't Create New Notebook

### ISSUE THREAD

**Issue by rlee300** [googlecolab/colabtools#1955] opened 2021-04-11 17:14 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
I successfully created a connection to my Jupyter notebook; however, whenever I tried to create a new notebook, I receive a network error. 

![Capture](https://user-images.githubusercontent.com/82125323/114314202-99c8e900-9aae-11eb-8c82-506839a34a22.PNG)

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Edge and Chrome

**Comment by cperry-goog** [comment] 2024-05-09 16:42
Closing due to staleness. File a new bug with reproducible steps if this is an issue.

**Closed by cperry-goog** 2024-05-09 16:42 UTC
