### ISSUE TITLE
Fail to interact with folder called "checkpoints" on file-browser panel

### ISSUE THREAD

**Issue by Nntraveler** [googlecolab/colabtools#1913] opened 2021-03-19 03:17 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: 
  - when trying to create a folder under `./content/checkpoints/` using `files` on the left toolbar, an error occurred
 ```sh 
Error
Folder creation failed
Could not fetch resource at https://colab.research.google.com/tun/m/gpu-t4-s-1ncibcqw48luh/api/contents/content/checkpoints?authuser=0: 500  
FetchError: Could not fetch resource at https://colab.research.google.com/tun/m/gpu-t4-s-1ncibcqw48luh/api/contents/content/checkpoints?authuser=0: 500  
    at gy.er [as constructor] (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__en_gb.js?vrz=colab-20210317-060053-RC00_363384271:690:478)
    at new gy (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__en_gb.js?vrz=colab-20210317-060053-RC00_363384271:1304:881)
    at xa.program_ (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__en_gb.js?vrz=colab-20210317-060053-RC00_363384271:5212:449)
    at za (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__en_gb.js?vrz=colab-20210317-060053-RC00_363384271:19:336)
    at xa.next_ (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__en_gb.js?vrz=colab-20210317-060053-RC00_363384271:17:503)
    at Aa.next (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__en_gb.js?vrz=colab-20210317-060053-RC00_363384271:20:206)
    at b (https://colab.research.google.com/v2/external/external_polymer_binary_l10n__en_gb.js?vrz=colab-20210317-060053-RC00_363384271:20:467) 
```
  - Also I cannot inspect any files under `checkpoints` folder
  - However, notebook will not suffer from this problem. It seems that this problem is related to request sent by `colab-file-browser`
- Describe the expected behavior:
  - An folder under `/content/checkpoints` is created
  - Any file under `/content/checkpoints` appears in file-browser panel 
- The web browser you are using (Chrome, Firefox, Safari, etc.): Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*): https://colab.research.google.com/drive/1pcDDsuTx6MN-lCVWDpDdeOmsH0iPg7dW?usp=sharing

**Comment by craigcitro** [comment] 2021-03-19 03:23
This is a dupe of #621; you'll have to use a name other than `checkpoints` for now. (Sorry.)

**Closed by craigcitro** 2021-03-19 03:23 UTC
