### ISSUE TITLE
Notebook Meta-data Name Attribute Error

### ISSUE THREAD

**Issue by UmerFakher** [googlecolab/colabtools#1998] opened 2021-05-05 18:19 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
**For an in-depth explanation with screenshots please see: https://github.com/UmerFakher/GoogleColabNameError**

Steps to recreate issue
If we have a notebook, Original.ipynb and we do the following:

File > Save a copy to GitHub
and changing the name to Different_Copy.ipynb

The notebook will say it is Original.ipynb when you try to open it Different_Copy. See [in-depth exploration of issue](https://github.com/UmerFakher/GoogleColabNameError).

- Describe the expected behavior:

For Different_Copy.ipynb or any notebook that was originally a copy/renamed from another notebook to be accessible/openable through Colab

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Chrome

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**The copied notebook is not openable with Colab! Linking to it will simply open Original.ipynb**
https://github.com/UmerFakher/GoogleColabNameError/blob/main/Different_Copy.ipynb

**Comment by cperry-goog** [comment] 2021-05-06 22:23
Duplicate of #764

**Closed by cperry-goog** 2021-05-06 22:23 UTC
