### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by CathySunshine** [googlecolab/colabtools#3436] opened 2023-02-24 16:35 UTC
I am a google colab pro+ user, and my google drive disconnected after less than 10 hours in the background execution mode. 

I need to save checkpoints, for example, every 50 epochs. Colab Pro + users are supposed to have up to 24 hours of continuous running time. I am not using GPUs but only high RAM CPU in colab. Although the colab note is still running, disconnecting from my google drive (I save checkpoint results into my drive) causes program termination. It leads to an error saying, "transport endpoint is not connected."

If I save results on the local VM, I lose all the results when I open the notebook after the job is finished.

Following is what I have tried but not working:

I have tried the method mentioned in "Frequently Asked Questions": empty my drive trash and subfolder files. However, it still didn't work. I also restarted the runtime every time before I started running the code.

Is there a way to stop my mounted drive from disconnecting? Or is there a good way to save my checkpoint results?

**Comment by cperry-goog** [comment] 2023-03-02 17:54
dupe of #3441

**Closed by cperry-goog** 2023-03-02 17:54 UTC
