### ISSUE TITLE
Colab is not connecting to google drive

### ISSUE THREAD

**Issue by BrianChegeGichau** [googlecolab/colabtools#1435] opened 2020-07-23 09:29 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:
Ram is inefficient
- Describe the expected behavior:
Should be able to run the codes just fine
- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome
- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by craigcitro** [comment] 2020-07-23 16:47
Dupe of #1428. (Should now be fixed.)

**Closed by craigcitro** 2020-07-23 16:47 UTC
