### ISSUE TITLE
Continuous disconnect

### ISSUE THREAD

**Issue by vikbehal** [googlecolab/colabtools#66] opened 2018-02-21 07:40 UTC
The nb disconnects continuously. Kindly advise.

Mode - GPU

**Comment by fischman** [comment] 2018-02-22 07:50
Can you share a minimal repro notebook with colaboratory-team@google.com noting this issue's URL in the share message?

**Comment by SpireFlux** [comment] 2018-03-12 19:47
I'm getting the same errors.

**Comment by fischman** [comment] 2018-03-12 20:29
@SpireFlux your notebook relies on data in your drive. Can you repro with public data?
At any rate I note that your notebook calls tf.Session() without the config options recommended by the GPU example notebook at https://colab.research.google.com/notebooks/gpu.ipynb
You really want something like

```
# See https://www.tensorflow.org/tutorials/using_gpu#allowing_gpu_memory_growth
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
with tf.Session(config=config) as session:
  ...
```

**Comment by pointyointment** [comment] 2018-04-10 20:04
I'm having a similar problem, but not using TensorFlow. I'm trying to use PyTorch, but I run into the problem before I get to that part of the notebook, so I don't think it's PyTorch's fault.

I'm trying to run the `process()` function from [here](https://www.kaggle.com/cloudfall/pytorch-tutorials-on-dsb2018?scriptVersionId=2305973/notebook) on files stored on my Google Drive, and it never succeeds because it takes a few minutes to run, during which time the runtime disconnects. This is before I get to the point of defining a PyTorch dataset class, let alone instantiating it on the data loaded by `process()`.

Is there some bug in that function that intermittently causes the runtime to crash on a random iteration of the loop, or is the runtime just unreliable?

**Comment by clemente620** [comment] 2019-02-01 02:04
no working 
always runtime disconnected

**Comment by colaboratory-team** [comment] 2019-03-16 20:29
Duplicate of #58

**Closed by colaboratory-team** 2019-03-16 20:29 UTC

**Comment by ShivamRawat0l** [comment] 2019-07-28 04:48
@clemente620  https://medium.com/@shivamrawat_756/how-to-prevent-google-colab-from-disconnecting-717b88a128c0 Maybe this could prevent it from disconnecting. But internet should be connected.

**Comment by nitsanra** [comment] 2020-02-24 10:52
> @clemente620 https://medium.com/@shivamrawat_756/how-to-prevent-google-colab-from-disconnecting-717b88a128c0 Maybe this could prevent it from disconnecting. But internet should be connected.

nop, this does not help,
I started having the same problem few days ago, until then, it was fine and I was able to run a notebook for few hours, and when disconnected it was possible to reconnect to the same host and not lose the data.
Since few days, Colab keeps disconnecting after ~1 hour, and the local data is gone :-(

**Comment by kunakl07** [comment] 2020-06-05 09:13
Since yesterday my colab notebook is getting continuously disconnected(it's getting connected for 2-3 seconds and then it gets disconnected).
Could you please advice a solution
