### ISSUE TITLE
Transport End point not connected

### ISSUE THREAD

**Issue by RimshaShoukat** [googlecolab/colabtools#3874] opened 2023-07-25 15:02 UTC
Collab Pro Plus is giving me a strange error. 
After 4 hours of training, it starts giving a 'file not found' error and a 'Transport endpoint not connected' error after 4hrs of training, even though the model has already run 6 epochs with the same data. I kindly request you to look into this issue. I am really worried about it as I have to submit my project as soon as possible. I hope you will review this problem and respond promptly.

**Comment by mayankmalik-colab** [comment] 2023-07-27 16:36
dupe of https://github.com/googlecolab/colabtools/issues/3441

**Comment by cperry-goog** [comment] 2024-11-15 04:28
This was an ephemeral issue from Drive which they resolved a few months back, closing - please do open a bug if you see it again.

**Closed by cperry-goog** 2024-11-15 04:28 UTC
Labels: bug, triaged
