### ISSUE TITLE
%edit not working

### ISSUE THREAD

**Issue by korakot** [googlecolab/colabtools#1670] opened 2020-10-29 09:47 UTC
- Describe the current behavior:

When I call `%edit mylib.py` it does nothing.

- Describe the expected behavior:

It should open `mylib.py` for me to edit.

- The web browser you are using (Chrome, Firefox, Safari, etc.):

Firefox

- Link to a *minimal, public, self-contained* notebook that
  reproduces this issue:

https://colab.research.google.com/drive/1jdwGBAnAm6PphjhigymAtkedxMYUt4yA?usp=sharing

I tried to solve this myself, but get stuck. See details in the shared notebook above.

**Comment by craigcitro** [comment] 2020-10-29 17:18
Agreed that it would be nice if this worked; this has the same root cause as #42 so closing as dupe.

**Closed by craigcitro** 2020-10-29 17:18 UTC

**Comment by korakot** [comment] 2020-10-30 00:53
@craigcitro The issue is similar. But this one can be solved easily.

Just tell me the JavaScript source code of `google.colab.files.view`. Currently, I only have

    function(c){ a.b.sendMessage("view_file",{path:c, lineNumber:void 0}) }

What is a, b? My Colab above show the almost complete solution. Only this part is missing.

**Comment by korakot** [comment] 2020-10-30 01:02
The root cause is probably different too. Colab couldn't possibly open a VIM or Nano text editor to edit the file. You must use the colab built-in text editor. Just call:

    from google.colab import files
    files.view(path_to_file)

So, the root cause is that you didn't specify the default text editor. Also, there is no python way to specify line-num to jump to.

Do I understand the issue correctly? @blois ?
