### ISSUE TITLE
I can´t log with my Google Educational account

### ISSUE THREAD

**Issue by isipavelek** [googlecolab/colabtools#2318] opened 2021-09-29 13:54 UTC
I try to log in Google Colabortory with my educational account but it´s not enable. Using the admin console.
I enable the Access to additional services is enabled without individual control of all organizational units for all users. However i can´t log with my educational account.

**Comment by craigcitro** [comment] 2021-09-29 16:02
duplicate of #2264

**Closed by craigcitro** 2021-09-29 16:02 UTC
Labels: bug
