### ISSUE TITLE
Autocomplete does NOT work at all.

### ISSUE THREAD

**Issue by zechzhao** [googlecolab/colabtools#1695] opened 2020-11-08 17:22 UTC
Bug report for Colab: http://colab.research.google.com/.

For 
- Describe the current behavior:
Tab only gives two spaces after say np.random.
ctrl+space is input method switch on ubuntu

- Describe the expected behavior:
autocomplete selection list should appear. 

- The web browser you are using (Chrome, Firefox, Safari, etc.):
Chrome & Safari 

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by mihailisin** [comment] 2020-12-17 17:24
Have the same issue.

auto completion does not work for my ipynb. 
i hit "ctrl+space" and get the popup "no suggestions".

**Comment by AaronBiddle** [comment] 2021-07-29 11:36
It wasn't working for me either. On Windows 10 using Chrome. After 20 minutes of trying random things I closed the table of contents on the left pane and it started working again. I am not sure if it was closing the table of contents or some other thing I did or maybe just waiting 20 minutes or perhaps the stars in the universe aligned properly, but it started working again.

**Comment by craigcitro** [comment] 2021-07-29 16:08
@AaronBiddle that "closing TOC fixes" bit is interesting, but I can't seem to repro.

Can you confirm if (1) it's reproducible on your side, (2) if it's restricted to a single notebook, and (3) if you can repro in incognito?

**Comment by AaronBiddle** [comment] 2021-07-30 11:42
I just solved the issue I was having. I wasn't aware that colab wouldn't autocomplete from a library until I executed the code that imported the library I was referencing. Since I would often import libraries and run the relevant code in the same code block, it appeared to me that autocomplete wasn't working. With prior execution of the imports everything is now running perfectly.

**Closed** 2021-07-30 15:39 UTC
Labels: reply-needed, triaged
