### ISSUE TITLE
Printing Issue

### ISSUE THREAD

**Issue by Gautampdy** [googlecolab/colabtools#4817] opened 2024-09-02 06:45 UTC
while printing and saving, all pages are not considered it is showing out of bound issue. 

**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by saifulfadzli** [comment] 2024-09-03 01:23
Describe the current behavior
Since Saturday 31 Aug 2024, when I click the File -> Print button and chose "Safe To PDF", the preview only shown "1 Sheet of Paper". I can only print 1 page of ipynb notebook. It should be a few pages.

**Describe the expected behavior**
Until a few days ago (Friday 30 Aug 2024), I click the File -> Print button. I chose "Save To PDF". The preview shown a few pages of ipynb notebook can be printed. This is the expected normal behaviour of the print function I have been using before Friday 30 Aug 2024.  

What web browser you are using:
Chrome 127.0.6533.120, Firefox 129.0.1

Additional context
Link to a minimal, public, self-contained notebook that reproduces this issue:

https://colab.research.google.com/drive/1NBnq27jiTE8Qwkw49rhv4O_Sj-u9TWbq?usp=sharing

**Comment by ayushchaware08** [comment] 2024-09-04 15:09
I am facing the same issue not only with me but also with my fellowmate.

**Comment by cperry-goog** [comment] 2024-09-05 16:33
Dupe of #4815

**Closed by cperry-goog** 2024-09-05 16:33 UTC
Labels: bug
