### ISSUE TITLE
On opening colab notebook webpage says Loading.... and stays blank

### ISSUE THREAD

**Issue by akhil512** [googlecolab/colabtools#2249] opened 2021-09-17 03:41 UTC
**Describe the current behavior**
Whenever I was trying to open any colab from my google drive it says loading and the screen stay blank forever, earlier I was able to open notebooks without any issue.

**Describe the expected behavior**
Ideally, it should open the particular notebook

**What web browser you are using**
Tried opening in Chrome, Firefox, Safari, Edge and also tried to open in incognito browsers of these browsers.

**Additional context**
Link to the notebook which I have observed this issue [click here](https://drive.google.com/file/d/18iMjc6ez47R1kreZMkAsl0-qryPlKlUu/view?usp=sharing)
Link to the screen snip of the error [click here](https://drive.google.com/file/d/1mBeVTaOxic_QFz46ncDMjWTd5o6jqGJ5/view?usp=sharing)

**Comment by shivani21998** [comment] 2021-09-17 05:17
Facing the same issue
attachment with the error in the console is attached below
![Capture](https://user-images.githubusercontent.com/29472727/133728421-573bdd6f-a9ba-4538-8bc2-f41c6612beff.JPG)
e

**Comment by nikhilkalyankar** [comment] 2021-09-17 06:39
Working only if I change my IP address and open in incognito mode.

![Working only if changed ipaddress and using incognito](https://user-images.githubusercontent.com/9170462/133736068-78b42abd-8729-4418-b0d3-3936a213aa4a.PNG)

**Comment by krag-harsh** [comment] 2021-09-17 13:22
Having the same issue :(

**Comment by craigcitro** [comment] 2021-09-17 18:20
Duplicate of #2250

**Closed by craigcitro** 2021-09-17 18:20 UTC
Labels: bug
