### ISSUE TITLE
Unable to load google colab - loading error

### ISSUE THREAD

**Issue by green93** [googlecolab/colabtools#2253] opened 2021-09-17 16:49 UTC
![Screenshot from 2021-09-17 22-20-31](https://user-images.githubusercontent.com/27999714/133825174-db9e3664-8a7a-4152-85a5-828712c73e43.png)

**Describe the current behavior**
Since yesterday i was not able to open google colab. It stuck on loading while showing no error. But currently i am able to see editor, but not able to connect to runtime (GPU or CPU). It's showing error. I am using PRO version of COLAB. I have disabled TRACKING and AD BLOCKER on FIREFOX. Same issue persists on CHROME as well.
![Screenshot from 2021-09-17 22-18-31](https://user-images.githubusercontent.com/27999714/133824909-2c58783f-88fb-40c9-b8b4-fb4af1c59d7b.png)

**What web browser you are using**
Chrome, Firefox

**Comment by craigcitro** [comment] 2021-09-17 18:19
Duplicate of #2250

**Closed by craigcitro** 2021-09-17 18:19 UTC
Labels: bug
