### ISSUE TITLE
ctrl-[ multiple selected lines causes SyntaxError: Unexpected token S in JSON at position 0

### ISSUE THREAD

**Issue by am717171** [googlecolab/colabtools#477] opened 2019-03-13 04:41 UTC
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by colaboratory-team** [comment] 2019-03-13 05:30
Duplicate of #476

**Closed by colaboratory-team** 2019-03-13 05:30 UTC
