### ISSUE TITLE
Allocating resources takes a lot of time

### ISSUE THREAD

**Issue by KarthikMgk** [googlecolab/colabtools#425] opened 2019-02-12 19:03 UTC
Hey,
I'm trying to run some simple import statements and colab takes forever to allocate resources. I'm not sure what is happening. Tried resetting runtimes, refreshing the tab and reopening the colab from drive. Nothing worked!!!

**Comment by colaboratory-team** [comment] 2019-02-12 19:49
Duplicate of #426

**Closed by colaboratory-team** 2019-02-12 19:49 UTC
