### ISSUE TITLE
Failed to execute cell. Could not send execute message to runtime: XhrHttpError: Request Failed, status=503, url=https://colab.research.google.com/tun/m/m-s-1n0phamwuj5kl/api/sessions?authuser=0

### ISSUE THREAD

**Issue by Sushila-Phogat** [googlecolab/colabtools#1284] opened 2020-05-30 10:19 UTC
Request Failed, status=503, url=https://colab.research.google.com/tun/m/m-s-1n0phamwuj5kl/api/sessions?authuser=0
XhrHttpError: Request Failed, status=503, url=https://colab.research.google.com/tun/m/m-s-1n0phamwuj5kl/api/sessions?authuser=0
    at AC.zC [as constructor] (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200528-085601-RC00_313572190:1027:443)
    at new AC (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200528-085601-RC00_313572190:1028:56)
    at XMLHttpRequest.f.onreadystatechange (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200528-085601-RC00_313572190:1026:183)

**Comment by Sushila-Phogat** [comment] 2020-05-30 10:20
> Request Failed, status=503, url=https://colab.research.google.com/tun/m/m-s-1n0phamwuj5kl/api/sessions?authuser=0
> XhrHttpError: Request Failed, status=503, url=https://colab.research.google.com/tun/m/m-s-1n0phamwuj5kl/api/sessions?authuser=0
> at AC.zC [as constructor] (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200528-085601-RC00_313572190:1027:443)
> at new AC (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200528-085601-RC00_313572190:1028:56)
> at XMLHttpRequest.f.onreadystatechange (https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200528-085601-RC00_313572190:1026:183)

**Comment by Sushila-Phogat** [comment] 2020-05-30 10:22
Please provide solution for my issue

**Comment by colaboratory-team** [comment] 2020-05-30 17:35
Duplicate of #1287

**Closed by colaboratory-team** 2020-05-30 17:35 UTC
