### ISSUE TITLE
Tensorboard in Colab got 403 error even when Third-party cookies are allowed (Google Chrome)

### ISSUE THREAD

**Issue by jaigitrep159** [googlecolab/colabtools#3990] opened 2023-09-08 08:21 UTC
**Describe the current behavior**
Just got a 403 error when trying to launch tensorboard in colab.

Screenshot:
![image](https://github.com/googlecolab/colabtools/assets/76834328/9d5f2a3a-5c58-4178-a061-37b68e70035f)

and when i try directing from the site (e.g. `https://0g3k40fl0s271-496ff2e9c6d22116-6006-colab.googleusercontent.com/?tensorboardColab=true`), it doesn't get a 403 error:
![image](https://github.com/googlecolab/colabtools/assets/76834328/6e33c90b-8b7d-4ced-9906-57e69eb827d7)

I have enabled third-party cookies like in the screenshot:
![image](https://github.com/googlecolab/colabtools/assets/76834328/6ad8c491-7db0-44b2-917a-3d1a7e7cd83f)

**Describe the expected behavior**
1. from this notebook https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_in_notebooks.ipynb
2. I execute the cell here:
![image](https://github.com/googlecolab/colabtools/assets/76834328/3486e06d-d9a3-443c-9128-fd1d74fcd7ec)
and there:
![image](https://github.com/googlecolab/colabtools/assets/76834328/ab7bcaa9-0756-409f-b2d1-79a24215f7c5)
seems like an iframe issue.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.) Google Chrome Version 116.0.5845.180 (Official Build) (64-bit)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.
 https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_in_notebooks.ipynb

**Comment by jaigitrep159** [comment] 2023-09-09 09:06
UPDATE: i restarted the computer, still not working. Even when restart the chrome browser

**Comment by Jayzhang2333** [comment] 2023-09-11 03:43
same, it was fine last week and I did not change  anything. It just happened

**Comment by metrizable** [comment] 2023-09-11 16:59
@jaigitrep159 Thanks for filing the issue.

I've taken the [notebook](https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_in_notebooks.ipynb) you supplied and tried to replicate the issue you're experiencing. I successfully launched and displayed tensorboard in Colab:

![8JAgXQakcHipccg](https://github.com/googlecolab/colabtools/assets/65414824/1fcb5efb-9579-4b7b-b570-73cb14d974de)

Can you describe in greater detail what you're attempting? The first part of the issue description seems to indicate some activity other than what's in the minimal repro notebook supplied

**Comment by justinjohn0306** [comment] 2023-09-13 09:12
doesn't work for me either

**Comment by justinjohn0306** [comment] 2023-09-13 09:13
> @jaigitrep159 Thanks for filing the issue.
> 
> I've taken the [notebook](https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_in_notebooks.ipynb) you supplied and tried to replicate the issue you're experiencing. I successfully launched and displayed tensorboard in Colab:
> 
> ![8JAgXQakcHipccg](https://user-images.githubusercontent.com/65414824/267093050-1fcb5efb-9579-4b7b-b570-73cb14d974de.png)
> 
> Can you describe in greater detail what you're attempting? The first part of the issue description seems to indicate some activity other than what's in the minimal repro notebook supplied

no matter what you do, tensorboard fails to load.

**Comment by kailukowiak** [comment] 2023-09-13 13:56
I'm also facing this issue. I have this setup on my chrome:
![image](https://github.com/googlecolab/colabtools/assets/27589714/e9de1d56-b725-433e-90dd-c5998fb96fbb)

**Comment by cperry-goog** [comment] 2023-09-14 16:37
Does this reproduce in Chrome incognito mode? This could be the result of a Chrome extension conflicting.

**Comment by mkrauter** [comment] 2023-09-14 17:11
Confirmed not working in Chrome incognito mode either.

**Comment by UtkuEla** [comment] 2023-09-14 18:24
I have the same issue and confirm that it does not work in Opera either.

**Comment by mkrauter** [comment] 2023-09-15 11:00
Did a clean reinstall of Chrome, no success.
It works fine in Edge, however... 😉

**Comment by kailukowiak** [comment] 2023-09-15 13:28
> Did a clean reinstall of Chrome, no success. It works fine in Edge, however... 😉

@mkrauter How to expedite a bug fix with an Alphabet product? Show all the browsers their product does work in 😂

**Comment by mkrauter** [comment] 2023-09-15 14:27
@kailukowiak Haha, that was just a small revenge for me spending three hours trying to trace the issue on my side. BTW, forgot to mention that Tensorboard loads fine in Android Chrome, though I don't find that much convenient... 😉

**Comment by koktavy** [comment] 2023-09-19 22:49
I see this error in the console:
```
GET https://hej6g88dots5-496ff2e9c6d22116-6006-colab.googleusercontent.com/?tensorboardColab=true 403
```
That address does show up in the site settings of Chrome. I can accept all available permissions (a number are blocked and greyed out) then reload the frame within Colab, but there is still nothing besides a 403 page.

**Comment by yatbear** [comment] 2023-09-21 19:17
I tested running this Colab in Safari and TensorBoard loads.

**Comment by SophieDC98** [comment] 2023-10-02 14:22
Same issue here... Deleted all chrome extensions, allowed all cookies, restarted the browser, restarted the computer. No luck

**Comment by yonggari95** [comment] 2023-10-06 12:15
same issue unsloved either :(
worked fine last week but not now without any changes :(

**Comment by nakabonne** [comment] 2023-10-15 04:50
same here

**Comment by hengqujushi** [comment] 2023-10-16 10:18
same here

**Comment by dgl2000** [comment] 2023-10-16 21:25
same here, it worked fine 2 weeks ago...

**Comment by Ammar-Azman** [comment] 2023-10-17 05:54
I used Brave, then Go to Setting > Shield > Block Cookies > Disable. Tensorboard works like charm.

**Comment by josem7** [comment] 2023-10-17 16:49
Same here :(

**Comment by Chiauwen** [comment] 2023-10-18 14:28
same here T_T

**Comment by v187965** [comment] 2023-10-18 23:54
Same here =/ Did anyone find a solution?

**Comment by kailukowiak** [comment] 2023-10-19 00:07
> Same here =/ Did anyone find a solution?

Use Firefox

**Comment by bileschi** [comment] 2023-10-23 17:59
Googlers: tracked internally at b/301984066

**Comment by Ammar-Azman** [comment] 2023-10-25 01:45
> Same here =/ Did anyone find a solution?

https://github.com/googlecolab/colabtools/issues/3990#issuecomment-1765715921

**Comment by itfrom** [comment] 2023-10-25 08:19
I tested it on two different versions of Chrome.
1. Version 118.0.5993.88 (Official Build) (arm64)
2. Version 116.0.5845.140 (Official Build) (arm64)

Tensorboard in Colab works well on the old version (2) although it doesn't work on the current version (1).

It seems that the new version of Chrome blocks Tensorboard in Colab for some reason.

**Comment by leedh** [comment] 2023-10-25 08:20
I tested it on two different versions of Chrome.

Version 118.0.5993.88 (Official Build) (arm64)
Version 116.0.5845.140 (Official Build) (arm64)
Tensorboard in Colab works well on the old version (2) although it doesn't work on the current version (1).

It seems that the new version of Chrome blocks Tensorboard in Colab for some reason.

**Comment by Srgr0** [comment] 2023-10-27 10:27
Maybe this should help:
https://gist.github.com/Srgr0/b31c87447349e90621d42a59a8e8655d

**Comment by vansh-31** [comment] 2023-10-27 12:42
Use FireFox or if u want to run it on chrome then
Right Click > click on inspect > go to network tab > Search the "?tensorboardColab=true" u can use the filter (Enter the port number on which tensorboard was running normally 6006) to reduce the search space > then just double click on it or copy the requestedURL and paste it on a new page

**Comment by Chiauwen** [comment] 2023-10-30 09:22
I found the solution as well, just run the things on local PC everything will be fine.
In my case, I run it on Visual Studio Code.

**Comment by bileschi** [comment] 2023-10-30 12:50
Posting an update here - the Google internal Colab team is working with the Google internal Chrome team to determine a cause.  Our apologies that this is causing so much trouble.  I'll post the most recent bug update, from Oct 27:

"""
Thank you everyone for your patience, we start looking into this in more depth this week. The main workarounds right now are to either, when using Chrome, to use serve_kernel_port_as_window instead of serve_kernel_port_as_iframe (although this may also break in the future). Or serve_kernel_port_as_iframe seems to still be working in other browsers like Firefox

Here's where we are currently, I'm hoping for some help from the Chrome team on whether the behavior we're seeing is expected.

You can see the breakage in this notebook (INTERNAL LINK REDACTED), the second cell returns 403 when it should be returning a JS code snippet written by the previous cell.

For proxying traffic to the runtime, we use a service worker, registered within a iframe in the *-colab.googleusercontent.com subdomain that proxies traffic going to localhost to the user VM instead. This behavior breaks when the "Experimental third-party storage partitioning" experiment is enabled in Chrome (which is now on for 100% of users in the stable release)

It's not entirely clear to me why that is the case, since this continues to work in Firefox and Safari, which also partition service workers.

Note the difference in Service Worker clients based on experiment state. With the experiment off, and the feature working, the service worker has two clients in the same domain, which makes sense since there are two iframes that it should be working with:

With the experiment enabled, the only client is outputframe.html, which initially loads the service worker:
This seems like a Chrome bug; why can't it get the second client when it comes from the exact same domain?
We've seen some success with document.requestStorageAccess() resolving this issue, and will continue to look into that as well
"""

**Comment by jchwenger** [comment] 2023-11-02 10:31
Same issue here but also in Firefox, even after allowing all cookies and disabling all plug-ins? On Ubuntu 20. I may have missed this, but it is frustrating, I am no longer able to use TB in Colab at all...

**Comment by SetoKaiba** [comment] 2023-11-07 19:18
Is there any update on this? It's working in Oct, 28 by enabling 3rd party cookies. But it's not working now.

**Comment by bileschi** [comment] 2023-11-07 22:36
FWIU Colab has a fix.  It works internally at Google in the sandbox environment and will be made available through their roll out process.  I unfortunately don't have an estimate of how long it will take to make it to public Colab.
Googlers see https://b.corp.google.com/issues/301984066#comment24

**Comment by EvanWiederspan** [comment] 2023-11-08 17:24
Thank you everyone for your patience on this, we rolled out the fix to prod last night and it should be working now. This ended up being caused by a bug in Chrome in the Service Worker partitioning feature that had rolled out

Both `serve_kernel_port_as_iframe` and `serve_kernel_port_as_window` should now be working in Chrome. Note that  `serve_kernel_port_as_window` is planned for deprecation, and is only working right now due to https://bugs.chromium.org/p/chromium/issues/detail?id=1498580. We expect it to stop working once that bug is fixed in Chrome

`serve_kernel_port_as_iframe` should continue to keep working

**Comment by Srgr0** [comment] 2023-11-09 16:20
I have confirmed that the problem is resolved in Chrome for Mac 119.0.6045.123 (Official Build, arm64).

Thanks to the Chromium team.

![ScreenShot 2023-11-10 1 11 16](https://github.com/googlecolab/colabtools/assets/66754887/42010e48-f479-4641-862d-eba588bd07a4)

**Comment by kailukowiak** [comment] 2023-11-09 17:00
Big thanks to everyone who worked on this.

**Closed** 2023-11-09 17:32 UTC
Labels: bug

**Comment by bileschi** [comment] 2023-11-09 20:58
Great job everyone.  Thanks especially to our users for their feedback and patience.  It's great to have such a wonderful community

**Comment by ManzarIMalik** [comment] 2024-04-18 17:24
It is not working again for me, I have tried all possible solutions mentioned in this thread. 

Chrome Version 124.0.6367.61 (Official Build) (64-bit)

**Comment by EvanWiederspan** [comment] 2024-04-18 18:20
I see https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_in_notebooks.ipynb working for me just fine on current chrome beta, 125.0.6422.4 (Official Build) beta (64-bit)

**Comment by g-i-o-r-g-i-o** [comment] 2024-07-06 09:30
same, I'm looking for alternatives to tensorboard.
It works one day, than the next day it stops working. Same config.
