### ISSUE TITLE
google-auth library version is too low

### ISSUE THREAD

**Issue by tigersoldier** [googlecolab/colabtools#1806] opened 2021-01-09 00:47 UTC
The `google-colab` package pins `google-auth` version to 1.17.2, which does not support `quota_project_id` attribute. It will cause error when running the following code:

```python
! pip3 install -U google-cloud-aiplatform

from google.cloud.aiplatform import gapic as aip

client_options = {"api_endpoint": API_ENDPOINT}
client = aip.DatasetServiceClient(
    client_options=client_options
)
```

The error is:

```
    157             if credentials is None:
    158                 credentials, _ = auth.default(
--> 159                     scopes=self.AUTH_SCOPES, quota_project_id=quota_project_id
    160                 )
    161 

TypeError: default() got an unexpected keyword argument 'quota_project_id'
```

**Comment by craigcitro** [comment] 2021-01-29 22:55
(duplicate of #1181)

**Comment by craigcitro** [comment] 2021-01-29 22:56
Actually, I take that back -- this is indeed a different issue.

I've submitted a change that should avoid this friction going forward; I'll update the bug again once it's live.

**Comment by craigcitro** [comment] 2021-02-02 18:41
This should be fixed!

**Closed by craigcitro** 2021-02-02 18:41 UTC
