### ISSUE TITLE
runtime died using Pytorch for LSTM

### ISSUE THREAD

**Issue by adityak2920** [googlecolab/colabtools#312] opened 2018-10-21 06:17 UTC
I have tried many times but every time runtime died restarting automatically
you can check the code here:z
https://colab.research.google.com/drive/1wQ2KtxijKt9FNeOknnWNj22-LSx4u7xZ#scrollTo=dCVUpxfsJXWN

**Comment by soumith** [comment] 2019-05-01 02:44
i'm sure this was fixed by #412

**Comment by metrizable** [comment] 2023-04-08 00:36
Since this issue was filed a while ago, and there have been a number of upgrades to our ecosystem including PyTorch since then, if you are still experiencing the issue, please re-open and provide a minimal reproducible notebook.

**Closed by metrizable** 2023-04-08 00:36 UTC
