### ISSUE TITLE
Xarray does not work in Google colab

### ISSUE THREAD

**Issue by ngohikennyyue** [googlecolab/colabtools#3134] opened 2022-10-08 03:47 UTC
The package xarray appear to not working since this morning. I have written some script that was utilizing xarray to load and interpolate netcdf data last night. But this morning when I went back to the same script and run it again it shows an attribute error 
`AttributeError: 'EntryPoints' object has no attribute 'get'`
To make sure my data sources is not corrupted, I inspected and can open it with netcdf4 package smoothly without any hiccups. 

I tried to open built in tutorial / sample dataset with xarray  and it also appears with the same error message
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-1-daa755d2bb23>](https://localhost:8080/#) in <module>
      1 import xarray as xr
----> 2 xr.tutorial.load_dataset('air_temperature')

4 frames
[/usr/local/lib/python3.7/dist-packages/xarray/backends/plugins.py](https://localhost:8080/#) in list_engines()
    103 @functools.lru_cache(maxsize=1)
    104 def list_engines():
--> 105     entrypoints = entry_points().get("xarray.backends", ())
    106     return build_engines(entrypoints)
    107 

AttributeError: 'EntryPoints' object has no attribute 'get'
```

I'm using Google chrome to open Google Colab

The link to the error example
https://colab.research.google.com/drive/1OoT690jTQXtCvTAdpjUkpaKxvjcGO7vg?usp=sharing

https://gist.github.com/ngohikennyyue/dd32aa575be131f736b44d98b07212cd

Appreciate your time and attention. 
Thanks

**Comment by dfbustosus** [comment] 2022-10-13 14:22
I had the same Issue . The problem seems to be importlib-metadata 5.0.0 which was released some days ago that deprecates the old entry point system.

I solved with the following commands:

!pip install importlib-metadata==4.0.1
!pip install xarray==0.18.1

Then restart the kernel in colab (Ctrl + M .) and it should be work. If you dont restart the kernel before using xarry it will not work.

Best regards

**Comment by colaboratory-team** [comment] 2022-10-13 14:34
Thanks for the fix dfbustosus, we'll downgrade importlib-metadata back to a version that works with our version of xarray

**Comment by bertcoerver** [comment] 2022-10-18 09:41
Having the same problem, 4.13.0 is the most recent version before 5.0.0 that works with colabs xarray version.

**Comment by colaboratory-team** [comment] 2022-10-19 21:15
We are now downgraded back to importlib-metadata==4.13.0, and I confirmed the xarray snippet from the report works now. Closing this out, thanks for the report

**Closed by colaboratory-team** 2022-10-19 21:15 UTC
Labels: bug
